# -*- coding: utf-8 -*-
import re

with open('index.html', 'r', encoding='utf-8') as f:
    source_ru = f.read()

def clean_comments_and_scripts(text):
    # CSS comments containing Cyrillic
    text = re.sub(r'/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+/', lambda m: '' if re.search(r'[\u0400-\u04FF]', m.group(0)) else m.group(0), text)
    # HTML comments containing Cyrillic
    text = re.sub(r'<!--.*?-->', lambda m: '' if re.search(r'[\u0400-\u04FF]', m.group(0)) else m.group(0), text, flags=re.DOTALL)
    # JS single line comments containing Cyrillic
    text = re.sub(r'//[^\n]*?[\u0400-\u04FF]+[^\n]*', '', text)
    return text

# Comprehensive master dictionary
# Each entry is (ru_text, en_text, tr_text)
translations = [
    # Top & Meta
    ('<html lang="ru"', '<html lang="en"', '<html lang="tr"'),
    ('Altai Optima — Autonomous AI Business Architecture', 'Altai Optima — Autonomous AI Sales Architecture', 'Altai Optima — Otonom AI Satış Mimarisi'),
    ('Altai Optima — Автономный AI-отдел продаж', 'Altai Optima — Autonomous AI Sales Architecture', 'Altai Optima — Otonom AI Satış Mimarisi'),
    ("fill='rgba(2,132,199,0.035)' letter-spacing='4'%3E%D0%A0%D0%95%D0%97%D0%AE%D0%9C%D0%95%3C/text%3E", "fill='rgba(2,132,199,0.035)' letter-spacing='4'%3ERESUME%3C/text%3E", "fill='rgba(2,132,199,0.035)' letter-spacing='4'%3EOZGEMIS%3C/text%3E"),

    # Switchers
    ('<span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">RU</span>\n          <a href="en.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">EN</a>\n          <a href="tr.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">TR</a>',
     '<a href="index.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">RU</a>\n          <span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">EN</span>\n          <a href="tr.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">TR</a>',
     '<a href="index.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">RU</a>\n          <a href="en.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">EN</a>\n          <span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">TR</span>'),
    ('<span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">RU</span>\n            <a href="en.html" class="px-2 py-0.5 rounded-full hover:text-white transition">EN</a>\n            <a href="tr.html" class="px-2 py-0.5 rounded-full hover:text-white transition">TR</a>',
     '<a href="index.html" class="px-2 py-0.5 rounded-full hover:text-white transition">RU</a>\n            <span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">EN</span>\n            <a href="tr.html" class="px-2 py-0.5 rounded-full hover:text-white transition">TR</a>',
     '<a href="index.html" class="px-2 py-0.5 rounded-full hover:text-white transition">RU</a>\n            <a href="en.html" class="px-2 py-0.5 rounded-full hover:text-white transition">EN</a>\n            <span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">TR</span>'),

    # Navigation & Header
    ('>КЕЙСЫ<', '>CASES<', '>VAKALAR<'),
    ('>КАЛЬКУЛЯТОР<', '>CALCULATOR<', '>HESAPLAYICI<'),
    ('>АРХИТЕКТУРА<', '>ARCHITECTURE<', '>MİMARİ<'),
    ('>РЕЗЮМЕ СОТРУДНИКА<', '>AI RESUME<', '>AI ÖZGEÇMİŞ<'),
    ('>РЕЗЮМЕ<', '>RESUME<', '>ÖZGEÇMİŞ<'),
    ('>ТЕСТОВЫЙ ЗАПУСК<', '>TEST PILOT<', '>TEST PİLOTU<'),
    ('>ТЕСТ<', '>TEST<', '>TEST<'),
    ('СВЯЗАТЬСЯ С МЕНЕДЖЕРОМ', 'CONTACT MANAGER', 'YÖNETİCİYE ULAŞIN'),
    ('title="Подняться наверх"', 'title="Back to Top"', 'title="Yukarı Çık"'),
    ('title="Написать в Telegram"', 'title="Message via Telegram"', 'title="Telegram\'dan Yazın"'),
    ('title="Написать в WhatsApp"', 'title="Message via WhatsApp"', 'title="WhatsApp\'tan Yazın"'),
    ('title="Листайте вниз к возможностям"', 'title="Scroll down to explore features"', 'title="Özellikleri keşfetmek için aşağı kaydırın"'),
    ('Скролл вниз', 'Scroll Down', 'Aşağı Kaydır'),

    # Hero Section
    ('Добрый день. Меня зовут Эва, как могу вам помочь?', 'Good day! I am Eva, how can I assist your business today?', 'İyi günler! Ben Eva, işletmenize nasıl yardımcı olabilirim?'),
    ('Тестовый запуск', 'Test Pilot', 'Test Pilotu'),
    ('АВТОНОМНЫЙ', 'AUTONOMOUS', 'OTONOM'),
    ('AI-ОТДЕЛ ПРОДАЖ', 'AI SALES DEPARTMENT', 'YAPAY ZEKA SATIŞ DEPARTMANI'),
    ('Пока наемный персонал теряет прибыль компании, искусственный интеллект конвертирует каждый контакт в сделку', 'While human reps lose company profits, artificial intelligence converts every lead into a closed deal', 'Mevcut personel şirket gelirini kaçırırken, yapay zeka her teması karlı bir satışa dönüştürür'),
    ('Посмотреть выгоду', 'Calculate Revenue', 'Gelir Artışını Hesapla'),
    ('100% ВНИМАНИЯ', '100% ATTENTION', 'HER MÜŞTERİYE'),
    (' К КАЖДОМУ КЛИЕНТУ', ' TO EVERY CLIENT', ' %100 ODAK VE İLGİ'),

    # Pain points
    ('СКОЛЬКО ДЕНЕГ ВЫ ТЕРЯЕТЕ,', 'HOW MUCH REVENUE DO YOU LOSE,', 'SATIŞ TEMSİLCİLERİ GECİKİRKEN,'),
    ('ПОКА МЕНЕДЖЕР ТОРМОЗИТ?', 'WHILE SALES REPS DELAY?', 'NE KADAR GELİR KAYBEDİYORSUNUZ?'),
    ('Вы оплачиваете рекламу и привлекаете лиды, но деньги сгорают на трех системных ошибках наемного персонала', 'You invest in advertising and acquire leads, but revenue burns due to three systemic human sales mistakes', 'Reklama bütçe ayırıp potansiyel müşteri çekiyorsunuz, ancak insan kaynaklı 3 kritik hata bütçenizi yakıyor'),
    ('ПОТЕРЯ ВЫРУЧКИ', 'LOST REVENUE', 'GELİR KAYBI'),
    ('СУББОТА 21:30', 'SATURDAY 21:30', 'CUMARTESİ 21:30'),
    ('СУББОТА 22:40', 'SATURDAY 22:40', 'CUMARTESİ 22:40'),
    ('Ответим в понедельник', 'We will reply on Monday', 'Pazartesi günü döneceğiz'),
    ('Клиент готов оплатить чек 300 000 ₽ вечером в выходной. Менеджер не на связи. Через 5 минут заказ уходит конкуренту, ответившему сразу.', 'A high-intent buyer is ready to pay a $5,000 invoice on a weekend evening. Rep is offline. Within 5 minutes the order is lost to a faster competitor.', 'Müşteri hafta sonu akşamı yüksek tutarlı bir ödemeye hazır. Temsilci çevrimdışı. 5 dakika içinde sipariş anında yanıt veren rakibe gider.'),
    ('СЛИВ КОНВЕРСИИ', 'CONVERSION DROP', 'DÖNÜŞÜM KAYBI'),
    ('ОЖИДАНИЕ 2 ЧАСА', '2-HOUR WAIT', '2 SAAT BEKLEME'),
    ('Кофе ценой в сделку', 'A Coffee That Costs a Deal', 'Bir Kahve Molası Bir Satışa Mal Olur'),
    ('Горячая заявка остывает, пока сотрудник раскачивается с утра. Лид теряет интерес и при звонке сухо бросает: спасибо, уже неактуально.', 'A hot inbound lead goes cold while a sales rep gets ready for the day. The buyer loses interest: "Thanks, already bought elsewhere."', 'Temsilci güne başlayana kadar sıcak talep soğur. Müşteri ilgisini kaybeder: "Teşekkürler, başka yerden aldık."'),
    ('УТЕЧКА МАРЖИ', 'MARGIN LEAK', 'MARJ KAYBI'),
    ('ПЕРЕГОВОРЫ', 'NEGOTIATIONS', 'MÜZAKERELER'),
    ('Скидка из слабости', 'Discounting Out of Weakness', 'Tavizden Doğan İndirim'),
    ('Сотрудник пугается возражения дорого и раздает скидки за счет вашей прибыли, вместо аргументации ценности и удержания полной маржи.', 'Sales reps get intimidated by price objections and discount away your net margin, instead of articulating core value.', 'Temsilci "pahalı" itirazından çekinir ve şirketin kârından taviz vererek gereksiz indirimler dağıtır.'),
    ('title="А можете получать..."', 'title="Or you could be gaining..."', 'title="Veya şunu kazanabilirsiniz..."'),
    ('А МОЖЕТЕ ПОЛУЧАТЬ...', 'OR YOU COULD BE GAINING...', 'VEYA ŞUNU KAZANABİLİRSİNİZ...'),
    ('title="Перейти к +30% к выручке"', 'title="Jump to +30% Revenue Uplift"', 'title="+%30 Net Ciro Artışına Geç"'),

    # Manifesto +30%
    ('+30% К ВЫРУЧКЕ', '+30% NET REVENUE', '+%30 NET CİRO ARTIŞI'),
    ('Оптимизируем каждый этап вашей воронки и', 'We optimize every stage of your sales funnel and', 'Satış huninizin her aşamasını optimize eder ve'),
    ('выжимаем максимум чистой прибыли из входящего потока', 'maximize high-margin revenue from your inbound traffic', 'gelen her talepten maksimum kârlılık sağlarız'),
    ('Мгновенный захват горячего клиента', 'Instant High-Intent Lead Capture', 'Sıcak Müşteriyi Anında Yakalama'),
    ('СЕКУНДЫ', 'SECONDS', 'SANİYE'),
    ('В 45 раз быстрее человека', '45x faster than humans', 'İnsandan 45 kat daha hızlı'),
    ('Ответ в первую минуту <strong class="text-sky-700 font-bold">поднимает конверсию в закрытие сделки на 40%</strong>', 'First-minute response <strong class="text-sky-700 font-bold">boosts deal closing rates by 40%</strong>', 'İlk dakika içinde verilen yanıt <strong class="text-sky-700 font-bold">satış kapatma oranını %40 artırır</strong>'),
    ('<strong class="text-emerald-700 font-bold">AI-продавец знает абсолютно всю информацию о продукте и компании</strong>, легко отрабатывает любое возражение и снимает «дорого» на основе кейсов вместо уступок за счет чистой прибыли', '<strong class="text-emerald-700 font-bold">The AI sales agent masters every detail of your product catalog</strong>, resolving objections and eliminating price resistance using proof points instead of sacrificing margin', '<strong class="text-emerald-700 font-bold">Yapay zeka ürününüzün tüm detaylarına hakimdir</strong>, her itirazı başarıyla yönetir ve kâr marjından taviz vermeden satışı kapatır'),
    ('Круглосуточная работа без выгорания и человеческого фактора. <strong class="text-amber-700 font-bold">Каждая заявка берется в обработку за секунды 24/7/365</strong>', 'Round-the-clock execution without burnout or human errors. <strong class="text-amber-700 font-bold">Every lead is engaged in seconds 24/7/365</strong>', 'Tükenmişlik ve insan hatası olmadan 7/24 çalışma. <strong class="text-amber-700 font-bold">Her talep 365 gün saniyeler içinde işleme alınır</strong>'),

    # Section 4 Bento
    ('Четкая механика сделки', 'Flawless Deal Mechanics', 'Kusursuz Satış Mekaniği'),
    ('Рутина уходит алгоритмам, чистая прибыль остается бизнесу', 'Routine shifts to algorithms, net profit stays with the business', 'Rutin görevler algoritmalara, net kâr ise işletmenize kalır'),
    ('ГОЛОСОВОЙ AI', 'NEURAL VOICE AI', 'SESLİ YAPAY ZEKA'),
    ('Живая речь эксперта', 'Natural Expert Speech', 'Doğal Uzman Konuşması'),
    ('<strong class="font-bold text-slate-950">Собеседник слышит уверенного менеджера с безупречной дикцией.</strong> AI-продавец мгновенно считывает микропаузы, <strong class="text-sky-700 font-bold">снимает возражения и ведет коммуникацию человеческим голосом и подачей</strong>.', '<strong class="font-bold text-slate-950">The buyer hears a confident executive with immaculate diction.</strong> The AI detects micro-pauses in real time, <strong class="text-sky-700 font-bold">handles objections, and negotiates with human warmth and precision</strong>.', '<strong class="font-bold text-slate-950">Müşteri diksiyonu kusursuz bir yönetici ile konuştuğunu hisseder.</strong> Yapay zeka mikro duraklamaları algılar, <strong class="text-sky-700 font-bold">itirazları giderir ve insan sıcaklığında satış yürütür</strong>.'),
    ('Естественные интонации и контекстная память', 'Natural intonations & conversational memory', 'Doğal tonlama ve bağlam hafızası'),
    ('100% фокус на продаже', '100% focus on closing', '%100 satış odaklılık'),
    ('ВСЕ МЕССЕНДЖЕРЫ', 'ALL MESSAGING CHANNELS', 'TÜM MESAJLAŞMA UYGULAMALARI'),
    ('<strong class="text-emerald-700 font-bold">Мгновенный ответ в любом удобном для клиента мессенджере</strong>', '<strong class="text-emerald-700 font-bold">Instant responses in whatever channel the buyer prefers</strong>', '<strong class="text-emerald-700 font-bold">Müşterinin tercih ettiği kanalda anında yanıt</strong>'),
    ('КАНАЛЫ СВЯЗИ 24/7/365:', 'SUPPORTED CHANNELS 24/7/365:', 'İLETİŞİM KANALLARI 7/24/365:'),
    ('Официальный API', 'Official Business API', 'Resmi API'),
    ('Личные и бот', 'Direct & Bot', 'Bireysel ve Bot'),
    ('Avito Чат', 'Marketplaces', 'Portal & Web Chat'),
    ('Авто-ответ 24/7', 'Instant Auto-reply 24/7', '7/24 Otomatik Yanıt'),
    ('РЕАКТИВАЦИЯ АРХИВА', 'DATABASE REACTIVATION', 'VERİTABANI CANLANDIRMA'),
    ('Второе дыхание старой базы', 'New Life for Dormant Leads', 'Eski Müşterilere İkinci Nefes'),
    ('<strong class="text-purple-700 font-bold">Уснувшие контакты возвращаются в диалог</strong> через деликатные персонализированные офферы. AI не спамит, а решает актуальную задачу клиента.', '<strong class="text-purple-700 font-bold">Dormant contacts return to conversation</strong> via delicate personalized offers. The AI provides genuine value, not spam.', '<strong class="text-purple-700 font-bold">Uyuyan kontaklar sohbete geri döner</strong>; kişiye özel zarif tekliflerle. AI spam yapmaz, müşterinin ihtiyacını çözer.'),
    ('Уснувшая база', 'Dormant Database', 'Uyuyan Veritabanı'),
    ('Успешная оплата', 'Closed Revenue', 'Tahsil Edilen Gelir'),
    ('800 контактов', '800 contacts', '800 kişi'),
    ('268 закрыто', '268 closed', '268 kazanıldı'),
    ('АВТОНОМНАЯ CRM', 'AUTONOMOUS CRM', 'OTONOM CRM'),
    ('Система протоколирует договоренности, выставляет счета и <strong class="text-sky-700 font-bold">автоматически переводит сделку на этап «Оплачено»</strong> после банковского подтверждения.', 'The system logs agreements, generates invoices, and <strong class="text-sky-700 font-bold">automatically advances deals to Closed Won</strong> upon payment clearance.', 'Sistem anlaşmaları belgeler, fatura iletir ve banka onayından sonra <strong class="text-sky-700 font-bold">satışı otomatik Kazanıldı aşamasına alır</strong>.'),
    ('Этап 1', 'Stage 1', 'Aşama 1'),
    ('Скоринг', 'Scoring', 'Skorlama'),
    ('Этап 2', 'Stage 2', 'Aşama 2'),
    ('Расчет КП', 'Quoting', 'Teklif'),
    ('Финал', 'Final', 'Sonuç'),
    ('Оплачено ✓', 'Paid ✓', 'Ödendi ✓'),
    ('amoCRM API v4', 'amoCRM API v4', 'amoCRM API v4'),
    ('Битрикс24 REST', 'Bitrix24 REST', 'Bitrix24 REST'),
    ('Сквозная синхронизация', 'End-to-End CRM Sync', 'Uçtan Uca Senkronizasyon'),
    ('Психология коммуникации', 'Real-Time Conversational', 'Gerçek Zamanlı İletişim'),
    ('в реальном времени', 'Intelligence & Psychology', 'Psikolojisi ve Yapay Zeka'),
    ('Автономная генерация ответов 0.8с', 'Autonomous 0.8s Response Generation', '0.8 Saniyede Otonom Yanıt Üretimi'),
    ('<strong class="text-sky-800 font-bold">Диалог ведется на основе регламентов вашего бизнеса</strong>, без пауз, раздражения и глупых опечаток нанятых стажеров.', '<strong class="text-sky-800 font-bold">Dialogues follow your exact enterprise sales playbooks</strong>, free of delays, emotional fatigue, or rookie spelling errors.', '<strong class="text-sky-800 font-bold">Diyalog işletmenizin kurallarına göre yürütülür</strong>; duraklama, yorgunluk ve insan kaynaklı hatalar olmaz.'),
    ('Знакомство и закрытие на внедрение', 'Discovery & Closing on Pilot Deployment', 'Tanışma ve Pilot Satış Kapatma'),
    ('Отработка «Почему это стоит денег»', 'Handling "Why Is This Worth The Investment"', '"Neden Bu Yatırıma Değer" İtirazı'),
    ('Мгновенная продажа товара в Direct', 'Instant Product Closing in Instagram Direct', 'Instagram Direct\'te Anında Satış'),
    ('в сети • отклик 0.8с', 'online • 0.8s response', 'çevrimiçi • 0.8s yanıt'),
    ('Ожидание реакции клиента...', 'Awaiting client response...', 'Müşteri yanıtı bekleniyor...'),

    # Section 5 amoCRM
    ('Пока менеджеры ленятся заполнять CRM', 'While sales reps neglect CRM data entry', 'Temsilciler CRM doldurmayı ihmal ederken'),
    ('AI-сотрудник автоматически', 'AI Agent automatically logs', 'AI Temsilcisi diyaloglardaki'),
    ('вносит 100% данных из диалогов', '100% of dialogue data and', 'tüm verileri otomatik işler ve'),
    ('и двигает сделку по воронке', 'drives the deal forward', 'satışı hunide hızla ilerletir'),
    ('Фрэнк Каупервуд', 'Frank Cowperwood', 'Frank Cowperwood'),
    ('Фрэнк Кауперруд', 'Frank Cowperwood', 'Frank Cowperwood'),
    ('Исраэль Иуда', 'Frank Cowperwood', 'Frank Cowperwood'),
    ('#ТЕГИРОВАТЬ', '#TAGGING', '#ETİKETLE'),
    ('Основное', 'General', 'Genel'),
    ('Сделки', 'Deals', 'Fırsatlar'),
    ('Настроить', 'Settings', 'Ayarlar'),
    ('Отв-ный', 'Assignee', 'Sorumlu'),
    ('Егоров Ренат (AI Altai)', 'Renat Egorov (AI Altai)', 'Renat Egorov (AI Altai)'),
    ('Раб. тел.', 'Work Phone', 'İş Tel'),
    ('валиден ✓', 'verified ✓', 'doğrulandı ✓'),
    ('Email раб.', 'Work Email', 'İş E-posta'),
    ('Должность', 'Position', 'Pozisyon'),
    ('Пользовательское с...', 'Custom status...', 'Özel durum...'),
    ('title="Активно"', 'title="Active"', 'title="Aktif"'),
    ('КОМПАНИЯ', 'COMPANY', 'ŞİRKET'),
    ('Тестовая компания', 'Test Company Inc.', 'Test Şirketi A.Ş.'),
    ('Бюджет лида', 'Deal Budget', 'Fırsat Bütçesi'),
    ('Сфера / Web', 'Industry', 'Sektör / Web'),
    ('Адрес', 'Address', 'Adres'),
    ('Статус в CRM', 'CRM Status', 'CRM Durumu'),
    ('Анализ переписки...', 'Analyzing dialogue...', 'Diyalog analiz ediliyor...'),
    ('Автозаполнение всех полей в CRM', 'Autofill 100% fields in CRM', 'CRM\'de %100 otomatik alan doldurma'),
    ('СИНХРОНИЗИРОВАНО', 'SYNCHRONIZED', 'SENKRONİZE EDİLDİ'),
    ('ДВИЖЕНИЕ СДЕЛКИ В AMOCRM', 'PIPELINE FLOW IN CRM', 'CRM\'DE SATIŞ HUNİSİ AKIŞI'),
    ('Этапы воронки без зависаний', 'Seamless Funnel Velocity', 'Kesintisiz Huni İlerlemesi'),
    ('Заполнение без ошибок', 'Zero Data Entry Errors', 'Sıfır Hata ile Veri Girişi'),
    ('НОВЫЙ ЛИД', 'NEW LEAD', 'YENİ TALEP'),
    ('409 сделок', '409 deals', '409 fırsat'),
    ('КОНТАКТ', 'CONTACT', 'İLETİŞİM'),
    ('732 сделки', '732 deals', '732 fırsat'),
    ('КВАЛИФИКАЦИЯ', 'QUALIFICATION', 'UYGUNLUK'),
    ('235 сделок', '235 deals', '235 fırsat'),
    ('КП ОТПРАВЛЕНО', 'PROPOSAL SENT', 'TEKLİF GÖNDERİLDİ'),
    ('1 389 сделок', '1,389 deals', '1.389 fırsat'),
    ('УСПЕШНО', 'CLOSED WON', 'KAZANILDI'),
    ('100% ОПЛАТА', '100% PAID', '%100 ÖDENDİ'),
    ('1. Новый лид (Мгновенный захват 0.8с)', '1. New Lead (Instant 0.8s Capture)', '1. Yeni Talep (0.8s Anında Yakalama)'),
    ('✓ Захват', '✓ Capture', '✓ Yakalama'),
    ('Лид из WhatsApp, Telegram, сайта или JivoSite моментально регистрируется в CRM', 'Lead from WhatsApp, Telegram, web or Jivo is instantly logged into CRM', 'WhatsApp, Telegram, web veya Jivo\'dan gelen talep anında CRM\'e işlenir'),
    ('Лид из WhatsApp, Telegram, сайта или JivoSite моментально регистрируется в CRM.', 'Lead from WhatsApp, Telegram, web or Jivo is instantly logged into CRM.', 'WhatsApp, Telegram, web veya Jivo\'dan gelen talep anında CRM\'e işlenir.'),
    ('Лид из WhatsApp, Telegram, сайта или рекламы мгновенно попадает в CRM без потерь.', 'Lead from WhatsApp, Telegram, web or ads is instantly logged into CRM with zero loss.', 'WhatsApp, Telegram, web veya reklamdan gelen talep anında CRM\'e işlenir.'),
    ('2. Контакт установлен (Живой диалог)', '2. Contact Made (Live Dialogue)', '2. İletişim Kuruldu (Canlı Diyalog)'),
    ('Диалог 24/7', 'Dialogue 24/7', '7/24 Diyalog'),
    ('AI выходит на связь за секунды, задает уточняющие вопросы и удерживает внимание лида', 'AI responds in seconds, asks clarifying questions, and holds the lead\'s attention', 'Yapay zeka saniyeler içinde iletişime geçer, sorular sorar ve ilgiyi canlı tutar'),
    ('AI выходит на связь за секунды, задает уточняющие вопросы и удерживает внимание лида.', 'AI responds in seconds, asks clarifying questions, and holds the lead\'s attention.', 'Yapay zeka saniyeler içinde iletişime geçer, sorular sorar ve ilgiyi canlı tutar.'),
    ('3. Квалифицирован (ЛПР, бюджет, объем)', '3. Qualified (Decision Maker, Budget, Scope)', '3. Uygunluk Belirlendi (Yetkili, Bütçe, Hacim)'),
    ('100% полей в CRM', '100% CRM Fields', 'CRM\'de %100 Alan'),
    ('ИИ фиксирует должность, компанию, объем закупки и бюджет — вносит данные прямо в карточку', 'AI extracts title, company, purchase volume, and budget directly into the card', 'Yapay zeka yetkili unvanını, şirketi ve bütçeyi doğrudan CRM kartına işler'),
    ('ИИ фиксирует должность, компанию, объем закупки и бюджет — вносит 100% данных в карточку.', 'AI extracts title, company, purchase volume, and budget directly into the card.', 'Yapay zeka yetkili unvanını, şirketi ve bütçeyi doğrudan CRM kartına işler.'),
    ('ИИ фиксирует должность, компанию, объем закупки и платежеспособность в карточке CRM.', 'AI extracts title, company, purchase volume, and budget directly into the card.', 'Yapay zeka yetkili unvanını, şirketi ve bütçeyi doğrudan CRM kartına işler.'),
    ('4. КП отправлено (Согласование и дожим)', '4. Proposal Sent (Review & Closing)', '4. Teklif Gönderildi (Müzakere ve Takip)'),
    ('Прайс защищен', 'Margin Defended', 'Fiyat Korundu'),
    ('Автоматический расчет спецификации и сметы по прайсу без скидок из страха потери лида', 'Automated price book calculation and proposal dispatch without unnecessary discounts', 'Fiyat listesinden otomatik hesaplama ve gereksiz indirim vermeden teklif iletimi'),
    ('Автоматический расчет спецификации из прайса, отправка PDF-счета и дожим без уступок.', 'Automated price book calculation, instant PDF invoice, and value-based closing.', 'Fiyat listesinden otomatik hesaplama, PDF fatura gönderimi ve tavizsiz satış kapatma.'),
    ('5. Успешно реализовано (Оплата)', '5. Closed Won (Payment Received)', '5. Başarıyla Tamamlandı (Ödeme Alındı)'),
    ('ДЕНЬГИ НА СЧЕТУ', 'FUNDS CLEARED', 'ÖDEME ALINDI'),
    ('Чек пробит, транзакция зафиксирована, сделка переведена в финальный этап amoCRM', 'Receipt cleared, transaction recorded, and deal moved to Closed Won', 'Fatura tahsil edildi, işlem kaydedildi ve fırsat amoCRM\'de kazanıldı aşamasına alındı'),
    ('Чек пробит, транзакция зафиксирована, сделка переведена в статус «Оплачено».', 'Receipt cleared, transaction recorded, and deal moved to Closed Won.', 'Ödeme onaylandı, işlem muhasebeye işlendi ve durum "Ödendi" olarak güncellendi.'),
    ('Чек пробит, транзакция зафиксирована в 1С/банке, сделка переведена в статус «Оплачено».', 'Receipt cleared, transaction recorded in bank/ERP, and deal moved to Closed Won.', 'Ödeme onaylandı, işlem muhasebeye işlendi ve durum "Ödendi" olarak güncellendi.'),

    # Section 6 Cases
    ('// РЕАЛЬНЫЕ КЕЙСЫ', '// REAL CASE STUDIES', '// GERÇEK BAŞARI HİKAYELERİ'),
    ('Разборы внедрения', 'Implementation Breakdowns', 'Otonom Satış Departmanı'),
    ('автономного отдела продаж', 'of Autonomous AI Sales', 'Uygulama İncelemeleri'),
    ('ВЫБЕРИТЕ СФЕРУ ДЛЯ ИЗУЧЕНИЯ:', 'SELECT AN INDUSTRY TO EXPLORE:', 'İNCELEMEK İÇİN BİR SEKTÖR SEÇİN:'),
    ('4 ГОТОВЫХ СЦЕНАРИЯ', '4 READY-TO-USE SCENARIOS', '4 HAZIR SENARYO'),
    ('B2B Опт & Поставки', 'B2B Wholesale & Supply', 'B2B Toptan & Tedarik'),
    ('Металл, комплектующие', 'Industrial, Equipment', 'Endüstriyel, Ekipman'),
    ('Недвижимость & КП', 'Real Estate & Luxury', 'Gayrimenkul & Lüks'),
    ('Девелопмент, ЖК', 'Developments, Land', 'Projeler, Arsa'),
    ('Автобизнес & Лизинг', 'Automotive & Fleet', 'Otomotiv & Filo'),
    ('Avito, спецтехника', 'Commercial, Trucks', 'Ticari, İş Makineleri'),
    ('B2B Консалтинг', 'B2B Consulting & Legal', 'B2B Danışmanlık & Hukuk'),
    ('Аудит, сложные услуги', 'Tax, Corporate Advisory', 'Vergi, Kurumsal Denetim'),
    ('ДЕМОНСТРАЦИЯ СЦЕНАРИЯ', 'SCENARIO DEMO', 'SENARYO DEMOSU'),
    ('Шаг 1: Захват & Расчет', 'Step 1: Capture & Quote', 'Adım 1: Yakalama & Teklif'),
    ('Шаг 2: Дожим в Telegram', 'Step 2: Push in Telegram', 'Adım 2: Telegram\'da Takip'),
    ('Шаг 3: Сделка в CRM', 'Step 3: CRM Deal Flow', 'Adım 3: CRM Satış Akışı'),
    ('Было:', 'Before:', 'Önce:'),
    ('Стало с AI:', 'With AI:', 'AI ile Sonra:'),
    ('Рассчитайте выгоду под вашу нишу:', 'Calculate revenue for your industry:', 'Sektörünüze özel getiriyi hesaplayın:'),
    ('Открыть калькулятор', 'Open Calculator', 'Hesaplayıcıyı Aç'),

    # Section 7 Calculator
    ('// КАЛЬКУЛЯТОР ВЫГОДЫ', '// REVENUE CALCULATOR', '// GELİR ARTIŞI HESAPLAYICI'),
    ('СКОЛЬКО ЧИСТОЙ ПРИБЫЛИ', 'HOW MUCH NET REVENUE', 'İŞLETMENİZ ŞU ANDA'),
    ('ТЕРЯЕТ ВАШ БИЗНЕС ПРЯМО СЕЙЧАС?', 'DOES YOUR BUSINESS LOSE RIGHT NOW?', 'NE KADAR NET KÂR KAYBEDİYOR?'),
    ('Двигайте ползунки под параметры вашей компании и посмотрите реальную прибавку к выручке', 'Adjust the sliders to your company metrics and see your exact revenue uplift', 'Kaydırıcıları şirketinizin metriklerine göre ayarlayın ve cironuzdaki net artışı görün'),
    ('Количество входящих заявок (лидов) в месяц:', 'Inbound leads per month:', 'Aylık gelen potansiyel müşteri (talep) sayısı:'),
    ('Средний чек сделки (₽):', 'Average deal size ($):', 'Ortalama satış tutarı ($):'),
    ('Текущая конверсия отдела продаж (%):', 'Current sales team conversion (%):', 'Mevcut satış ekibi dönüşüm oranı (%):'),
    ('ИТОГОВЫЙ ПРИРОСТ С ВНЕДРЕНИЕМ ALTAI OPTIMA', 'TOTAL REVENUE GAIN WITH ALTAI OPTIMA', 'ALTAI OPTIMA İLE TOPLAM NET KAZANÇ'),
    ('ДОПОЛНИТЕЛЬНО В МЕСЯЦ', 'ADDITIONAL REVENUE / MO', 'AYLIK EK CİRO'),
    ('ПРИРОСТ ПРИБЫЛИ ЗА ГОД', 'ANNUAL PROFIT UPLIFT', 'YILLIK EK KÂR'),
    ('ТУРБО-РОСТ', 'TURBO ROI', 'TURBO BÜYÜME'),
    ('Окупаемость системы от 3 до 14 дней с момента запуска', 'System payback in 3 to 14 days from launch', 'Sistemin kendini amorti etme süresi lansmandan itibaren 3 ila 14 gündür'),
    ('Забрать эту прибыль', 'Capture This Revenue', 'Bu Geliri Hemen Yakala'),

    # Section 8 Resume
    ('// ИНТЕРАКТИВНОЕ РЕЗЮМЕ', '// INTERACTIVE CANDIDATE PROFILE', '// İNTERAKTİF ADAY PROFİLİ'),
    ('РЕЗЮМЕ ВАШЕГО ИДЕАЛЬНОГО', 'RESUME OF YOUR PERFECT', 'İDEAL YAPAY ZEKA SATIŞ'),
    ('AI-СОТРУДНИКА', 'AI SALES EXECUTIVE', 'TEMSİLCİNİZİN ÖZGEÇMİŞİ'),
    ('Выберите сотрудника под ценности и специфику вашей аудитории', 'Select a candidate matching your brand voice and market segment', 'Marka değerlerinize ve hedef kitlenize en uygun AI çalışanını seçin'),
    ('Интерактивный выбор', 'Interactive Selection', 'İnteraktif Seçim'),
    ('35 лет', '35 yo', '35 yaş'),
    ('38 лет', '38 yo', '38 yaş'),
    ('29 лет', '29 yo', '29 yaş'),
    ('42 года', '42 yo', '42 yaş'),
    ('31 год', '31 yo', '31 yaş'),
    ('45 лет', '45 yo', '45 yaş'),
    ('27 лет', '27 yo', '27 yaş'),
    ('30 лет', '30 yo', '30 yaş'),
    ('34 года', '34 yo', '34 yaş'),
    ('46 лет', '46 yo', '46 yaş'),
    ('Эва', 'Eva', 'Eva'),
    ('Алекс', 'Aleks', 'Aleks'),
    ('Дарья', 'Daria', 'Daria'),
    ('Руслан', 'Ruslan', 'Ruslan'),
    ('Мэй', 'Mei', 'Mei'),
    ('Марк', 'Mark', 'Mark'),
    ('Амина', 'Amina', 'Amina'),
    ('Денис', 'Denis', 'Denis'),
    ('Кенджи', 'Kenji', 'Kenji'),
    ('Елена', 'Elena', 'Elena'),
    ('ЭВА', 'EVA', 'EVA'),
    ('СТАРШИЙ ВИЦЕ-ПРЕЗИДЕНТ ПО ПРОДАЖАМ', 'SENIOR VP OF SALES', 'KIDEMLİ SATIŞ BAŞKAN YARDIMCISI'),
    ('Вся Россия, CRM', 'Global, Any CRM', 'Küresel, Tüm CRM Sistemleri'),
    ('Возраст:', 'Age:', 'Yaş:'),
    ('Готова к работе', 'Ready for Deployment', 'Göreve Hazır'),
    ('Готов к работе', 'Ready for Deployment', 'Göreve Hazır'),
    ('alt="Эва — Старший вице-президент по продажам"', 'alt="Eva — Senior VP of Sales"', 'alt="Eva — Kıdemli Satış Başkan Yardımcısı"'),
    ('Ключевые компетенции', 'Core Competencies', 'Temel Yetkinlikler'),
    ('Навыки коммуникации уровня Ritz-Carlton:', 'Ritz-Carlton Level Communication:', 'Ritz-Carlton Düzeyinde İletişim:'),
    ('безупречный тон, уважение границ и персональный сервис высшего класса.', 'flawless vocal etiquette, active listening, and high-touch VIP relationship building.', 'kusursuz nezaket, etkin dinleme ve üst düzey müşteri ilişkileri yönetimi.'),
    ('Отработка любых возражений:', 'Objection Handling & Closing:', 'İtiraz Yönetimi ve Satış Kapatma:'),
    ('аргументация ценности и твердая защита чека без раздачи скидок.', 'value-based positioning and strict margin defense without unwarranted discounts.', 'değer odaklı konumlandırma ve indirimsiz fiyat marjı koruması.'),
    ('Автономная работа в CRM:', 'Autonomous CRM Execution:', 'CRM\'de Otonom Çalışma:'),
    ('самостоятельное ведение лида по воронке до оплаты.', 'end-to-end pipeline management from lead capture to invoice clearing.', 'talep yakalamadan fatura tahsilatına kadar otonom satış süreci.'),
    ('Мгновенная реакция на обращения:', 'Instant Response Time:', 'Anında Yanıt Süresi:'),
    ('отклик за 0.8 секунды в любых каналах связи.', '0.8-second first response time across all messaging and voice channels.', 'tüm mesajlaşma ve ses kanallarında 0.8 saniyede ilk yanıt hızı.'),
    ('Значение русского языка уровня Даля:', 'Multilingual Fluency:', 'Çok Dilli Akıcı İletişim:'),
    ('Знание русского языка уровня Даля:', 'Multilingual Fluency:', 'Çok Dilli Akıcı İletişim:'),
    ('живая, убедительная речь без скриптовой сухости.', 'natural, expressive dialogue without robotic script stiffness.', 'robotik metin kuruluğu olmadan doğal ve ikna edici diyalog.'),
    ('Условия и график', 'Terms & Availability', 'Çalışma Şartları & Uygunluk'),
    ('Режим работы:', 'Work Schedule:', 'Çalışma Modeli:'),
    ('Результат:', 'Outcome:', 'Net Sonuç:'),
    ('+30% к прибыли', '+30% to Net Profit', '+%30 Net Kâr Artışı'),
    ('Зарплата:', 'Compensation:', 'Maaş Beklentisi:'),
    ('от 100 000 ₽', 'from $1,200', '$1.200\'dan başlayan'),
    ('Языки', 'Languages', 'Diller'),
    ('Владение:', 'Proficiency:', 'Yetkinlik:'),
    ('7 170 языков', '7,170 languages', '7.170 dil'),
    ('Уровень:', 'Level:', 'Seviye:'),
    ('Родной / C2', 'Native / C2', 'Ana Dil / C2'),
    ('О себе', 'Executive Summary', 'Yönetici Özeti'),
    ('Обучена строгим стандартам персонального сервиса на базе Ritz-Carlton. <strong class="text-slate-950 font-semibold">Я готова уже здесь и сейчас зарабатывать деньги для вашей компании:</strong> веду диалог безупречным голосом, строго защищаю базовый прайс и довожу сделку до оплаты с достоинством профессионала — без отпусков, выгорания и человеческого фактора.', 'Trained to the rigorous standards of premier customer relationship management. <strong class="text-slate-950 font-semibold">I am ready right now to accelerate revenue for your company:</strong> conducting high-converting dialogues, strictly defending your price margins, and closing deals with total professionalism — zero downtime, zero burnout, zero human error.', 'Seçkin müşteri ilişkileri standartlarında eğitildim. <strong class="text-slate-950 font-semibold">Şirketinizin gelirini hemen şimdi artırmaya hazırım:</strong> yüksek dönüşümlü diyaloglar yürütür, fiyat marjlarınızı tavizsiz korur ve anlaşmaları profesyonellikle kapatırım — izin yok, tükenmişlik yok, insan hatası yok.'),
    ('ПОДАРОК ПРИ ПОДКЛЮЧЕНИИ', 'BONUS GIFT WITH DEPLOYMENT', 'ENTEGRASYONDA ÖZEL HEDİYE'),
    ('Давайте создадим для вас кастомного <strong class="text-transparent bg-clip-text bg-gradient-to-r from-sky-600 to-blue-700 font-extrabold font-inter">AI-менеджера под ваш продукт</strong>, интегрируем в CRM и мессенджеры и проведем тестовый запуск на живом потоке клиентов, чтобы вы увидели рост конверсии в первый же день.', 'Let us deploy a custom <strong class="text-transparent bg-clip-text bg-gradient-to-r from-sky-600 to-blue-700 font-extrabold font-inter">AI sales executive tailored to your product</strong>, integrated directly with your CRM and messaging channels for an instant revenue uplift on day one.', 'Ürününüz için özel <strong class="text-transparent bg-clip-text bg-gradient-to-r from-sky-600 to-blue-700 font-extrabold font-inter">yapay zeka satış yöneticisi</strong> geliştirelim, CRM ve mesajlaşma kanallarınıza bağlayıp ilk günden ciro artışını birlikte başlatalım.'),
    ('Перенос базы из Excel в CRM в подарок', 'Complimentary database migration from Excel to CRM', 'Excel\'den CRM\'e ücretsiz veritabanı aktarımı'),
    ('выгода 45 000 ₽', 'worth $500', 'değer: $500'),
    ('Подарок при подключении • выгода 45 000 ₽', 'Complimentary Gift • Worth $500', 'Entegrasyonda Özel Hediye • Değer: $500'),
    ('Подписание NDA перед началом любых работ', 'Comprehensive NDA signed prior to commencing any work', 'Çalışmaya başlamadan önce kapsamlı Gizlilik Sözleşmesi (NDA)'),
    ('ваши данные в безопасности', 'your data is 100% confidential and secure', 'verileriniz %100 gizli ve güvende'),
    ('placeholder="Александр"', 'placeholder="Alex"', 'placeholder="Ahmet"'),
    ('placeholder="+7 (999) 000-00-00 или @username"', 'placeholder="+1 (555) 000-0000 or @username"', 'placeholder="+90 (555) 000-0000 veya @kullaniciadi"'),
    ('ОБСУДИТЬ ДЕТАЛИ ПРОЕКТА', 'DISCUSS PROJECT DETAILS', 'PROJE DETAYLARINI GÖRÜŞÜN'),
    ('✓ Заявка принята! Свяжемся с вами в течение 10 минут.', '✓ Request received! We will contact you within 10 minutes.', '✓ Başvurunuz alındı! 10 dakika içinde sizinle iletişime geçeceğiz.'),

    # Section 9 Quote & Banner
    ('«Мысли глобально, действуй локально»', '"Think globally, act locally"', '«Küresel düşün, yerel hareket et»'),
    ('— Команда Altai', '— Altai Team', '— Altai Ekibi'),
    ('МЫСЛИ ГЛОБАЛЬНО, ДЕЙСТВУЙ ЛОКАЛЬНО', 'THINK GLOBALLY, ACT LOCALLY', 'KÜRESEL DÜŞÜN, YEREL HAREKET ET'),
    ('Время убрать человеческий фактор из отдела продаж и забрать упущенную прибыль', 'Time to remove human sales bottlenecks and capture lost profit', 'Satış ekibindeki insan kaynaklı hataları sonlandırma ve kaçan geliri geri kazanma zamanı'),
    ('Запустите тестовый пилот на 50 реальных лидах бесплатно', 'Launch a free test pilot on 50 real inbound leads', '50 gerçek potansiyel müşteri üzerinde ücretsiz deneme pilotu başlatın'),
    ('Развернем AI-продавца под ваш продукт за 24 часа. Без оплаты, без изменения штата, без риска.', 'We deploy your custom AI sales agent in 24h. No upfront fee, zero risk.', 'Ürününüz için özel AI satış temsilcisini 24 saatte kuralım. Ön ödeme yok, kadro değişikliği yok, sıfır risk.'),
    ('Бесплатный пилот на 50 лидах', 'Free 50-lead live pilot', '50 talepte ücretsiz pilot'),
    ('Готовая интеграция за 24 часа', 'Ready integration in 24h', '24 saatte hazır entegrasyon'),
    ('Договор с гарантией ROI', 'Contract with ROI guarantee', 'ROI garantili sözleşme'),
    ('Ваше имя', 'Your Name', 'Adınız Soyadınız'),
    ('Телефон или Telegram *', 'Phone or Telegram *', 'Telefon veya Telegram *'),
    ('Сайт компании или ниша', 'Company website or industry', 'Şirket web sitesi veya sektör'),
    ('Запустить бесплатный пилот', 'Launch Free Live Pilot', 'Ücretsiz Pilotu Başlat'),
    ('✓ Заявка принята! Мы свяжемся с вами в течение 15 минут для согласования пилота.', '✓ Request received! We will contact you within 15 minutes to configure your pilot.', '✓ Başvurunuz alındı! Pilot yapılandırması için 15 dakika içinde sizinle iletişime geçeceğiz.'),
    ('🔒 Ваши данные защищены. Мы не передаем контакты третьим лицам.', '🔒 Your data is secure. We never share contacts with third parties.', '🔒 Verileriniz tamamen güvendedir. Bilgileriniz asla 3. taraflarla paylaşılmaz.'),
    ('🎁 ПОДАРОК ПРИ ПОДКЛЮЧЕНИИ AI-ПРОДАВЦА', '🎁 BONUS GIFT WITH AI INTEGRATION', '🎁 AI ENTEGRASYONUNDA ÖZEL HEDİYE'),
    ('ВЫГОДА 45 000 ₽', 'VALUE $500', 'DEĞER: $500'),
    ('Вся база в Excel или Google Таблицах? Наведем четкий порядок', 'All your customer data in Excel or Sheets? We organize everything', 'Müşteri verileriniz Excel veya Google E-Tablolarda mı? Hepsini kusursuz düzenleyelim'),
    ('Если у вас еще нет CRM — не проблема. Мы возьмем на себя всю рутину: перенесем ваши разрозненные таблицы, почистим от дублей, сегментируем контакты и подготовим базу для старта AI-продаж.', 'No CRM yet? No problem. We handle full database migration: duplicate cleanup, segmentation, and setup for AI sales.', 'Henüz bir CRM sisteminiz yoksa sorun değil. Tüm geçiş sürecini üstleniyoruz: tablolarınızı aktarır, kopyaları temizler, kişileri segmentlere ayırır ve AI satışlarına hazırlarız.'),
    ('Очистка от дублей', 'Duplicate cleanup', 'Kopya kayıt temizliği'),
    ('Импорт в CRM', 'Direct CRM import', 'Doğrudan CRM aktarımı'),
    ('AI-сегментация', 'AI segmentation', 'AI segmentasyonu'),
    ('Забрать подарок и перенести базу', 'Claim Gift & Migrate Database', 'Hediyeyi Al ve Veritabanını Aktar'),
    ('✓ Заявка принята! Мы свяжемся с вами в течение 15 минут для согласования переноса базы.', '✓ Request received! We will contact you within 15 minutes.', '✓ Başvurunuz alındı! 15 dakika içinde iletişime geçeceğiz.'),
    ('🔒 Конфиденциально • Подписываем NDA перед началом работ', '🔒 Confidential • We sign NDA prior to starting work', '🔒 Gizlilik Garantisi • Çalışmaya başlamadan önce NDA imzalıyoruz'),
    ('Начать работу', 'Get Started', 'Hemen Başlayın'),

    # Avatar tooltips & alt
    ('title="Эва // Эксперт по сложным B2B продажам"', 'title="Eva // Complex B2B Sales Executive"', 'title="Eva // Karmaşık B2B Satış Uzmanı"'),
    ('title="Александр // Уверенный мужской баритон"', 'title="Aleksander // Confident Baritone"', 'title="Aleksander // Güven Veren Bariton"'),
    ('title="Дарья // Премиальный сервис и забота"', 'title="Daria // Premium VIP Service"', 'title="Daria // Premium VIP Hizmet"'),
    ('title="Руслан // Твердые переговоры и опт"', 'title="Ruslan // Hard Negotiations & Wholesale"', 'title="Ruslan // Zorlu Müzakereler & Toptan"'),
    ('title="Мэй // Международные сделки и Tech"', 'title="Mei // Cross-border Deals & Tech"', 'title="Mei // Küresel Ticaret & Tech"'),
    ('title="Марк // Корпоративные сделки"', 'title="Mark // Enterprise Deals"', 'title="Mark // Kurumsal Anlaşmalar"'),
    ('title="Амина // Деликатный премиум-дожим"', 'title="Amina // Delicate Luxury Closing"', 'title="Amina // Lüks Gayrimenkul Kapatıcısı"'),
    ('title="Денис // Скоростной захват лидов"', 'title="Denis // High-Speed Lead Capture"', 'title="Denis // Yüksek Hızlı Talep Yakalama"'),
    ('title="Кенджи // Инженерный расчет и B2B"', 'title="Kenji // Engineering & B2B Calculation"', 'title="Kenji // Mühendislik ve B2B Hesaplama"'),
    ('title="Елена // Высокие чеки и доверие"', 'title="Elena // High-Ticket & Trust"', 'title="Elena // Yüksek Tutarlı Anlaşmalar"'),
    ('alt="Эва"', 'alt="Eva"', 'alt="Eva"'),
    ('alt="Александр"', 'alt="Aleksander"', 'alt="Aleksander"'),
    ('alt="Дарья"', 'alt="Daria"', 'alt="Daria"'),
    ('alt="Руслан"', 'alt="Ruslan"', 'alt="Ruslan"'),
    ('alt="Мэй"', 'alt="Mei"', 'alt="Mei"'),
    ('alt="Марк"', 'alt="Mark"', 'alt="Mark"'),
    ('alt="Амина"', 'alt="Amina"', 'alt="Amina"'),
    ('alt="Денис"', 'alt="Denis"', 'alt="Denis"'),
    ('alt="Кенджи"', 'alt="Kenji"', 'alt="Kenji"'),
    ('alt="Елена"', 'alt="Elena"', 'alt="Elena"'),

    # Audio player / status text
    ("status.textContent = 'Воспроизведение...';", "status.textContent = 'Playing...';", "status.textContent = 'Oynatılıyor...';"),
    ("status.textContent = 'Слушать';", "status.textContent = 'Listen';", "status.textContent = 'Dinle';"),

    # Personas JS Data
    ("name: 'ЭВА',", "name: 'EVA',", "name: 'EVA',"),
    ("role: 'СТАРШИЙ ВИЦЕ-ПРЕЗИДЕНТ ПО ПРОДАЖАМ',", "role: 'SENIOR VP OF SALES',", "role: 'KIDEMLİ SATIŞ BAŞKAN YARDIMCISI',"),
    ("badge: 'ПЕРСОНА: ЭВА',", "badge: 'PERSONA: EVA',", "badge: 'PERSONA: EVA',"),
    ("title: 'Эва // AI Altai Optima',", "title: 'Eva // AI Altai Optima',", "title: 'Eva // AI Altai Optima',"),
    ("desc: 'Безупречный женский альт, строгий деловой этикет Ritz-Carlton. Идеально закрывает чеки от 500 000 ₽.',", "desc: 'Flawless vocal timbre, strict Ritz-Carlton business etiquette. Closes $10k+ enterprise deals.',", "desc: 'Kusursuz kadın ses tonu, Ritz-Carlton standartlarında iş etiği. Yüksek tutarlı kurumsal anlaşmaları başarıyla kapatır.',"),
    ("name: 'АЛЕКСАНДР СЕМЕНОВ',", "name: 'ALEKSANDER SEMENOV',", "name: 'ALEKSANDER SEMENOV',"),
    ("role: 'ДИРЕКТОР ПО B2B ПРОДАЖАМ И ОПТУ',", "role: 'B2B & WHOLESALE DIRECTOR',", "role: 'B2B & TOPTAN SATIŞ DİREKTÖRÜ',"),
    ("badge: 'ПЕРСОНА: АЛЕКСАНДР',", "badge: 'PERSONA: ALEKSANDER',", "badge: 'PERSONA: ALEKSANDER',"),
    ("title: 'Александр // Уверенный баритон',", "title: 'Aleksander // Confident Baritone',", "title: 'Aleksander // Güven Veren Bariton',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (БАРИТОН)',", "voiceBadge: 'VOICE: SYNTHESIS HD (BARITONE)',", "voiceBadge: 'SES: HD SENTEZ (BARİTON)',"),
    ("desc: 'Глубокий спокойный мужской баритон. Идеален для оптовой торговли, поставок оборудования, девелопмента и логистики.',", "desc: 'Deep confident baritone. Exceptional in wholesale, industrial equipment, construction, and supply chain.',", "desc: 'Derin ve sakin erkek bariton sesi. Toptan ticaret, makine tedariki, inşaat ve lojistik için idealdir.',"),
    ("name: 'ДАРЬЯ РОМАНОВА',", "name: 'DARIA ROMANOVA',", "name: 'DARIA ROMANOVA',"),
    ("role: 'РУКОВОДИТЕЛЬ VIP-КОНСЬЕРЖ СЕРВИСА',", "role: 'VIP CONCIERGE & HOSPITALITY HEAD',", "role: 'VIP KONSİYERJ HİZMETLERİ MÜDÜRÜ',"),
    ("badge: 'ПЕРСОНА: ДАРЬЯ',", "badge: 'PERSONA: DARIA',", "badge: 'PERSONA: DARIA',"),
    ("title: 'Дарья // Премиальный сервис и забота',", "title: 'Daria // Premium Service & Care',", "title: 'Daria // Premium Hizmet & İlgi',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (СОПРАНО)',", "voiceBadge: 'VOICE: SYNTHESIS HD (SOPRANO)',", "voiceBadge: 'SES: HD SENTEZ (SOPRANO)',"),
    ("desc: 'Эмпатичный, интеллигентный и располагающий голос. Высокая конверсия в премиальной медицине, туризме и сфере услуг.',", "desc: 'Empathic and polite voice. Highest closing rates in luxury healthcare, high-end travel, and VIP hospitality.',", "desc: 'Empatik, kibar ve güven verici ses tonu. Lüks sağlık, turizm ve VIP hizmet sektörlerinde en yüksek dönüşüm.',"),
    ("name: 'РУСЛАН АЛИЕВ',", "name: 'RUSLAN ALIEV',", "name: 'RUSLAN ALIEV',"),
    ("role: 'ВЕДУЩИЙ ПЕРЕГОВОРЩИК И СТРАТЕГ',", "role: 'CHIEF NEGOTIATOR & STRATEGIST',", "role: 'BAŞ MÜZAKERECİ VE STRATEJİST',"),
    ("badge: 'ПЕРСОНА: РУСЛАН',", "badge: 'PERSONA: RUSLAN',", "badge: 'PERSONA: RUSLAN',"),
    ("title: 'Руслан // Твердые переговоры и опт',", "title: 'Ruslan // Hard Closing & Wholesale',", "title: 'Ruslan // Zorlu Müzakere & Toptan',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ТЕМБР-ЛИДЕР)',", "voiceBadge: 'VOICE: SYNTHESIS HD (EXECUTIVE)',", "voiceBadge: 'SES: HD SENTEZ (LİDER TON)',"),
    ("desc: 'Твердая аргументация, железная позиция по цене без уступок. Идеален для дистрибуции, спецтехники и жестких B2B-переговоров.',", "desc: 'Firm arguments, zero unwarranted discounting. Built for heavy machinery, raw materials, and high-stakes B2B.',", "desc: 'Güçlü argümanlar, tavizsiz fiyat duruşu. Dağıtım, ağır vasıta ve kritik B2B anlaşmalarında uzmandır.',"),
    ("name: 'МЭЙ ЛИН',", "name: 'MEI LIN',", "name: 'MEI LIN',"),
    ("role: 'МЕНЕДЖЕР ПО ВЭД И ТЕХНОЛОГИЯМ',", "role: 'CROSS-BORDER TRADE & TECH LEAD',", "role: 'DIŞ TİCARET VE TEKNOLOJİ MÜDÜRÜ',"),
    ("badge: 'ПЕРСОНА: МЭЙ',", "badge: 'PERSONA: MEI',", "badge: 'PERSONA: MEI',"),
    ("title: 'Мэй // Международные сделки и Tech',", "title: 'Mei // Global Trade & Tech',", "title: 'Mei // Küresel Ticaret & Tech',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ДЕЛОВОЙ)',", "voiceBadge: 'VOICE: SYNTHESIS HD (BUSINESS)',", "voiceBadge: 'SES: HD SENTEZ (KURUMSAL)',"),
    ("desc: 'Структурная, быстрая речь с точностью до цифры. Идеальна для SaaS, IT-решений, импорта из Азии и e-commerce.',", "desc: 'Fast, data-driven communication. Tailored for SaaS, cloud software, Asian import, and global e-commerce.',", "desc: 'Rakam odaklı, hızlı ve net iletişim. SaaS, yazılım, Asya ithalatı ve e-ticaret süreçleri için mükemmeldir.',"),
    ("name: 'МАРК ШТЕЙН',", "name: 'MARK STEIN',", "name: 'MARK STEIN',"),
    ("role: 'КОРПОРАТИВНЫЙ АМБАССАДОР',", "role: 'ENTERPRISE AMBASSADOR',", "role: 'KURUMSAL ANLAŞMALAR ELÇİSİ',"),
    ("badge: 'ПЕРСОНА: МАРК',", "badge: 'PERSONA: MARK',", "badge: 'PERSONA: MARK',"),
    ("title: 'Марк // Корпоративные сделки',", "title: 'Mark // Enterprise Accounts',", "title: 'Mark // Kurumsal Müşteriler',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (СТАТУС)',", "voiceBadge: 'VOICE: SYNTHESIS HD (STATUS)',", "voiceBadge: 'SES: HD SENTEZ (PRESTİJ)',"),
    ("desc: 'Вызывает моментальное доверие собственников и топ-менеджеров. Специализация: консалтинг, инвестпроекты, банковский сектор.',", "desc: 'Builds instant C-level trust. Specializes in management consulting, private equity, and institutional finance.',", "desc: 'Şirket sahipleri ve üst düzey yöneticilerde anında güven oluşturur. Danışmanlık, yatırım ve finans uzmanı.',"),
    ("name: 'АМИНА КАСЫМОВА',", "name: 'AMINA KASYMOVA',", "name: 'AMINA KASYMOVA',"),
    ("role: 'ЭКСПЕРТ ПО ЭЛИТНОЙ НЕДВИЖИМОСТИ',", "role: 'LUXURY REAL ESTATE EXECUTIVE',", "role: 'LÜKS GAYRİMENKUL UZMANI',"),
    ("badge: 'ПЕРСОНА: АМИНА',", "badge: 'PERSONA: AMINA',", "badge: 'PERSONA: AMINA',"),
    ("title: 'Амина // Деликатный премиум-дожим',", "title: 'Amina // Delicate Luxury Closing',", "title: 'Amina // Zarif Satış Kapatma',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (БАРХАТ)',", "voiceBadge: 'VOICE: SYNTHESIS HD (VELVET)',", "voiceBadge: 'SES: HD SENTEZ (KADİFE TON)',"),
    ("desc: 'Мягкое ведение диалога с тактичным дожимом до закрытия договора. Прекрасно работает в загородной и премиум-недвижимости.',", "desc: 'Elegant conversation style with subtle yet decisive closing techniques. Optimized for prime residential assets.',", "desc: 'Zarif diyalog yönetimi ile sözleşme aşamasına taşıyan ikna yeteneği. Lüks konut projeleri için tasarlanmıştır.',"),
    ("name: 'ДЕНИС ВОЛКОВ',", "name: 'DENIS VOLKOV',", "name: 'DENIS VOLKOV',"),
    ("role: 'HIGH-ENERGY СКОРОСТНОЙ КЛОУЗЕР',", "role: 'HIGH-VELOCITY DEAL CLOSER',", "role: 'YÜKSEK ENERJİLİ HIZLI KAPATICI',"),
    ("badge: 'ПЕРСОНА: ДЕНИС',", "badge: 'PERSONA: DENIS',", "badge: 'PERSONA: DENIS',"),
    ("title: 'Денис // Скоростной захват лидов',", "title: 'Denis // Rapid Lead Conversion',", "title: 'Denis // Hızlı Talep Dönüşümü',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ДИНАМИК)',", "voiceBadge: 'VOICE: SYNTHESIS HD (DYNAMIC)',", "voiceBadge: 'SES: HD SENTEZ (DİNAMİK)',"),
    ("desc: 'Динамичный темп речи, моментальная реакция на входящий интерес. Превосходно конвертирует холодный и горячий трафик с рекламы.',", "desc: 'High energy, sub-second responses. Turns cold paid traffic and warm inquiries into paid orders on the spot.',", "desc: 'Dinamik konuşma temposu, anlık reaksiyon. Reklamlardan gelen soğuk ve sıcak trafiği hızla satışa çevirir.',"),
    ("name: 'КЕНДЖИ ТАНАКА',", "name: 'KENJI TANAKA',", "name: 'KENJI TANAKA',"),
    ("role: 'ТЕХНИЧЕСКИЙ ЭКСПЕРТ И B2B-ИНЖЕНЕР',", "role: 'SOLUTIONS ARCHITECT & SALES ENGINEER',", "role: 'B2B ÇÖZÜM MİMARI VE MÜHENDİS',"),
    ("badge: 'ПЕРСОНА: КЕНДЖИ',", "badge: 'PERSONA: KENJI',", "badge: 'PERSONA: KENJI',"),
    ("title: 'Кенджи // Инженерный расчет и B2B',", "title: 'Kenji // Technical Solutions & B2B',", "title: 'Kenji // Teknik Hesaplama & B2B',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ВЗВЕШЕННЫЙ)',", "voiceBadge: 'VOICE: SYNTHESIS HD (TECHNICAL)',", "voiceBadge: 'SES: HD SENTEZ (TEKNİK)',"),
    ("desc: 'Глубокое погружение в ТЗ, сложные спецификации и сметы. Конвертирует технических директоров и инженеров.',", "desc: 'Deep technical comprehension and detailed specifications. Effortlessly handles CTOs, engineers, and procurement leads.',", "desc: 'Teknik şartnamelere ve karmaşık maliyet tablolarına tam hakimiyet. CTO\'lar ve mühendislerle aynı dilde konuşur.',"),
    ("name: 'ЕЛЕНА СМИРНОВА',", "name: 'ELENA SMIRNOVA',", "name: 'ELENA SMIRNOVA',"),
    ("role: 'УПРАВЛЯЮЩИЙ ПАРТНЕР ПО ПРОДАЖАМ',", "role: 'MANAGING SALES PARTNER',", "role: 'YÖNETİCİ SATIŞ ORTAĞI',"),
    ("badge: 'ПЕРСОНА: ЕЛЕНА',", "badge: 'PERSONA: ELENA',", "badge: 'PERSONA: ELENA',"),
    ("title: 'Елена // Высокие чеки и доверие',", "title: 'Elena // High-Ticket & Authority',", "title: 'Elena // Yüksek Hacim & Otorite',"),
    ("voiceBadge: 'ГОЛОС: СИНТЕЗ HD (СТАТУСНЫЙ)',", "voiceBadge: 'VOICE: SYNTHESIS HD (EXECUTIVE)',", "voiceBadge: 'SES: HD SENTEZ (ÜST DÜZEY)',"),
    ("desc: 'Солидный статус и безупречный такт. Проводит переговоры на уровне генеральных директоров и акционеров холдингов.',", "desc: 'Executive presence and impeccable etiquette. Conducts board-level negotiations with holding company owners.',", "desc: 'Kurumsal ağırlık ve kusursuz nezaket. Holding sahipleri ve yönetim kurulu seviyesinde müzakereleri yönetir.',"),

    # ALL INNER TEMPLATES FOR CASES (B2B, REALTY, AUTO, CONSULTING)
    ("Лиды</span>", "Leads</span>", "Talepler</span>"),
    ("Сделки</span>", "Deals</span>", "Fırsatlar</span>"),
    ("Товары и Склады</span>", "Products & Stock</span>", "Ürünler & Depolar</span>"),
    ("Клиенты</span>", "Contacts</span>", "Kişiler</span>"),
    ("Интеграция 1С</span>", "ERP Integration</span>", "ERP Entegrasyonu</span>"),
    ("<span>Сделки</span>", "<span>Deals</span>", "<span>Fırsatlar</span>"),
    ("+ СОЗДАТЬ</span>", "+ CREATE</span>", "+ OLUŞTUR</span>"),
    ("<span>Сделки в работе</span>", "<span>Active Deals</span>", "<span>Aktif Fırsatlar</span>"),
    ("01. Заявка</div>", "01. Inquiry</div>", "01. Talep</div>"),
    ("02. Расчет 1С</div>", "02. ERP Calc</div>", "02. ERP Hesap</div>"),
    ("03. Счет\n", "03. Invoice\n", "03. Fatura\n"),
    ("04. Оплата</div>", "04. Payment</div>", "04. Tahsilat</div>"),
    ("Сделка #4892: ООО \"МеталлСтрой Холдинг\"", "Deal #4892: MetalStroy Holding LLC", "Fırsat #4892: MetalStroy Holding A.Ş."),
    ("Воронка: Оптовые поставки металлопроката", "Pipeline: Industrial Steel Supply", "Huni: Endüstriyel Çelik Tedariki"),
    ("СЧЕТ ВЫСТАВЛЕН</span>", "INVOICE ISSUED</span>", "FATURA KESİLDİ</span>"),
    ("СУММА СДЕЛКИ:</span>", "DEAL VALUE:</span>", "İŞLEM TUTARI:</span>"),
    ("3 420 000 ₽</strong>", "$45,000</strong>", "$45.000</strong>"),
    ("МАРЖА (24.8%):</span>", "MARGIN (24.8%):</span>", "MARJ (%24.8):</span>"),
    ("+848 160 ₽</strong>", "+$11,160</strong>", "+$11.160</strong>"),
    ("ОТВЕТСТВЕННЫЙ:</span>", "ASSIGNEE:</span>", "SORUMLU:</span>"),
    ("ИСТОЧНИК:</span>", "SOURCE:</span>", "KAYNAK:</span>"),
    ("Telegram API (ID: 482)</span>", "Telegram API (ID: 482)</span>", "Telegram API (ID: 482)</span>"),
    ("1С:Управление торговлей v11.5</span>", "ERP Enterprise Inventory</span>", "ERP Ticari Envanter</span>"),
    ("Складской резерв ✓</span>", "Stock Reserved ✓</span>", "Stok Ayrıldı ✓</span>"),
    ("• Арматура А500С 12мм (45 т):</span>", "• Rebar A500C 12mm (45 t):</span>", "• İnşaat Demiri A500C 12mm (45 t):</span>"),
    ("Склад Подольск (Резерв)</span>", "Warehouse North (Reserved)</span>", "Kuzey Deposu (Rezerve)</span>"),
    ("• Балка 20Б1 (18 т):</span>", "• I-Beam 20B1 (18 t):</span>", "• I-Profil 20B1 (18 t):</span>"),
    ("Склад Чехов (Резерв)</span>", "Warehouse South (Reserved)</span>", "Güney Deposu (Rezerve)</span>"),
    ("📞 Звонок</span>", "📞 Call</span>", "📞 Arama</span>"),
    ("✉️ Письмо</span>", "✉️ Email</span>", "✉️ E-posta</span>"),
    ("💬 Чат</span>", "💬 Chat</span>", "💬 Sohbet</span>"),
    ("15 сек автосчет</span>", "15s auto-quote</span>", "15sn otomatik teklif</span>"),

    # Case 2 Realty
    ("companyLogo: 'АС',", "companyLogo: 'AS',", "companyLogo: 'AS',"),
    ("companyName: 'Девелоперская группа «Альянс Девелопмент»',", "companyName: 'Alliance Development Group',", "companyName: 'Alliance Development Group',"),
    ("companyNiche: 'Премиальные коттеджные поселки & Виллы • 450 га',", "companyNiche: 'Luxury Estates & Private Villas • 450 ha',", "companyNiche: 'Lüks Konut Projeleri & Villalar • 450 ha',"),
    ("authorAvatar: 'МК',", "authorAvatar: 'MK',", "authorAvatar: 'MK',"),
    ("authorName: 'Михаил Казанцев',", "authorName: 'Mikhail Kazantsev',", "authorName: 'Mihail Kazantsev',"),
    ("authorRole: 'Директор по продажам элитной недвижимости',", "authorRole: 'Head of Luxury Sales',", "authorRole: 'Lüks Satış Direktörü',"),
    ("review: '«3 800 контактов в архивной базе просто лежали мертвым грузом. Менеджерам было лень звонить старым лидам. Голосовой AI за 3 дня обзвонил всю базу, выявил 142 горячих покупателя и записал 38 человек на просмотры вилл. Мы закрыли 6 сделок на 184 млн рублей без затрат на рекламу.»',",
     "review: '\"3,800 contacts in our old database were sitting idle. Reps refused to cold-call past leads. Voice AI dialed the entire archive in 3 days, qualified 142 high-intent buyers, and scheduled 38 private villa viewings. We closed 6 deals totaling $2.4M with zero ad spend.\"',",
     "review: '\"Eski veritabanımızdaki 3.800 kişi atıl bekliyordu. Temsilciler eski listeleri aramaya üşeniyordu. Sesli AI 3 günde tüm listeyi taradı, 142 sıcak alıcı tespit etti ve 38 villa ziyareti planladı. Reklam harcaması yapmadan $2.4M tutarında 6 satış kapattık.\"',"),
    ("nicheTag: 'НИША: ЗАГОРОДНЫЙ ДЕВЕЛОПМЕНТ & VIP НЕДВИЖИМОСТЬ',", "nicheTag: 'NICHE: LUXURY REAL ESTATE & DEVELOPMENTS',", "nicheTag: 'SEKTÖR: LÜKS GAYRİMENKUL & VİLLA PROJELERİ',"),
    ("stackTag: 'СТЕК: ГОЛОСОВОЙ РОБОТ HD + WHATSAPP + AMOCRM',", "stackTag: 'STACK: NEURAL VOICE HD + WHATSAPP + AMOCRM',", "stackTag: 'ALTYAPI: HD SESLİ AI + WHATSAPP + AMOCRM',"),
    ("title: 'Реактивация архивной базы элитного коттеджного поселка',", "title: 'Database Reactivation for Prime Residential Estates',", "title: 'Lüks Villa Projesi Arşiv Veritabanı Canlandırma',"),
    ("subtitle: 'Голосовой AI-робот обзвонил 3 800 уснувших лидов, презентовал 2-ю очередь и записал на показы',", "subtitle: 'Voice AI engaged 3,800 dormant leads, presented Phase 2, and booked private tours',", "subtitle: 'Sesli AI 3.800 uyuyan müşteriyi aradı, 2. etabı sundu ve VIP randevuları oluşturdu',"),
    ("revenue: '+18.4M ₽',", "revenue: '+$240,000',", "revenue: '+$240.000',"),
    ("revenueNote: 'ЧИСТАЯ МАРЖА С РЕАКТИВАЦИИ',", "revenueNote: 'NET MARGIN FROM REACTIVATION',", "revenueNote: 'CANLANDIRMADAN NET KÂR',"),
    ("{ label: 'ОБЗВОН БАЗЫ', val: '3 800 ЛИДОВ', sub: 'За 3 дня работы робота', color: 'text-sky-950' },", "{ label: 'DATABASE DIALED', val: '3,800 LEADS', sub: 'In 3 days by Voice AI', color: 'text-sky-950' },", "{ label: 'ARANAN LİSTE', val: '3.800 KİŞİ', sub: '3 günde Sesli AI ile', color: 'text-sky-950' },"),
    ("{ label: 'ЗАПИСЬ НА ПОКАЗ', val: '38 СЛОТОВ', sub: 'Целевые визиты в поселок', color: 'text-emerald-600' },", "{ label: 'SITE TOURS', val: '38 SLOTS', sub: 'Targeted estate visits', color: 'text-emerald-600' },", "{ label: 'VİLLA RANDEVUSU', val: '38 RANDEVU', sub: 'Hedefli özel ziyaretler', color: 'text-emerald-600' },"),
    ("{ label: 'ЗАКРЫТО В ДОГОВОР', val: '6 СДЕЛОК', sub: 'На сумму 184.2M ₽', color: 'text-emerald-600' },", "{ label: 'DEALS CLOSED', val: '6 DEALS', sub: 'Total volume $2.4M', color: 'text-emerald-600' },", "{ label: 'KAPATILAN SATIŞ', val: '6 ANLAŞMA', sub: 'Toplam $2.4M hacim', color: 'text-emerald-600' },"),
    ("{ label: 'ЗАТРАТЫ НА ТРАФИК', val: '0 ₽', sub: 'Работа по своей базе', color: 'text-sky-950' }", "{ label: 'AD SPEND', val: '$0', sub: 'Organic archive list', color: 'text-sky-950' }", "{ label: 'REKLAM MALİYETİ', val: '$0', sub: 'Mevcut veritabanı ile', color: 'text-sky-950' }"),
    ("summaryA: '<strong>3 800 контактов</strong> лежали в архиве без касаний 8 месяцев • 0 продаж с базы',", "summaryA: '<strong>3,800 leads</strong> sat untouched in archive for 8 months • $0 revenue',", "summaryA: '<strong>3.800 kişi</strong> 8 aydır arşivde dokunulmadan bekliyordu • $0 gelir',"),
    ("summaryB: 'AI обзвонил базу за <strong>72 часа</strong> • 38 показов • <strong>+18.4M ₽ чистой прибыли</strong>',", "summaryB: 'AI processed list in <strong>72 hours</strong> • 38 tours • <strong>+$240,000 net profit</strong>',", "summaryB: 'AI listeyi <strong>72 saatte</strong> taradı • 38 randevu • <strong>+$240.000 net kâr</strong>',"),
    ("leftTitle: 'Голосовой AI HD • Аудио-звонок лиду',", "leftTitle: 'Voice AI HD • Outbound Call',", "leftTitle: 'HD Sesli AI • Giden Arama',"),
    ("leftBadge: 'СИНТЕЗ ГОЛОСА 60 FPS',", "leftBadge: '60 FPS NEURAL SYNTHESIS',", "leftBadge: '60 FPS NÖRAL SES',"),
    ("<span>Михаил (Архив 2023 г.)</span>", "<span>Michael (2023 Archive)</span>", "<span>Mihail (2023 Arşivi)</span>"),
    ("Согласился на просмотр в Сб 12:00", "Confirmed viewing for Sat 12:00", "Cumartesi 12:00 randevusunu onayladı"),
    ("00:48 / 01:25 • HD Запись", "00:48 / 01:25 • HD Audio", "00:48 / 01:25 • HD Kayıt"),
    ("Слушать диалог", "Listen to Audio", "Diyaloğu Dinle"),
    ("<div><strong class=\"text-sky-950\">AI:</strong> «Михаил, добрый день! Это Дарья из «Альянс Девелопмент». Вы в прошлом году интересовались коттеджами у озера. Мы открыли продажи 2-й очереди со скидкой 12% на старте. Отправить вам генплан в WhatsApp?»</div>",
     "<div><strong class=\"text-sky-950\">AI:</strong> \"Hello Michael! This is Daria from Alliance Development. Last year you looked into our lakeside estates. We just opened Phase 2 sales with a 12% early-bird incentive. May I share the master plan via WhatsApp?\"</div>",
     "<div><strong class=\"text-sky-950\">AI:</strong> \"İyi günler Mihail Bey! Alliance Development\'tan Daria ben. Geçen yıl göl kıyısındaki villalarımızla ilgilenmiştiniz. 2. etabın satışlarını lansmana özel %12 avantajla açtık. Vaziyet planını WhatsApp\'tan ileteyim mi?\"</div>"),
    ("<div><strong class=\"text-slate-950\">Клиент:</strong> «Да, скиньте в WhatsApp. Запишите на показ в субботу в 12:00.»</div>",
     "<div><strong class=\"text-slate-950\">Client:</strong> \"Yes, send it on WhatsApp. And book me for a viewing this Saturday at 12:00.\"</div>",
     "<div><strong class=\"text-slate-950\">Müşteri:</strong> \"Evet, WhatsApp\'tan iletin. Cumartesi 12:00 için de randevu oluşturun.\"</div>"),
    ("«Михаил, закрепил за вами просмотр коттеджа: <strong>Суббота, 12:00</strong>. Персональный пропуск на КП оформлен. Локация и генплан во вложении 👇»",
     "\"Michael, confirmed your private estate tour: <strong>Saturday, 12:00</strong>. Security pass issued. Location pin and master plan attached below 👇\"",
     "\"Mihail Bey, villa sunum randevunuz kaydedildi: <strong>Cumartesi, 12:00</strong>. Güvenlik giriş kartınız hazırlandı. Konum ve vaziyet planı ektedir 👇\""),
    ("Генплан_Лесная_Резиденция_2очередь.pdf", "MasterPlan_Forest_Residences_Phase2.pdf", "VaziyetPlani_Orman_Villalari_Etap2.pdf"),
    ("4.8 MB • Коттедж 280 м²", "4.8 MB • Villa 280 m²", "4.8 MB • Villa 280 m²"),
    ("11:42 • Отправлено в WhatsApp ✓", "11:42 • Delivered in WhatsApp ✓", "11:42 • WhatsApp\'ta İletildi ✓"),
    ("rightTitle: 'amoCRM • Карточка лида #74109',", "rightTitle: 'amoCRM • Lead Card #74109',", "rightTitle: 'amoCRM • Aday Kartı #74109',"),
    ("rightBadge: 'РЕАКТИВАЦИЯ АРХИВА',", "rightBadge: 'ARCHIVE REACTIVATION',", "rightBadge: 'ARŞİV CANLANDIRMA',"),
    ("Воронка: КП \"Лесная Резиденция\"", "Pipeline: Forest Residences Estates", "Huni: Orman Villaları Projesi"),
    ("01. Архив (3 800)</div>", "01. Archive (3,800)</div>", "01. Arşiv (3.800)</div>"),
    ("02. Звонок AI ✓</div>", "02. AI Call ✓</div>", "02. AI Araması ✓</div>"),
    ("03. Просмотр Сб\n", "03. Sat Tour\n", "03. Cmt Ziyaret\n"),
    ("04. Бронь/ДКП</div>", "04. Contract</div>", "04. Sözleşme</div>"),
    ("Сделка #74109: Михаил (Архивная база)", "Deal #74109: Michael (Archive Lead)", "Fırsat #74109: Mihail (Arşiv Talebi)"),
    ("Автоназначение слота показа", "Automated Tour Slot Scheduled", "Otomatik Randevu Ataması"),
    ("СЛОТ ПОДТВЕРЖДЕН</span>", "SLOT CONFIRMED</span>", "RANDEVU ONAYLANDI</span>"),
    ("БЮДЖЕТ ПОКУПКИ:</span>", "PURCHASE BUDGET:</span>", "ALIM BÜTÇESİ:</span>"),
    ("ДАТА ПОКАЗА:</span>", "TOUR DATE:</span>", "RANDEVU TARİHİ:</span>"),
    ("Суббота, 12:00 (Слот подтвержден)</strong>", "Saturday, 12:00 (Slot Confirmed)</strong>", "Cumartesi, 12:00 (Randevu Onaylandı)</strong>"),
    ("ВЫБРАННЫЙ ОБЪЕКТ:</span>", "SELECTED PROPERTY:</span>", "SEÇİLEN MÜLK:</span>"),
    ("КП \"Лесная Резиденция\", Участок №14, Коттедж 280 м²</span>", "Forest Residences, Lot #14, Villa 280 m²</span>", "Orman Villaları, Parsel #14, Villa 280 m²</span>"),
    ("АВТОДОЖИМ:</span>", "AUTO-FOLLOWUP:</span>", "OTOMATİK TAKİP:</span>"),
    ("WHATSAPP НАПОМИНАНИЕ ВКЛ</span>", "WHATSAPP REMINDER ACTIVE</span>", "WHATSAPP HATIRLATICI AKTİF</span>"),
    ("ПРОПУСК ОФОРМЛЕН</span>", "SECURITY PASS ISSUED</span>", "GİRİŞ KARTI ONAYLANDI</span>"),
    ("⚡ Итог: спящий контакт из 3 800 архива реактивирован за 48 сек разговора робота.", "⚡ Result: dormant lead from 3,800 archive reactivated in a 48s AI dialogue.", "⚡ Sonuç: 3.800 kişilik arşivdeki uyuyan aday 48 saniyelik AI görüşmesiyle canlandırıldı."),

    # Case 3 Auto
    ("companyLogo: 'ТА',", "companyLogo: 'TA',", "companyLogo: 'TA',"),
    ("companyName: 'Дилерский центр «ТрансАвто СпецТехника»',", "companyName: 'TransAuto Commercial Fleet Dealership',", "companyName: 'TransAuto Ticari Vasıta Bayisi',"),
    ("companyNiche: 'Тягачи Sitrak, спецтехника & коммерческий лизинг • Оборот 2.1B ₽/год',", "companyNiche: 'Sitrak Semi-Trucks, Machinery & Fleet Leasing • $28M/yr',", "companyNiche: 'Sitrak Çekici, Ağır Vasıta & Filo Leasing • $28M/yıl',"),
    ("authorAvatar: 'ДС',", "authorAvatar: 'DS',", "authorAvatar: 'DS',"),
    ("authorName: 'Denis Самойлов',", "authorName: 'Denis Samoylov',", "authorName: 'Denis Samoylov',"),
    ("authorRole: 'Собственник сети дилерских центров',", "authorRole: 'Owner & Managing Director',", "authorRole: 'Bayi Ağı Sahibi ve Genel Müdür',"),
    ("review: '«45% обращений с Avito падали ночью и на выходных, когда отдел продаж спал. Клиенты успевали оставить заявку 5 конкурентам. AI перехватывает лид за 1.2 секунды прямо в чате Avito, рассчитывает лизинг и бронирует визит на тест-драйв. Конверсия из чата в тест выросла на 42%.»',",
     "review: '\"45% of marketplace inquiries arrived at night and over weekends when sales reps were asleep. Buyers contacted 5 rivals simultaneously. The AI captures leads in 1.2s on the portal chat, computes lease financing, and books test-drive appointments. Closing velocity jumped 42%.\"',",
     "review: '\"İlan portallarından gelen taleplerin %45\'i gece ve hafta sonu geliyordu. Müşteriler aynı anda 5 rakibe yazıyordu. AI 1.2 saniyede talep yakalıyor, leasing ödeme planını iletiyor ve test sürüşü randevusu oluşturuyor. Test sürüşüne dönüşüm %42 arttı.\"',"),
    ("nicheTag: 'НИША: АВТОБИЗНЕС, СПЕЦТЕХНИКА & ЛИЗИНГ',", "nicheTag: 'NICHE: COMMERCIAL FLEET, HEAVY TRUCKS & LEASING',", "nicheTag: 'SEKTÖR: TİCARİ ARAÇ, ÇEKİCİ & LEASING',"),
    ("stackTag: 'СТЕК: AVITO ЧАТ + WHATSAPP API + AMOCRM',", "stackTag: 'STACK: MARKETPLACE CHAT + WHATSAPP API + AMOCRM',", "stackTag: 'ALTYAPI: PORTAL CHAT + WHATSAPP API + AMOCRM',"),
    ("title: 'Дилер коммерческой техники и грузовых авто',", "title: 'Commercial Truck & Heavy Equipment Dealership',", "title: 'Ticari Çekici ve Ağır Vasıta Yetkili Satıcısı',"),
    ("subtitle: 'Круглосуточный захват заявок с Avito, подбор спецтехники и моментальный расчет лизинга',", "subtitle: '24/7 lead capture on marketplaces, equipment lookup, and instant lease calculation',", "subtitle: 'Portallardan 7/24 anında talep yakalama, araç eşleştirme ve otomatik leasing hesabı',"),
    ("revenue: '+8.2M ₽',", "revenue: '+$110,000',", "revenue: '+$110.000',"),
    ("revenueNote: 'ДОПОЛНИТЕЛЬНАЯ ВЫРУЧКА В МЕСЯЦ',", "revenueNote: 'ADDITIONAL MONTHLY REVENUE',", "revenueNote: 'AYLIK EK CİRO',"),
    ("{ label: 'ВРЕМЯ ОТКЛИКА', val: '1.2 SECONDS', sub: 'В ночные часы и выходные', color: 'text-sky-950' },", "{ label: 'RESPONSE TIME', val: '1.2 SECONDS', sub: 'Nights & weekend hours', color: 'text-sky-950' },", "{ label: 'YANIT SÜRESİ', val: '1.2 SANİYE', sub: 'Gece ve hafta sonları', color: 'text-sky-950' },"),
    ("{ label: 'ДОХОДИМОСТЬ НА ТЕСТ', val: '+42%', sub: 'Рост конверсии в осмотр техники', color: 'text-emerald-600' },", "{ label: 'TEST-DRIVE TOURS', val: '+42%', sub: 'In-person inspection rate', color: 'text-emerald-600' },", "{ label: 'TEST SÜRÜŞÜ', val: '+%42', sub: 'Araç inceleme oranı', color: 'text-emerald-600' },"),
    ("{ label: 'КОНВЕРСИЯ В ДОГОВОР', val: '+28%', sub: 'Из холодного чата в сделку', color: 'text-emerald-600' },", "{ label: 'CONTRACT RATE', val: '+28%', sub: 'Cold chat to closed deal', color: 'text-emerald-600' },", "{ label: 'SÖZLEŞME ORANI', val: '+%28', sub: 'Sohbetten satışa dönüşüm', color: 'text-emerald-600' },"),
    ("{ label: 'ОКУПАЕМОСТЬ AI', val: '14 ДНЕЙ', sub: 'С первых двух проданных тягачей', color: 'text-sky-950' }", "{ label: 'SYSTEM ROI', val: '14 DAYS', sub: 'With first 2 sold trucks', color: 'text-sky-950' }", "{ label: 'AMORTİ SÜRESİ', val: '14 GÜN', sub: 'İlk satılan 2 çekici ile', color: 'text-sky-950' }"),
    ("summaryA: '<strong>45% заявок с Avito</strong> приходили ночью и сгорали • Менеджеры тратили до 40 мин на сбор КП',", "summaryA: '<strong>45% of marketplace leads</strong> arrived at night and were lost • Reps took 40 min to quote',", "summaryA: '<strong>Taleplerin %45\'i</strong> gece gelip kayboluyordu • Temsilciler teklif için 40 dk harcıyordu',"),
    ("summaryB: 'Отклик <strong>1.2 секунды 24/7</strong> • Авторасчет лизинга • <strong>+8.2M ₽ доп. продаж техники</strong>',", "summaryB: 'Response in <strong>1.2s 24/7</strong> • Instant lease model • <strong>+$110,000 extra sales</strong>',", "summaryB: '<strong>7/24 1.2 sn yanıt</strong> • Otomatik leasing hesabı • <strong>+$110.000 ek ciro</strong>',"),
    ("leftTitle: 'Avito Сообщения • Sitrak C7H Тягач',", "leftTitle: 'Marketplace Inbound • Sitrak C7H Truck',", "leftTitle: 'Portal Mesajları • Sitrak C7H Çekici',"),
    ("leftBadge: 'AVITO API • 23:40 (НОЧЬ)',", "leftBadge: 'PORTAL API • 23:40 (NIGHT)',", "leftBadge: 'PORTAL API • 23:40 (GECE)',"),
    ("<span>ООО \"ТрансЛогистик\" (Покупатель)</span>", "<span>TransLogistics LLC (Buyer)</span>", "<span>TransLojistik A.Ş. (Alıcı)</span>"),
    ("в сети • Avito Профиль верифицирован ✓", "online • Verified Corporate Buyer ✓", "çevrimiçi • Doğrulanmış Kurumsal Profil ✓"),
    ("Седельный тягач Sitrak C7H 4x2 Luxury (480 л.с.)", "Sitrak C7H 4x2 Luxury Semi-Truck (480 hp)", "Sitrak C7H 4x2 Luxury Çekici Kamyon (480 bg)"),
    ("«Седельный тягач Sitrak C7H в наличии? Какой аванс и ежемесячный платеж в лизинг на 3 года?»", "\"Is Sitrak C7H semi-truck in stock? What is the down payment and monthly lease payment for 3 years?\"", "\"Sitrak C7H çekici stokta var mı? 3 yıllık leasing için peşinat ve aylık ödeme ne kadar olur?\""),
    ("23:40:05 (Ночь)", "23:40:05 (Night)", "23:40:05 (Gece)"),
    ("AI Дилер Altai Optima", "AI Dealer Altai Optima", "AI Yetkili Satıcı Altai Optima"),
    ("1.2 сек отклик ✓", "1.2s response ✓", "1.2 sn yanıt ✓"),
    ("«В наличии 4 тягача 2024 г. на стоянке Север. При авансе 15% (2 220 000 ₽) платеж: <strong>218 000 ₽/мес</strong> с НДС и КАСКО. Забронировать тягач на осмотр завтра в 11:00?»",
     "\"4 units (2024 model) in stock at North Yard. With 15% down ($28,500), monthly payment is: <strong>$2,850/mo</strong> including full insurance. Shall I reserve a unit for your test inspection tomorrow at 11:00?\"",
     "\"Kuzey Otoparkımızda 4 adet 2024 model çekici mevcut. %15 peşinatla ($28.500) aylık ödeme: tam kasko dahil <strong>$2.850/ay</strong>. Yarın 11:00 için aracı adınıza rezerve edelim mi?\""),
    ("23:40:07 • ✓✓ Доставлено", "23:40:07 • ✓✓ Delivered", "23:40:07 • ✓✓ İletildi"),
    ("«Да, бронируйте на 11:00, приеду с водителем и реквизитами.»", "\"Yes, reserve for 11:00, I will arrive with my driver and corporate documents.\"", "\"Evet, 11:00 için rezerve edin, şoförüm ve şirket evraklarımızla geleceğim.\""),
    ("Лизинг 36 мес • Одобрение 99%", "Lease 36 mo • 99% Approval", "Leasing 36 ay • %99 Onay"),
    ("Стоянка Север (4 тягача)", "North Yard (4 units)", "Kuzey Sahası (4 araç)"),
    ("Тест-драйв Завтра 11:00", "Test Inspection Tomorrow 11:00", "Test Sürüşü Yarın 11:00"),
    ("rightTitle: 'amoCRM • Ночной лид и бронь техники',", "rightTitle: 'amoCRM • Night Lead & Asset Lock',", "rightTitle: 'amoCRM • Gece Talebi & Araç Rezervasyonu',"),
    ("rightBadge: 'AMOCRM + 1С ЛИЗИНГ',", "rightBadge: 'AMOCRM + ERP LEASING',", "rightBadge: 'AMOCRM + ERP LEASING',"),
    ("Воронка: Тягачи и Спецтехника в лизинг", "Pipeline: Heavy Trucks & Fleet Leasing", "Huni: Ticari Çekici ve Ağır Vasıta Leasing"),
    ("БРОНЬ ПОДТВЕРЖДЕНА</span>", "ASSET RESERVED</span>", "REZERVASYON ONAYLANDI</span>"),
    ("01. Avito Чат 23:40</div>", "01. Portal Chat 23:40</div>", "01. Portal Chat 23:40</div>"),
    ("02. Лизинг 1С ✓</div>", "02. ERP Lease ✓</div>", "02. ERP Leasing ✓</div>"),
    ("03. Бронь 11:00\n", "03. Lock 11:00\n", "03. Randevu 11:00\n"),
    ("04. Договор</div>", "04. Agreement</div>", "04. Sözleşme</div>"),
    ("СТОИМОСТЬ ТЯГАЧА:</span>", "TRUCK VALUE:</span>", "ARAÇ DEĞERİ:</span>"),
    ("АВАНС (15%):</span>", "DOWN PAYMENT (15%):</span>", "PEŞİNAT (%15):</span>"),
    ("2 220 000 ₽</strong>", "$28,500</strong>", "$28.500</strong>"),
    ("14 800 000 ₽</strong>", "$190,000</strong>", "$190.000</strong>"),
    ("ПЛАТЕЖ ПО ЛИЗИНГУ:</span>", "MONTHLY LEASE PAYMENT:</span>", "AYLIK LEASING ÖDEMESİ:</span>"),
    ("218 000 ₽ / мес (36 мес)</strong>", "$2,850 / mo (36 mo)</strong>", "$2.850 / ay (36 ay)</strong>"),
    ("ДАТА ВИЗИТА:</span>", "TEST-DRIVE DATE:</span>", "ZİYARET TARİHİ:</span>"),
    ("Завтра, 11:00 (Стоянка Север)</strong>", "Tomorrow, 11:00 (North Yard)</strong>", "Yarın, 11:00 (Kuzey Sahası)</strong>"),
    ("1С:Лизинг • Автоматический скоринг</span>", "ERP Leasing • Automated Scoring</span>", "ERP Leasing • Otomatik Skorlama</span>"),
    ("Одобрено ✓</span>", "Approved ✓</span>", "Onaylandı ✓</span>"),
    ("⚡ Итог: ночная заявка с Avito закрыта на тест-драйв за 12 секунд переписки без участия менеджера.",
     "⚡ Result: late-night marketplace inquiry locked into a live test-drive in 12s with zero human rep involvement.",
     "⚡ Sonuç: gece gelen portal talebi temsilci olmadan 12 saniyede test sürüşüne bağlandı."),

    # Case 4 Consulting
    ("companyLogo: 'В&П',", "companyLogo: 'V&P',", "companyLogo: 'V&P',"),
    ("companyName: 'Консалтинговая группа «Вершинин & Партнеры»',", "companyName: 'Vershinin & Partners Advisory Group',", "companyName: 'Vershinin & Partners Danışmanlık Grubu',"),
    ("companyNiche: 'Налоговый аудит холдингов & B2B консалтинг • Оборот 450M ₽/год',", "companyNiche: 'Corporate Tax Audit & Enterprise Consulting • $6M/yr',", "companyNiche: 'Kurumsal Vergi Denetimi & B2B Danışmanlık • $6M/yıl',"),
    ("authorAvatar: 'РВ',", "authorAvatar: 'RV',", "authorAvatar: 'RV',"),
    ("authorName: 'Роман Вершинин',", "authorName: 'Roman Vershinin',", "authorName: 'Roman Vershinin',"),
    ("authorRole: 'Управляющий партнер',", "authorRole: 'Managing Partner',", "authorRole: 'Yönetici Ortak',"),
    ("review: '«Партнеры с чеком 500 000+ ₽ тратили по 15 часов в неделю на первичные созвоны с нецелевыми лидами. AI проводит скоринг по 12 критериям прямо в Instagram Direct и ставит в календарь только квалифицированных собственников с крупным оборотом. Время закрытия сделки сократилось в 3 раза.»',",
     "review: '\"Senior partners charging $10k+ spent 15 hours a week on unqualified discovery calls. The AI scores leads across 12 criteria directly in Instagram Direct and schedules only high-revenue business owners into our calendar. Sales cycle dropped 3x.\"',",
     "review: '\"Kıdemli ortaklarımız uygun olmayan adaylarla yapılan ön görüşmelerde haftada 15 saat kaybediyordu. AI Instagram Direct\'te 12 kritere göre skorlama yapıyor ve yalnızca yüksek cirolu şirket sahiplerini takvime ekliyor. Satış döngüsü 3 kat hızlandı.\"',"),
    ("nicheTag: 'НИША: B2B КОНСАЛТИНГ & НАЛОГОВЫЙ АУДИТ',", "nicheTag: 'NICHE: B2B CONSULTING & TAX AUDIT',", "nicheTag: 'SEKTÖR: B2B DANIŞMANLIK & VERGİ DENETİMİ',"),
    ("stackTag: 'СТЕК: INSTAGRAM DIRECT + TELEGRAM + CALENDAR AI',", "stackTag: 'STACK: INSTAGRAM DIRECT + TELEGRAM + CALENDAR AI',", "stackTag: 'ALTYAPI: INSTAGRAM DIRECT + TELEGRAM + CALENDAR AI',"),
    ("title: 'Интеллектуальный скоринг и фильтрация B2B-клиентов',", "title: 'Intelligent B2B Lead Qualification & Calendar Booking',", "title: 'B2B Akıllı Skorlama ve Otomatik Takvim Randevusu',"),
    ("subtitle: 'Автоматическая квалификация ЛПР в соцсетях и бронирование слотов в Google Calendar',", "subtitle: 'Automated executive qualification in social media and seamless Google Calendar scheduling',", "subtitle: 'Sosyal medyada yetkili tespiti ve Google Takvim\'de otomatik toplantı oluşturma',"),
    ("revenue: '+4.6M ₽',", "revenue: '+$60,000',", "revenue: '+$60.000',"),
    ("revenueNote: 'ПРИРОСТ МЕСЯЧНОЙ ВЫРУЧКИ',", "revenueNote: 'MONTHLY REVENUE GAIN',", "revenueNote: 'AYLIK EK CİRO',"),
    ("{ label: 'ВРЕМЯ ДО ЗУМА', val: '4 ЧАСА', sub: 'Вместо 7 дней ожидания', color: 'text-sky-950' },", "{ label: 'TIME TO ZOOM', val: '4 HOURS', sub: 'Instead of 7-day delay', color: 'text-sky-950' },", "{ label: 'TOPLANTI HIZI', val: '4 SAAT', sub: '7 günlük bekleme yerine', color: 'text-sky-950' },"),
    ("{ label: 'СРЕДНИЙ ЧЕК', val: '+35%', sub: 'За счет точной квалификации', color: 'text-emerald-600' },", "{ label: 'AVERAGE DEAL', val: '+35%', sub: 'Targeted qualification', color: 'text-emerald-600' },", "{ label: 'ORTALAMA TUTAR', val: '+%35', sub: 'Hassas profilleme ile', color: 'text-emerald-600' },"),
    ("{ label: 'РУТИНА ПАРТНЕРОВ', val: '0 ЧАСОВ', sub: 'На нецелевые звонки', color: 'text-emerald-600' },", "{ label: 'PARTNER WASTE', val: '0 HOURS', sub: 'On unqualified calls', color: 'text-emerald-600' },", "{ label: 'ZAMAN KAYBI', val: '0 SAAT', sub: 'Uygunsuz görüşmelerde', color: 'text-emerald-600' },"),
    ("{ label: 'ОКУПАЕМОСТЬ AI', val: '9 ДНЕЙ', sub: 'С первого закрытого аудита', color: 'text-sky-950' }", "{ label: 'PAYBACK PERIOD', val: '9 DAYS', sub: 'With first closed audit', color: 'text-sky-950' }", "{ label: 'AMORTİ SÜRESİ', val: '9 GÜN', sub: 'İlk denetim sözleşmesiyle', color: 'text-sky-950' }"),
    ("summaryA: 'Партнеры тратили <strong>15 ч/нед</strong> на нецелевые созвоны • Долгий цикл записи (5-7 дней)',", "summaryA: 'Partners spent <strong>15 hrs/wk</strong> on bad calls • Scheduling lag took 5-7 days',", "summaryA: 'Ortaklar haftada <strong>15 saat</strong> verimsiz görüşme yapıyordu • Randevu 5-7 gün sürüyordu',"),
    ("summaryB: 'AI-скоринг 12 параметров • <strong>Zoom через 4 часа</strong> • <strong>+4.6M ₽ выручки</strong>',", "summaryB: '12-point AI scoring • <strong>Zoom within 4 hours</strong> • <strong>+$60,000 net profit</strong>',", "summaryB: '12 kriterli AI analizi • <strong>4 saatte Zoom</strong> • <strong>+$60.000 net kazanç</strong>',"),
    ("leftTitle: 'Instagram Direct • Скоринг ЛПР',", "leftTitle: 'Instagram Direct • Executive Scoring',", "leftTitle: 'Instagram Direct • Yetkili Analizi',"),
    ("leftBadge: 'DIRECT + CALENDAR AI',", "leftBadge: 'DIRECT + CALENDAR AI',", "leftBadge: 'DIRECT + CALENDAR AI',"),
    ("roman_invest_group (Роман В.)", "roman_invest_group (Roman V.)", "roman_invest_group (Roman V.)"),
    ("Собственник • Оборот 800M • В сети", "Owner • Revenue $10M+ • Online", "Şirket Sahibi • Ciro $10M+ • Çevrimiçi"),
    ("«Нужен налоговый аудит группы компаний (холдинг 3 юрлица, оборот 800 млн) перед реструктуризацией. Кто ведет такие проекты?»",
     "\"We require a corporate tax audit for a 3-entity holding company ($10M+ revenue) prior to restructuring. Who leads these engagements?\"",
     "\"Yeniden yapılanma öncesinde 3 şirketli holdingimiz ($10M+ ciro) için vergi denetimi gerekiyor. Bu ölçekteki projeleri kim yönetiyor?\""),
    ("15 сек ✓", "15 sec ✓", "15 sn ✓"),
    ("«Здравствуйте, Роман! Проекты с оборотом от 500 млн ведет лично управляющий партнер. Провел экспресс-скоринг: подходит <strong>четверг в 15:00</strong> для конфиденциального Zoom-разбора?»",
     "\"Hello Roman! Engagements of this scale are personally led by our Managing Partner. I have conducted discovery scoring: is <strong>Thursday at 15:00</strong> suitable for a confidential Zoom session?\"",
     "\"Merhaba Roman Bey! Bu ölçekteki projeleri bizzat Yönetici Ortağımız yönetmektedir. Ön uygunluk analizini tamamladım: Gizlilik çerçevesinde bir Zoom toplantısı için <strong>Perşembe 15:00</strong> uygun mudur?\""),
    ("📅 Zoom: Налоговый аудит холдинга", "📅 Zoom: Holding Corporate Tax Audit", "📅 Zoom: Holding Vergi Denetimi Toplantısı"),
    ("СЛОТ ПОДТВЕРЖДЕН", "SLOT CONFIRMED", "TOPLANTI ONAYLANDI"),
    ("Четверг, 15:00 – 15:45 • Управляющий партнер • Бриф сформирован", "Thursday, 15:00 – 15:45 • Managing Partner • Brief Prepared", "Perşembe, 15:00 – 15:45 • Yönetici Ortak • Ön Bilgi Formu Hazır"),
    ("16:20:25 • ✓✓ Прочитано", "16:20:25 • ✓✓ Read", "16:20:25 • ✓✓ Okundu"),
    ("«Подтверждаю четверг 15:00. Жду ссылку на Zoom и бриф.»", "\"Confirming Thursday 15:00. Looking forward to the Zoom link and brief.\"", "\"Perşembe 15:00 için onaylıyorum. Zoom bağlantısını ve toplantı özetini bekliyorum.\""),
    ("rightTitle: 'amoCRM + Google Calendar • Сделка #11084',", "rightTitle: 'amoCRM + Google Calendar • Deal #11084',", "rightTitle: 'amoCRM + Google Calendar • Fırsat #11084',"),
    ("rightBadge: 'AMOCRM + GOOGLE CALENDAR',", "rightBadge: 'AMOCRM + GOOGLE CALENDAR',", "rightBadge: 'AMOCRM + GOOGLE CALENDAR',"),
    ("Воронка: Юридический консалтинг", "Pipeline: Corporate Legal Advisory", "Huni: Kurumsal Hukuk & Danışmanlık"),
    ("ZOOM НАЗНАЧЕН", "ZOOM CONFIRMED", "ZOOM ONAYLANDI"),
    ("01. Direct ✓</div>", "01. Direct ✓</div>", "01. Direct ✓</div>"),
    ("02. Скоринг 12/12 ✓</div>", "02. Scoring 12/12 ✓</div>", "02. 12/12 Skorlama ✓</div>"),
    ("03. Zoom Чт 15:00\n", "03. Zoom Thu 15:00\n", "03. Zoom Perş 15:00\n"),
    ("04. Договор 750k</div>", "04. Contract $10k</div>", "04. Sözleşme $10k</div>"),
    ("ЧЕК ПРОЕКТА:</span>", "PROJECT VALUE:</span>", "PROJE BEDELİ:</span>"),
    ("СКОРИНГ AI:</span>", "AI SCORING:</span>", "AI SKORLAMASI:</span>"),
    ("12 из 12 параметров</span>", "12 of 12 criteria</span>", "12 üzerinden 12 kriter</span>"),
    ("ОБОРОТ БИЗНЕСА:</span>", "ANNUAL REVENUE:</span>", "ŞİRKET CİROSU:</span>"),
    ("800 000 000 ₽ (Холдинг)</strong>", "$10,000,000+ (Holding)</strong>", "$10.000.000+ (Holding)</strong>"),
    ("СЛОТ CALENDAR:</span>", "CALENDAR SLOT:</span>", "TAKVİM RANDEVUSU:</span>"),
    ("Чт, 15:00 – 15:45</strong>", "Thu, 15:00 – 15:45</strong>", "Perş, 15:00 – 15:45</strong>"),
    ("Ссылка Zoom: <span class=\"font-mono text-sky-700 font-bold\">zoom.us/j/94821034...</span> • Бриф рисков отправлен в календарь партнера.",
     "Zoom Link: <span class=\"font-mono text-sky-700 font-bold\">zoom.us/j/94821034...</span> • Risk brief delivered to partner calendar.",
     "Zoom Bağlantısı: <span class=\"font-mono text-sky-700 font-bold\">zoom.us/j/94821034...</span> • Risk analiz özeti yönetici takvimine eklendi."),
    ("⚡ Итог: квалифицированный лид с оборотом 800M ₽ поставлен в календарь партнера за 3 минуты.",
     "⚡ Result: qualified enterprise lead ($10M+ revenue) booked directly into partner calendar in 3 minutes.",
     "⚡ Sonuç: $10M+ cirolu nitelikli kurumsal müşteri 3 dakikada yönetici takvimine randevu olarak eklendi."),
    ("Отправьте сообщение...", "Type a message...", "Mesaj yazın..."),

    # Direct replacements for any other remnants
    ('>Э<', '>E<', '>E<'),
    ('>РВ<', '>RV<', '>RV<'),
    ('>МВ<', '>MV<', '>MV<'),
    ('>АС<', '>AS<', '>AS<'),
    ('>ЕК<', '>EK<', '>EK<'),
    ('>ТЛ<', '>TL<', '>TL<'),
    ('>В&П<', '>V&P<', '>V&P<'),
    ('>ТА<', '>TA<', '>TA<'),
    ('>ДС<', '>DS<', '>DS<'),
    ('>МК<', '>MK<', '>MK<')
]