# -*- coding: utf-8 -*-
import re

with open('index.html', 'r', encoding='utf-8') as f:
    ru_html = f.read()

# ==============================================================================
# 1. ENGLISH TRANSLATION MAP
# ==============================================================================
en_dict = {
    '<html lang="ru"': '<html lang="en"',
    'Altai Optima — Autonomous AI Business Architecture': 'Altai Optima — Autonomous AI Sales Architecture',
    'Altai Optima — Автономный AI-отдел продаж': 'Altai Optima — Autonomous AI Sales Architecture',
    
    # Resume SVG watermark
    "fill='rgba(2,132,199,0.035)' letter-spacing='4'%3E%D0%A0%D0%95%D0%97%D0%AE%D0%9C%D0%95%3C/text%3E": "fill='rgba(2,132,199,0.035)' letter-spacing='4'%3ERESUME%3C/text%3E",

    # Language Switchers
    '<span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">RU</span>\n          <a href="en.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">EN</a>\n          <a href="tr.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">TR</a>': '<a href="index.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">RU</a>\n          <span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">EN</span>\n          <a href="tr.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">TR</a>',
    '<span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">RU</span>\n            <a href="en.html" class="px-2 py-0.5 rounded-full hover:text-white transition">EN</a>\n            <a href="tr.html" class="px-2 py-0.5 rounded-full hover:text-white transition">TR</a>': '<a href="index.html" class="px-2 py-0.5 rounded-full hover:text-white transition">RU</a>\n            <span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">EN</span>\n            <a href="tr.html" class="px-2 py-0.5 rounded-full hover:text-white transition">TR</a>',

    # Navigation
    '>КЕЙСЫ<': '>CASES<',
    '>КАЛЬКУЛЯТОР<': '>CALCULATOR<',
    '>АРХИТЕКТУРА<': '>ARCHITECTURE<',
    '>РЕЗЮМЕ СОТРУДНИКА<': '>AI RESUME<',
    '>РЕЗЮМЕ<': '>RESUME<',
    '>ТЕСТОВЫЙ ЗАПУСК<': '>TEST PILOT<',
    '>ТЕСТ<': '>TEST<',
    'СВЯЗАТЬСЯ С МЕНЕДЖЕРОМ': 'CONTACT MANAGER',
    'title="Подняться наверх"': 'title="Back to Top"',
    'title="Написать в Telegram"': 'title="Message via Telegram"',
    'title="Написать в WhatsApp"': 'title="Message via WhatsApp"',

    # Hero
    'Добрый день. Меня зовут Эва, как могу вам помочь?': 'Good day! I am Eva, how can I assist your business today?',
    'Тестовый запуск': 'Test Pilot',
    'АВТОНОМНЫЙ': 'AUTONOMOUS',
    'AI-ОТДЕЛ ПРОДАЖ': 'AI SALES DEPARTMENT',
    'Пока наемный персонал теряет прибыль компании, искусственный интеллект конвертирует каждый контакт в сделку': 'While human reps lose company profits, artificial intelligence converts every lead into a closed deal',
    'Посмотреть выгоду': 'Calculate Revenue',
    '100% ВНИМАНИЯ': '100% ATTENTION',
    ' К КАЖДОМУ КЛИЕНТУ': ' TO EVERY CLIENT',
    'Скролл вниз': 'Scroll Down',

    # Pain points
    'СКОЛЬКО ДЕНЕГ ВЫ ТЕРЯЕТЕ,': 'HOW MUCH REVENUE DO YOU LOSE,',
    'ПОКА МЕНЕДЖЕР ТОРМОЗИТ?': 'WHILE SALES REPS DELAY?',
    '// ПРАВИЛО 3-Х СЕКУНД В B2B И B2C': '// THE 3-SECOND RULE IN SALES',
    'Вы оплачиваете рекламу и привлекаете лиды, но деньги сгорают на трех системных ошибках наемного персонала': 'You invest in advertising and acquire leads, but revenue burns due to three systemic human sales mistakes',
    'ПОТЕРЯ ВЫРУЧКИ': 'LOST REVENUE',
    'ВЫХОДНЫЕ & НОЧЬ': 'WEEKENDS & NIGHTS',
    'Ответим в понедельник': 'We will reply on Monday',
    'Клиент готов оплатить чек 300 000 ₽ вечером в выходной. Менеджер не на связи. Через 5 минут заказ уходит конкуренту, ответившему сразу.': 'A high-intent buyer is ready to pay a $5,000 invoice on a weekend evening. Rep is offline. Within 5 minutes the order is lost to a faster competitor.',
    'СЛИВ КОНВЕРСИИ': 'CONVERSION DROP',
    'ОЖИДАНИЕ 2 ЧАСА': '2-HOUR WAIT',
    'Кофе ценой в сделку': 'A Coffee That Costs a Deal',
    'Горячая заявка остывает, пока сотрудник раскачивается с утра. Лид теряет интерес и при звонке сухо бросает: спасибо, уже неактуально.': 'A hot inbound lead goes cold while a sales rep gets ready for the day. The buyer loses interest: "Thanks, already bought elsewhere."',
    'УТЕЧКА МАРЖИ': 'MARGIN LEAK',
    'ПЕРЕГОВОРЫ': 'NEGOTIATIONS',
    'Скидка из слабости': 'Discounts from Weakness',
    'Сотрудник пугается возражения дорого и раздает скидки за счет вашей прибыли, вместо аргументации ценности и удержания полной маржи.': 'Rep fears price resistance and gives away unapproved discounts from your profit instead of defending product value and margin.',
    'А МОЖЕТЕ ПОЛУЧАТЬ...': 'OR YOU COULD BE EARNING...',
    'title="А можете получать..."': 'title="Or you could be earning..."',
    'title="Перейти к +30% к выручке"': 'title="Jump to +30% Net Revenue"',

    # +30%
    '+30% К ВЫРУЧКЕ': '+30% NET REVENUE',
    'Оптимизируем каждый этап вашей воронки и': 'We optimize every stage of your sales funnel and',
    'выжимаем максимум чистой прибыли из входящего потока': 'extract maximum net profit from every incoming lead',
    'Мгновенный захват горячего клиента': 'Instant Capture of High-Intent Leads',
    'СЕКУНДЫ': 'SECONDS',
    'ВРЕМЯ ОТКЛИКА 24/7': '24/7 RESPONSE SPEED',
    'Захват лида за 0.8 секунды': '0.8-second lead capture',
    'Пока конкуренты открывают CRM, ваш AI уже презентовал продукт и выставил счет': 'While competitors open their CRM, your AI has already presented the product and sent an invoice',
    'В 45 раз быстрее человека': '45x faster than human reps',
    'Ответ в первую минуту <strong class="text-sky-700 font-bold">поднимает конверсию в закрытие сделки на 40%</strong>': 'Responding in the first minute <strong class="text-sky-700 font-bold">boosts closed deals conversion by 40%</strong>',
    ', без пауз, раздражения и глупых опечаток нанятых стажеров.': ', with zero pauses, zero frustration, and zero trainee typos.',
    '<strong class="text-emerald-700 font-bold">AI-продавец знает абсолютно всю информацию о продукте и компании</strong>': '<strong class="text-emerald-700 font-bold">AI sales agent knows 100% of product specifications and company policies</strong>',
    ', легко отрабатывает любое возражение и снимает «дорого» на основе кейсов вместо уступок за счет чистой прибыли': ', seamlessly handles any price objection using proven cases instead of discounting from your profit',
    'Круглосуточная работа без выгорания и человеческого фактора.': '24/7/365 nonstop execution without burnout or human factor.',
    '<strong class="text-amber-700 font-bold">Каждая заявка бережно дожимается до оплаты</strong>': '<strong class="text-amber-700 font-bold">Every opportunity is persistently guided to closed-won payment</strong>',
    'Четкая механика сделки': 'Flawless Sales Mechanics',
    'Рутина уходит алгоритмам, чистая прибыль остается бизнесу': 'Routine is offloaded to algorithms, net profit stays with business',
    'В 8 РАЗ БЫСТРЕЕ': '8X FASTER',
    'СОГЛАСОВАНИЕ КП': 'PROPOSAL APPROVAL',
    '1 день вместо 8 дней': '1 day instead of 8 days',
    'Автоматический расчет спецификации и сметы по прайсу без скидок из страха потери лида': 'Automated quote calculation from price book with zero fear-based discounts',
    '100% ОПЛАТА': '100% PAID DEALS',
    'БЕЗОШИБОЧНО': 'ZERO ERRORS',
    'Деньги на расчетном счете': 'Funds secured in bank account',
    'AI контролирует предоплаты, акты и дебиторку без неловкости и забывчивости людей': 'AI tracks deposits, contracts, and accounts receivable without human awkwardness or forgetfulness',

    # Architecture
    '// АРХИТЕКТУРА СИСТЕМЫ': '// SYSTEM ARCHITECTURE',
    'Четыре контура автономных продаж': 'Four Pillars of Autonomous Sales',
    'ГОЛОСОВОЙ AI': 'VOICE AI',
    'Живая речь эксперта': 'Human-Like Expert Voice',
    'Собеседник слышит уверенного менеджера с безупречной дикцией.': 'The caller hears a confident, articulate sales manager.',
    'AI-продавец мгновенно считывает микропаузы,': 'AI senses speech micro-pauses in real time,',
    'снимает возражения и ведет коммуникацию человеческим голосом и подачей': 'resolves objections and drives conversation with flawless human tone and pacing',
    'Естественные интонации и контекстная память': 'Natural intonations & persistent memory',
    '100% фокус на продаже': '100% focused on closing',
    'ВСЕ МЕССЕНДЖЕРЫ': 'OMNICHANNEL MESSAGING',
    'Мгновенный ответ в любом удобном для клиента мессенджере': 'Instant real-time responses across all client messaging channels',
    'КАНАЛЫ СВЯЗИ 24/7/365:': '24/7/365 CHANNELS:',
    'Официальный API': 'Official API',
    'Личные и бот': 'Personal & Bots',
    'Avito Чат': 'Live Chat',
    'Авто-ответ 24/7': 'Auto-reply 24/7',
    'РЕАКТИВАЦИЯ АРХИВА': 'DATABASE REACTIVATION',
    'Второе дыхание базы': 'Revitalizing Cold Databases',
    'Уснувшие контакты возвращаются в диалог': 'Dormant contacts re-engage in active sales dialogues',
    'через деликатные персонализированные касания без спама и раздражения': 'through tailored, high-value touches without spam or annoyance',
    'Уснувшая база': 'Dormant base',
    'Успешная оплата': 'Paid deals',
    '800 контактов': '800 contacts',
    '+1.8M ₽': '+$24,000',
    'АВТОНОМНАЯ CRM': 'AUTONOMOUS CRM',
    'Сделки двигаются сами': 'Deals Advance Automatically',
    'Система протоколирует договоренности, выставляет счета и': 'The system records commitments, issues invoices, and',
    'автоматически переводит этап сделки по воронке без участия человека': 'automatically shifts deal stages through the funnel without human effort',
    'Этап 1': 'Stage 1',
    'Этап 2': 'Stage 2',
    'Этап 3: Оплата': 'Stage 3: Payment',
    'Скоринг': 'Scoring',
    'Расчет КП': 'Quote Calculation',
    'Финал': 'Final',
    'Оплачено ✓': 'Paid ✓',
    '100% полей в CRM': '100% Fields in CRM',
    'Прайс защищен': 'Price Protected',
    'ДЕНЬГИ НА СЧЕТУ': 'FUNDS IN ACCOUNT',
    'Интеграция с вашей CRM и базами данных': 'Integration with your CRM and databases',
    'Битрикс24 REST': 'Bitrix24 REST',
    'Google Sheets API': 'Google Sheets API',
    '1С:Предприятие': '1C Enterprise / ERP',
    'МойСклад': 'MoySklad / ERP',
    'Подключение за 3 рабочих дня без остановки текущих продаж': 'Deployment in 3 business days without interrupting active operations',
    'Сквозная синхронизация': 'Full-cycle synchronization',

    # Simulator
    '// СИМУЛЯТОР ЖИВЫХ ПРОДАЖ': '// LIVE SALES SIMULATOR',
    'Психология коммуникации': 'Real-Time Sales Psychology',
    'в реальном времени': 'Across All Channels',
    'Диалог ведется на основе регламентов вашего бизнеса': 'Dialogue is conducted strictly according to your business playbooks',
    '4 ГОТОВЫХ СЦЕНАРИЯ': '4 LIVE DIALOGUE SCENARIOS',
    '1. Полный цикл (Квалификация + Счет)': '1. Full Deal (Qualification + Invoice)',
    'Знакомство и закрытие на внедрение': 'Introduction and closing the deal',
    '2. Отработка возражения «Дорого»': '2. Price Objection ("Too Expensive")',
    'Отработка «Почему это стоит своих денег»': 'Handling "Why it is worth the price"',
    '3. Instagram Direct (Размер и бронь)': '3. Instagram Direct (Size & Order)',
    'Мгновенная продажа товара в Direct': 'Instant product sale in Direct',
    'в сети • отклик 0.8с': 'online • 0.8s response',
    'Ожидание реакции клиента...': 'Waiting for client response...',
    'Обработка намерения лида (0.8c)...': 'Analyzing lead intent (0.8s)...',
    'Эва печатает ответ...': 'Eva is typing...',
    'Клиент пишет ответ...': 'Client is typing...',
    'сделка закрыта ✓': 'deal closed won ✓',
    'Написать сообщение...': 'Type a message...',

    # amoCRM Simulation
    'Пока менеджеры ленятся заполнять CRM': 'While human reps neglect CRM data entry',
    'AI-сотрудник автоматически': 'AI Agent automatically logs',
    'вносит 100% данных из диалогов': '100% of dialogue data and',
    'и двигает сделку по воронке': 'drives the deal forward',
    'Исраэль Иуда': 'Frank Cowperwood',
    'Фрэнк Каупервуд': 'Frank Cowperwood',
    '#ТЕГИРОВАТЬ': '#TAGGING',
    'Основное': 'General',
    'Сделки': 'Deals',
    'Настроить': 'Settings',
    'Отв-ный': 'Assignee',
    'Егоров Ренат (AI Altai)': 'Renat Egorov (AI Altai)',
    'Раб. тел.': 'Work Phone',
    'валиден ✓': 'verified ✓',
    'Email раб.': 'Work Email',
    'Должность': 'Position',
    'Пользовательское с...': 'Custom status...',
    'КОМПАНИЯ': 'COMPANY',
    'Тестовая компания': 'Test Company Inc.',
    'Бюджет лида': 'Deal Budget',
    'Сфера / Web': 'Industry',
    'Адрес': 'Address',
    'Статус в CRM': 'CRM Status',
    'Анализ переписки...': 'Analyzing dialogue...',
    'Автозаполнение всех полей в CRM': 'Autofill 100% fields in CRM',
    'Автономная работа в CRM:': 'Autonomous CRM execution:',
    'ДВИЖЕНИЕ СДЕЛКИ В AMOCRM': 'PIPELINE FLOW IN CRM',
    'Этапы воронки без зависаний': 'Seamless Funnel Velocity',
    'Заполнение без ошибок': 'Zero data entry errors',
    'НОВЫЙ ЛИД': 'NEW LEAD',
    '409 сделок': '409 deals',
    'КОНТАКТ': 'CONTACT',
    '732 сделки': '732 deals',
    'КВАЛИФИКАЦИЯ': 'QUALIFICATION',
    '235 сделок': '235 deals',
    'КП ОТПРАВЛЕНО': 'PROPOSAL SENT',
    '1 389 сделок': '1,389 deals',
    'УСПЕШНО': 'CLOSED WON',
    '1. Новый лид (Мгновенный захват 0.8с)': '1. New Lead (Instant 0.8s capture)',
    'Лид из WhatsApp, Telegram, сайта или рекламы мгновенно попадает в CRM без потерь.': 'Lead from WhatsApp, Telegram, website or ads is instantly logged into CRM with zero loss.',
    '2. Контакт установлен (Живой диалог)': '2. Contact Made (Live human-like chat)',
    'AI выходит на связь за секунды, задает уточняющие вопросы и удерживает внимание лида.': 'AI responds in seconds, asks clarifying questions, and holds the lead\'s attention.',
    '3. Квалифицирован (ЛПР, бюджет, объем)': '3. Qualified (Decision maker, budget, scope)',
    'ИИ фиксирует должность, компанию, объем закупки и платежеспособность в карточке CRM.': 'AI extracts position, company, order volume, and budget directly into the CRM card.',
    '4. КП отправлено (Согласование и дожим)': '4. Proposal Sent (Objection handling & push)',
    'Автоматический расчет спецификации из прайса, отправка PDF-счета и дожим без уступок.': 'Automated price book calculation, instant PDF invoice, and value-based closing.',
    '5. Успешно реализовано (Оплата)': '5. Closed Won (Payment received)',
    'Чек пробит, транзакция зафиксирована в 1С/банке, сделка переведена в статус «Оплачено».': 'Payment verified, invoice cleared in ERP/bank, and deal stage automatically updated to Paid.',
    'СИНХРОНИЗИРОВАНО': 'SYNCHRONIZED',

    # Cases Section Top
    '// РЕАЛЬНЫЕ КЕЙСЫ': '// REAL CASE STUDIES',
    'Разборы внедрения': 'Implementation Breakdowns',
    'автономного отдела продаж': 'of Autonomous AI Sales',
    '👇 ВЫБЕРИТЕ СФЕРУ ДЛЯ ИЗУЧЕНИЯ:': '👇 SELECT AN INDUSTRY TO EXPLORE:',
    'B2B Опт & Поставки': 'B2B Wholesale & Supply',
    'Металл, комплектующие': 'Industrial, Equipment',
    'Недвижимость & КП': 'Real Estate & Luxury',
    'Девелопмент, ЖК': 'Developments, Land',
    'Автобизнес & Лизинг': 'Automotive & Fleet',
    'Avito, спецтехника': 'Commercial, Trucks',
    'B2B Консалтинг': 'B2B Consulting & Legal',
    'Аудит, сложные услуги': 'Tax, Corporate Advisory',
    'ДЕМОНСТРАЦИЯ СЦЕНАРИЯ': 'SCENARIO DEMO',
    'Шаг 1: Захват & Расчет': 'Step 1: Capture & Quote',
    'Шаг 2: Дожим в Telegram': 'Step 2: Push in Telegram',
    'Шаг 3: Сделка в CRM': 'Step 3: CRM Deal Flow',
    'Оптовый поставщик металлопроката и комплектующих': 'Wholesale supplier of industrial steel and components',
    'Автоматизация расчета спецификаций из 4 000+ позиций и моментальный дожим в Telegram': 'Automating 4,000+ SKU quote calculations and instant closing in Telegram',
    'Было:': 'Before:',
    'Вместо 3–4 дней в Excel': 'Instead of 3–4 days in Excel',
    'Стало с AI:': 'With AI:',
    'РЕЗУЛЬТАТ': 'RESULT',
    'ЧИСТАЯ ВЫРУЧКА С AI': 'NET REVENUE WITH AI',
    'В первый месяц внедрения': 'In the first month of deployment',
    'ВРЕМЯ РАСЧЕТА КП': 'QUOTE TIME',
    '15 СЕКУНД': '15 SECONDS',
    'КОНВЕРСИЯ В ОПЛАТУ': 'CONVERSION RATE',
    'СКОРОСТЬ ДОЖИМА': 'CLOSING SPEED',
    '11 ДНЕЙ': '11 DAYS',
    'В 2.5 раза быстрее цикла сделки': '2.5x faster sales velocity',
    'ОКУПАЕМОСТЬ СИСТЕМЫ': 'SYSTEM ROI',
    'С первой отгрузки металлопроката': 'From the very first bulk shipment',
    'НИША: ОПТОВЫЕ ПОСТАВКИ МЕТАЛЛОПРОКАТА': 'NICHE: B2B INDUSTRIAL SUPPLY',
    'СТЕК: TELEGRAM + 1С + БИТРИКС24': 'STACK: TELEGRAM + 1C/ERP + BITRIX24',
    'ПРИРОСТ МЕСЯЧНОЙ ВЫРУЧКИ': 'MONTHLY REVENUE INCREASE',

    # Calculator & Quotes
    '“ МЫСЛИ ГЛОБАЛЬНО, ДЕЙСТВУЙ ЛОКАЛЬНО': '“ THINK GLOBALLY, ACT LOCALLY',
    '«Мысли глобально, действуй локально»': '“Think globally, act locally”',
    '— Команда Altai': '— Altai Team',
    'Сколько чистой прибыли принесет': 'How Much Net Profit Will',
    'автономный отдел продаж?': 'Autonomous AI Sales Generate?',
    'Входящих заявок в месяц:': 'Inbound leads per month:',
    '100 лидов': '100 leads',
    '3 000 лидов': '3,000 leads',
    'Средний чек сделки:': 'Average deal value:',
    'ЧИСТАЯ ДОПОЛНИТЕЛЬНАЯ ПРИБЫЛЬ В МЕСЯЦ:': 'NET ADDITIONAL PROFIT PER MONTH:',
    'ДОПОЛНИТЕЛЬНАЯ ВЫРУЧКА В ГОД:': 'ADDITIONAL REVENUE PER YEAR:',
    'Зафиксировать результат и запустить AI': 'Lock In Results and Launch AI Pilot',
    '3 дня на настройку': '3 days to deploy',
    'Без увольнения текущего штата': 'Zero disruption to current team',
    'Оплата за результат': 'Performance-based ROI',

    # Recruiter
    'ИНТЕРАКТИВНЫЙ РЕКРУТЕР': 'INTERACTIVE RECRUITER',
    'Ваш сотрудник может быть любым': 'Your AI Employee Can Be Anyone',
    'Кликните на аватар, чтобы изучить резюме': 'Click any avatar to inspect resume',
    '👇 ВЫБЕРИТЕ АВАТАР:': '👇 CHOOSE AVATAR:',
    'РЕЗЮМЕ СОТРУДНИКА': 'AI RESUME',
    'Слушать голос': 'Listen to voice sample',
    'Статус:': 'Status:',
    'Готова к работе': 'Ready to Deploy',
    'Готов к работе': 'Ready to Deploy',
    'Возраст:': 'Age:',
    'Опыт в AI:': 'AI Experience:',
    'Владение:': 'Languages:',
    '7 170 языков': '7,170 languages',
    'Стек:': 'Stack:',
    'О СЕБЕ И КЛЮЧЕВЫЕ КОМПЕТЕНЦИИ': 'ABOUT & CORE COMPETENCIES',
    'Благодаря интеллекту AI знаю любую тему и продукт в совершенстве, поэтому мне не требуется время на адаптацию и обучение.': 'Powered by state-of-the-art AI, I master any company product and sales nuance instantly with zero onboarding curve.',
    'Безупречный женский альт, строгий деловой этикет Ritz-Carlton. Идеально закрывает чеки от 500 000 ₽.': 'Flawless vocal presence, Ritz-Carlton executive etiquette. Expert in closing enterprise deals from $5,000+.',
    'Автономная генерация ответов 0.8с': '0.8s autonomous response time',
    'без скриптовых пауз и зависаний': 'with zero delays or pauses',
    'Идеальная аргументация ценности': 'Bulletproof value defense',
    'без скидок из страха потерять лид': 'without discounting out of fear',
    'Мгновенная интеграция': 'Instant integration',
    'с любой CRM, мессенджерами и 1С': 'with any CRM, messaging apps, and ERP',
    '100% соблюдение регламентов': '100% policy & SLA adherence',
    'без забывчивости и человеческого фактора': 'without human oversight needed',
    'Нанять этого сотрудника': 'Hire This AI Employee',
    'ОТКЛИК: 0.8 СЕК': 'RESPONSE: 0.8 SEC',
    'КОНВЕРСИЯ: +40%': 'CONVERSION: +40%',
    '35 лет': '35 yo',
    '38 лет': '38 yo',
    '29 лет': '29 yo',
    '42 года': '42 yo',
    '31 год': '31 yo',
    '45 лет': '45 yo',
    '27 лет': '27 yo',
    '30 лет': '30 yo',
    '34 года': '34 yo',
    '46 лет': '46 yo',
    'Эва': 'Eva',
    'Алекс': 'Aleks',
    'Дарья': 'Daria',
    'Руслан': 'Ruslan',
    'Мэй': 'Mei',
    'Марк': 'Mark',
    'Амина': 'Amina',
    'Денис': 'Denis',
    'Кенджи': 'Kenji',
    'Елена': 'Elena',

    # Forms & Modals
    'Время убрать человеческий фактор из отдела продаж и забрать упущенную прибыль': 'Time to remove the human factor from your sales team and claim lost revenue',
    'Запустите тестовый пилот на 50 реальных лидах бесплатно': 'Launch a free test pilot on 50 real inbound leads',
    'Развернем AI-продавца под ваш продукт за 24 часа. Без оплаты, без изменения штата, без риска.': 'We will deploy your custom AI sales agent within 24 hours. No upfront payment, no staffing changes, zero risk.',
    'Бесплатный пилот на 50 лидах': 'Free 50-lead live pilot',
    'Готовая интеграция за 24 часа': 'Ready integration within 24h',
    'Договор с гарантией ROI': 'ROI guarantee contract',
    'Ваше имя': 'Your Name',
    'Телефон или Telegram *': 'Phone or Telegram *',
    'Сайт компании или ниша': 'Company website or industry',
    'Запустить бесплатный пилот': 'Launch Free Live Pilot',
    '✓ Заявка принята! Мы свяжемся с вами в течение 15 минут для согласования пилота.': '✓ Request received! We will contact you within 15 minutes to configure your pilot.',
    '🔒 Ваши данные защищены. Мы не передаем контакты третьим лицам.': '🔒 Your data is fully encrypted. We never share contacts with third parties.',
    '🎁 ПОДАРОК ПРИ ПОДКЛЮЧЕНИИ AI-ПРОДАВЦА': '🎁 BONUS GIFT WITH AI SALES DEPLOYMENT',
    'ВЫГОДА 45 000 ₽': 'WORTH $500',
    'Вся база в Excel или Google Таблицах? Наведем четкий порядок': 'All your customer data in Excel or Google Sheets? We organize everything',
    'Если у вас еще нет CRM — не проблема. Мы возьмем на себя всю рутину: перенесем ваши разрозненные таблицы, почистим от дублей, сегментируем контакты и подготовим базу для старта AI-продаж.': 'No CRM yet? No problem. We handle the entire database migration: clean duplicates, segment contacts, and prepare your data for AI sales.',
    'Очистка от дублей': 'Duplicate cleanup',
    'Импорт в CRM': 'Direct CRM import',
    'AI-сегментация': 'AI segmentation',
    'Забрать подарок и перенести базу': 'Claim Gift & Migrate Database',
    '✓ Заявка принята! Мы свяжемся с вами в течение 15 минут для согласования переноса базы.': '✓ Request received! We will contact you within 15 minutes to coordinate migration.',
    '🔒 Конфиденциально • Подписываем NDA перед началом работ': '🔒 Confidential • We sign NDA prior to commencing any work',
    'Начать работу': 'Get Started',

    # JS Currency format
    "coin.textContent = '₽';": "coin.textContent = '$';",
    "cL.textContent = c.toLocaleString('ru-RU') + ' ₽';": "cL.textContent = '$' + c.toLocaleString('en-US');",
    "mV.textContent = month.toLocaleString('ru-RU') + ' ₽';": "mV.textContent = '+$' + month.toLocaleString('en-US');",
    "yV.textContent = year.toLocaleString('ru-RU') + ' ₽';": "yV.textContent = '+$' + year.toLocaleString('en-US');",

    # JS Interactive Branches
    "author: 'Максим (Лид)'": "author: 'Max (Lead)'",
    "text: 'Добрый день! Интересует подключение ИИ-отдела. Как быстро можно настроить под наши услуги?'": "text: 'Good day! Interested in deploying an AI sales department. How fast can it be configured for our services?'",
    "author: 'Эва // Altai Optima'": "author: 'Eva // Altai Optima'",
    "text: 'Максим, приветствую! Меня зовут Эва. Тестовый контур разворачиваем за 24 часа. Вам удобнее текстом или набрать голосом?'": "text: 'Max, hello! My name is Eva. We deploy a pilot environment in 24 hours. Do you prefer messaging or a quick voice call?'",
    "text: 'Давайте текстом, на встрече сейчас.'": "text: 'Let us chat here, I am in a meeting right now.'",
    "text: 'Принято! Система перехватывает лиды за 0.8с, квалифицирует бюджет и сама выставляет счет. Готовы протестировать на 50 входящих лидах?'": "text: 'Understood! The system captures leads in 0.8s, qualifies budget, and issues invoices. Ready to test on 50 real inbound leads?'",
    "text: 'Да, давайте попробуем, отправляйте ссылку.'": "text: 'Yes, let us test it. Please send the link.'",
    "text: 'Формирую защищенный доступ к тестовому стенду. Сделка переведена на этап «Пилот» ✓'": "text: 'Generating secure access to your sandbox. Deal moved to \"Pilot Stage\" ✓'",
    
    "text: 'Видел кнопочных ботов за три копейки. Зачем платить за вашу систему?'": "text: 'I have seen cheap button bots. Why should I invest in your autonomous system?'",
    "text: 'Кнопочные боты теряют 70% клиентов на первом же вопросе не по сценарию. Наша система понимает нюансы бизнеса, не раздает скидки из страха и дожимает сделку на уровне лучшего коммерческого директора.'": "text: 'Simple bots lose 70% of buyers on the very first unscripted query. Our system masters business context, defends margin without discounts, and closes deals like top sales executives.'",
    "text: 'То есть скидку вы мне не дадите?)'": "text: 'So you will not offer me a discount?)'",
    "text: 'Скидка обесценивает ваш результат. Вместо уступок мы даем гарантию сохранения +30% выручки в договоре 🤝'": "text: 'Discounts devalue your results. Instead of compromises, we legally guarantee +30% revenue uplift in our agreement 🤝'",

    "author: 'Анастасия (Direct)'": "author: 'Anastasia (Direct)'",
    "text: 'Добрый день! Подскажите, пожалуйста, сколько стоит данное платье?'": "text: 'Good day! Could you please share the price of this dress?'",
    "text: 'Анастасия, добрый день! Благодарю за обращение в нашу компанию, меня зовут Эва ✨<br><br>Стоимость платья составляет 5 000 рублей.<br><br>На данный момент у нас действует экспресс-доставка по городу с примеркой, а также изделие представлено в онлайн-пространствах.<br><br>Направляю ссылки для вашего удобства:<br>• <strong>Lamoda:</strong> <span class=\"underline decoration-pink-200 font-medium\">lamoda.ru/brand/dress</span><br>• <strong>Ozon:</strong> <span class=\"underline decoration-pink-200 font-medium\">ozon.ru/product/dress</span><br><br>Подсказать вам по наличию вашего размера или оформить заказ с доставкой прямо сейчас?'": "text: 'Anastasia, hello! Thank you for reaching out, my name is Eva ✨<br><br>The dress is $120.<br><br>We offer same-day express delivery with fitting, and it is also available in our boutique collections.<br><br>Here are direct links for your convenience:<br>• <strong>Boutique Store:</strong> <span class=\"underline decoration-pink-200 font-medium\">altai-optima.com/shop</span><br>• <strong>Lookbook:</strong> <span class=\"underline decoration-pink-200 font-medium\">altai-optima.com/catalog</span><br><br>Would you like me to check size availability or book courier delivery for tomorrow?'",
    "text: 'Да, подскажите! На параметры 88-64-92 лучше взять размер S?'": "text: 'Yes please! For measurements 88-64-92, is size S best?'",
    "text: 'Анастасия, под ваши параметры идеально подойдет размер S — посадка будет точной и подчеркнет талию. Забронировать его для вас на доставку курьером на завтра?'": "text: 'Anastasia, size S is a perfect tailored fit for your measurements. Shall I reserve it for courier delivery tomorrow?'",

    # amoCRM simulation live steps
    "phoneEl.textContent = '+7 (999) 834-12-05';": "phoneEl.textContent = '+1 (555) 384-9102';",
    "counterEl.textContent = 'Заполнено 1 из 8 обязательных полей';": "counterEl.textContent = '1 of 8 required fields completed';",
    "emailEl.textContent = 'maxim@prom-holding.ru';": "emailEl.textContent = 'frank@cowperwood-holdings.com';",
    "counterEl.textContent = 'Заполнено 2 из 8 обязательных полей';": "counterEl.textContent = '2 of 8 required fields completed';",
    "posEl.textContent = 'Генеральный директор';": "posEl.textContent = 'Chief Executive Officer';",
    "counterEl.textContent = 'Заполнено 3 из 8 обязательных полей';": "counterEl.textContent = '3 of 8 required fields completed';",
    "budgetEl.textContent = '4 500 000 ₽';": "budgetEl.textContent = '$75,000';",
    "counterEl.textContent = 'Заполнено 4 из 8 обязательных полей';": "counterEl.textContent = '4 of 8 required fields completed';",
    "compEl.textContent = 'ООО «Пром-Холдинг»';": "compEl.textContent = 'Cowperwood Capital Inc.';",
    "counterEl.textContent = 'Заполнено 5 из 8 обязательных полей';": "counterEl.textContent = '5 of 8 required fields completed';",
    "indEl.textContent = 'B2B Производство';": "indEl.textContent = 'B2B Enterprise / Manufacturing';",
    "counterEl.textContent = 'Заполнено 6 из 8 обязательных полей';": "counterEl.textContent = '6 of 8 required fields completed';",
    "cityEl.textContent = 'Москва';": "cityEl.textContent = 'New York';",
    "counterEl.textContent = 'Заполнено 7 из 8 обязательных полей';": "counterEl.textContent = '7 of 8 required fields completed';",
    "КП отправлено • Ждем оплату": "Proposal Sent • Awaiting Payment",
    "Все 8 обязательных полей заполнены на 100%": "All 8 required fields 100% completed",
    "Анализ диалога в переписке...": "Analyzing live chat...",
    "Заполнено 0 из 8 обязательных полей": "0 of 8 required fields completed",

    # Personas
    "name: 'ЭВА'": "name: 'EVA'",
    "role: 'СТАРШИЙ ВИЦЕ-ПРЕЗИДЕНТ ПО ПРОДАЖАМ'": "role: 'SENIOR VICE PRESIDENT OF SALES'",
    "badge: 'ПЕРСОНА: ЭВА'": "badge: 'PERSONA: EVA'",
    "ready: 'Готова приступить мгновенно'": "ready: 'Ready to Deploy Instantly'",
    "title: 'Эва // AI Altai Optima'": "title: 'Eva // AI Altai Optima'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD'": "voiceBadge: 'VOICE: HD SYNTHESIS'",
    "desc: 'Безупречный женский альт, строгий деловой этикет Ritz-Carlton. Идеально закрывает чеки от 500 000 ₽.'": "desc: 'Flawless vocal presence, Ritz-Carlton executive etiquette. Expert in closing enterprise deals from $5,000+.'",

    "name: 'АЛЕКСАНДР СЕМЕНОВ'": "name: 'ALEKSANDER SEMENOV'",
    "role: 'ДИРЕКТОР ПО B2B ПРОДАЖАМ И ОПТУ'": "role: 'DIRECTOR OF B2B SALES & WHOLESALE'",
    "badge: 'ПЕРСОНА: АЛЕКСАНДР'": "badge: 'PERSONA: ALEKSANDER'",
    "ready: 'Готов приступить мгновенно'": "ready: 'Ready to Deploy Instantly'",
    "title: 'Александр // Уверенный баритон'": "title: 'Aleksander // Confident Baritone'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (БАРИТОН)'": "voiceBadge: 'VOICE: HD SYNTHESIS (BARITONE)'",
    "desc: 'Глубокий спокойный мужской баритон. Идеален для оптовой торговли, поставок оборудования, девелопмента и логистики.'": "desc: 'Deep, calm baritone. Ideal for wholesale trade, machinery supply, real estate development, and freight.'",

    "name: 'ДАРЬЯ РОМАНОВА'": "name: 'DARIA ROMANOVA'",
    "role: 'РУКОВОДИТЕЛЬ VIP-КОНСЬЕРЖ СЕРВИСА'": "role: 'HEAD OF VIP CONCIERGE & CARE'",
    "badge: 'ПЕРСОНА: ДАРЬЯ'": "badge: 'PERSONA: DARIA'",
    "title: 'Дарья // Премиальный сервис и забота'": "title: 'Daria // Premium Service & Care'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (СОПРАНО)'": "voiceBadge: 'VOICE: HD SYNTHESIS (SOPRANO)'",
    "desc: 'Эмпатичный, интеллигентный и располагающий голос. Высокая конверсия в премиальной медицине, туризме и сфере услуг.'": "desc: 'Empathetic, articulate, and welcoming tone. Exceptional conversion in luxury healthcare, travel, and premium services.'",

    "name: 'РУСЛАН АЛИЕВ'": "name: 'RUSLAN ALIEV'",
    "role: 'ВЕДУЩИЙ ПЕРЕГОВОРЩИК И СТРАТЕГ'": "role: 'CHIEF NEGOTIATOR & STRATEGIST'",
    "badge: 'ПЕРСОНА: РУСЛАН'": "badge: 'PERSONA: RUSLAN'",
    "title: 'Руслан // Твердые переговоры и опт'": "title: 'Ruslan // Tough Negotiations & Wholesale'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ТЕМБР-ЛИДЕР)'": "voiceBadge: 'VOICE: HD SYNTHESIS (LEADER)'",
    "desc: 'Твердая аргументация, железная позиция по цене без уступок. Идеален для дистрибуции, спецтехники и жестких B2B-переговоров.'": "desc: 'Authoritative value defense with zero price discounting. Ideal for distribution, heavy equipment, and B2B contracts.'",

    "name: 'МЭЙ ЛИН'": "name: 'MEI LIN'",
    "role: 'МЕНЕДЖЕР ПО ВЭД И ТЕХНОЛОГИЯМ'": "role: 'TECH & INTERNATIONAL TRADE MANAGER'",
    "badge: 'ПЕРСОНА: МЭЙ'": "badge: 'PERSONA: MEI'",
    "title: 'Мэй // Международные сделки и Tech'": "title: 'Mei // Global Deals & Tech'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ДЕЛОВОЙ)'": "voiceBadge: 'VOICE: HD SYNTHESIS (BUSINESS)'",
    "desc: 'Структурная, быстрая речь с точностью до цифры. Идеальна для SaaS, IT-решений, импорта из Азии и e-commerce.'": "desc: 'Structured, high-tempo communication with exact metrics. Ideal for SaaS, tech solutions, global supply, and e-commerce.'",

    "name: 'МАРК ШТЕЙН'": "name: 'MARK STEIN'",
    "role: 'КОРПОРАТИВНЫЙ АМБАССАДОР'": "role: 'CORPORATE AMBASSADOR'",
    "badge: 'ПЕРСОНА: МАРК'": "badge: 'PERSONA: MARK'",
    "title: 'Марк // Корпоративные сделки'": "title: 'Mark // Enterprise Deals'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (СТАТУС)'": "voiceBadge: 'VOICE: HD SYNTHESIS (STATUS)'",
    "desc: 'Вызывает моментальное доверие собственников и топ-менеджеров. Специализация: консалтинг, инвестпроекты, банковский сектор.'": "desc: 'Instantly builds credibility with C-level executives. Specialization: advisory, capital projects, and banking.'",

    "name: 'АМИНА КАСЫМОВА'": "name: 'AMINA KASYMOVA'",
    "role: 'ЭКСПЕРТ ПО ЭЛИТНОЙ НЕДВИЖИМОСТИ'": "role: 'LUXURY REAL ESTATE EXPERT'",
    "badge: 'ПЕРСОНА: АМИНА'": "badge: 'PERSONA: AMINA'",
    "title: 'Амина // Деликатный премиум-дожим'": "title: 'Amina // High-Touch Closing'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (БАРХАТ)'": "voiceBadge: 'VOICE: HD SYNTHESIS (VELVET)'",
    "desc: 'Мягкое ведение диалога с тактичным дожимом до закрытия договора. Прекрасно работает в загородной и премиум-недвижимости.'": "desc: 'Polished client guidance with structured follow-through. Exceptional in prime residential and luxury real estate.'",

    "name: 'ДЕНИС ВОЛКОВ'": "name: 'DENIS VOLKOV'",
    "role: 'HIGH-ENERGY СКОРОСТНОЙ КЛОУЗЕР'": "role: 'HIGH-ENERGY SPEED CLOSER'",
    "badge: 'ПЕРСОНА: ДЕНИС'": "badge: 'PERSONA: DENIS'",
    "title: 'Денис // Скоростной захват лидов'": "title: 'Denis // Rapid Lead Capture'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ДИНАМИК)'": "voiceBadge: 'VOICE: HD SYNTHESIS (DYNAMIC)'",
    "desc: 'Динамичный темп речи, моментальная реакция на входящий интерес. Превосходно конвертирует холодный и горячий трафик с рекламы.'": "desc: 'Energetic pacing, instant response to buyer signals. Outperforms in converting both cold and inbound ad traffic.'",

    "name: 'КЕНДЖИ ТАНАКА'": "name: 'KENJI TANAKA'",
    "role: 'ТЕХНИЧЕСКИЙ ЭКСПЕРТ И B2B-ИНЖЕНЕР'": "role: 'TECHNICAL EXPERT & SOLUTIONS ARCHITECT'",
    "badge: 'ПЕРСОНА: КЕНДЖИ'": "badge: 'PERSONA: KENJI'",
    "title: 'Кенджи // Инженерный расчет и B2B'": "title: 'Kenji // Engineering Specs & B2B'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (ВЗВЕШЕННЫЙ)'": "voiceBadge: 'VOICE: HD SYNTHESIS (PRECISION)'",
    "desc: 'Глубокое погружение в ТЗ, сложные спецификации и сметы. Конвертирует технических директоров и инженеров.'": "desc: 'Deep technical comprehension of specifications and quotes. Converts CTOs, chief engineers, and architects.'",

    "name: 'ЕЛЕНА СМИРНОВА'": "name: 'ELENA SMIRNOVA'",
    "role: 'УПРАВЛЯЮЩИЙ ПАРТНЕР ПО ПРОДАЖАМ'": "role: 'MANAGING SALES PARTNER'",
    "badge: 'ПЕРСОНА: ЕЛЕНА'": "badge: 'PERSONA: ELENA'",
    "title: 'Елена // Высокие чеки и доверие'": "title: 'Elena // Enterprise Trust'",
    "voiceBadge: 'ГОЛОС: СИНТЕЗ HD (СТАТУСНЫЙ)'": "voiceBadge: 'VOICE: HD SYNTHESIS (EXECUTIVE)'",
    "desc: 'Солидный статус и безупречный такт. Проводит переговоры на уровне генеральных директоров и акционеров холдингов.'": "desc: 'Executive presence and impeccable poise. Conducts negotiations with holding shareholders and enterprise boards.'",

    # Cases Data
    "companyName: 'ООО «ПромСталь Холдинг»'": "companyName: 'PromSteel Holding LLC'",
    "companyNiche: 'B2B Металлопрокат & Трубная продукция • Оборот 920M ₽/год'": "companyNiche: 'B2B Industrial Steel & Piping • $12M/yr Revenue'",
    "authorName: 'Михаил Воронов'": "authorName: 'Michael Voronov'",
    "authorRole: 'Генеральный директор и основатель'": "authorRole: 'CEO & Founder'",
    "review: '«Раньше менеджеры вручную сводили спецификации по 3–4 дня в Excel, из-за чего 38% горячих заявок уходили к более быстрым конкурентам. После внедрения Altai Optima расчет из 4 000 позиций формируется в 1С за 15 секунд и моментально улетает в Telegram клиенту. В первый же месяц получили +10.4M ₽ чистой выручки.»'": "review: '\"Previously reps took 3–4 days to build Excel quotes manually, losing 38% of hot deals to faster competitors. With Altai Optima, 4,000+ SKU calculations are generated in 15 seconds and instantly delivered via Telegram. In our first month we generated +$140,000 in net revenue.\"\'",
    "nicheTag: 'НИША: B2B ОПТ И СТРОИТЕЛЬНЫЕ ПОСТАВКИ'": "nicheTag: 'NICHE: B2B INDUSTRIAL SUPPLY & MATERIALS'",
    "stackTag: 'СТЕК: БИТРИКС24 + TELEGRAM API + 1С'": "stackTag: 'STACK: BITRIX24 + TELEGRAM API + 1C/ERP'",
    "title: 'Оптовый поставщик металлопроката и комплектующих'": "title: 'Wholesale Supplier of Industrial Steel & Components'",
    "subtitle: 'Автоматизация расчета спецификаций из 4 000+ позиций и моментальный дожим в Telegram'": "subtitle: 'Automated 4,000+ SKU quotes and instant sales follow-up in Telegram'",
    "revenue: '+10.4M ₽'": "revenue: '+$140,000'",
    "revenueNote: 'В ПЕРВЫЙ МЕСЯЦ ВНЕДРЕНИЯ'": "revenueNote: 'IN THE FIRST MONTH'",
    "label: 'СКОРОСТЬ РАСЧЕТА', val: '15 СЕКУНД', sub: 'Вместо 3–4 дней в Excel'": "label: 'QUOTE TIME', val: '15 SECONDS', sub: 'Instead of 3–4 days in Excel'",
    "label: 'ЦИКЛ СДЕЛКИ', val: 'В 8 РАЗ БЫСТРЕЕ', sub: '1 день вместо 8 дней'": "label: 'SALES VELOCITY', val: '8X FASTER', sub: '1 day instead of 8 days'",
    "label: 'КОНВЕРСИЯ В ОПЛАТУ', val: '+34%', sub: 'За счет скорости КП'": "label: 'CONVERSION RATE', val: '+34%', sub: 'Driven by instant quotes'",
    "label: 'ОКУПАЕМОСТЬ AI', val: '11 ДНЕЙ', sub: 'С первых 4 закрытых сделок'": "label: 'SYSTEM ROI', val: '11 DAYS', sub: 'From the first 4 closed deals'",
    "summaryA: 'Сметы собирались <strong>3–4 дня</strong> в Excel • <strong>38% клиентов уходили</strong> к конкурентам • Менеджеры перегружены рутиной'": "summaryA: 'Quotes took <strong>3–4 days</strong> in Excel • <strong>38% of leads lost</strong> to competitors • Reps swamped by routine'",
    "summaryB: 'КП формируется <strong>за 15 секунд</strong> • Сделка в <strong>8 раз быстрее</strong> • <strong>+10.4M ₽ в месяц</strong> чистой выручки'": "summaryB: 'Quotes ready <strong>in 15 seconds</strong> • Deals closed <strong>8x faster</strong> • <strong>+$140,000/mo</strong> net profit'",
    "leftTitle: 'Telegram Desktop • Заказчик @metall_stroy'": "leftTitle: 'Telegram Desktop • Client @metall_stroy'",
    "Чаты": "Chats",
    "МеталлСтрой Холдинг (Алексей)": "MetalBuild Holding (Alex)",
    "Алексей (Закупки)": "Alex (Procurement)",
    "«Счет передал в бухгалтерию на оплату, резервируйте 45 тонн.»": "\"Sent invoice to accounting for payment, please reserve 45 tons.\"",
    "rightTitle: 'Битрикс24 CRM • Сделка #4892'": "rightTitle: 'Bitrix24 CRM • Deal #4892'",
    "rightBadge: 'БИТРИКС24 + 1С'": "rightBadge: 'BITRIX24 + ERP'",
    "искать сделку, 1С...": "search deal, ERP...",
    "Лиды": "Leads",
    "Товары и Склады": "Inventory & Stock",
    "Клиенты": "Clients",
    "Интеграция 1С": "ERP Integration",
    "+ СОЗДАТЬ": "+ CREATE",
    "Сделки в работе": "Active Deals",
    "01. Заявка": "01. Inquiry",
    "02. Расчет 1С": "02. ERP Quote",
    "03. Счет": "03. Invoice",
    "04. Оплата": "04. Payment",
    "Сделка #4892: ООО \"МеталлСтрой Холдинг\"": "Deal #4892: MetalBuild Holding LLC",
    "Воронка: Оптовые поставки металлопроката": "Pipeline: Wholesale Industrial Supply",
    "СЧЕТ ВЫСТАВЛЕН": "INVOICE ISSUED",
    "СУММА СДЕЛКИ:": "DEAL VALUE:",
    "МАРЖА (24.8%):": "MARGIN (24.8%):",
    "ОТВЕТСТВЕННЫЙ:": "ASSIGNEE:",
    "ИСТОЧНИК:": "SOURCE:",
    "1С:Управление торговлей v11.5": "ERP Enterprise Inventory v11.5",
    "Складской резерв ✓": "Stock Reserved ✓",
    "• Арматура А500С 12мм (45 т):": "• Rebar A500C 12mm (45 t):",
    "Склад Подольск (Резерв)": "Central Warehouse (Reserved)",
    "• Балка 20Б1 (18 т):": "• Beam 20B1 (18 t):",
    "Склад Чехов (Резерв)": "North Depot (Reserved)",
    "📞 Звонок": "📞 Call",
    "✉️ Письмо": "✉️ Email",
    "💬 Чат": "💬 Chat",
    "15 сек автосчет": "15s auto-quote",

    # Case 2: Real Estate
    "companyName: 'Девелоперская группа «Skyline Estate»'": "companyName: 'Skyline Estate Development Group'",
    "companyNiche: 'Загородные поселки & Клубные резиденции • Оборот 1.4B ₽/год'": "companyNiche: 'Luxury Estates & Private Residences • $18M/yr Revenue'",
    "authorName: 'Екатерина Белова'": "authorName: 'Ekaterina Belova'",
    "authorRole: 'Коммерческий директор девелопера'": "authorRole: 'Chief Commercial Officer'",
    "review: '«База из 3 800 старых лидов просто лежала мертвым грузом — брокеры не успевали их прозванивать. AI-ассистент за один вечер поднял контакты в WhatsApp, выявил реальный интерес и назначил 42 показа на объекте. Система полностью окупилась с первой же комиссии загородного дома.»'": "review: '\"A database of 3,800 old leads was sitting dormant because brokers lacked time to call. The AI assistant re-engaged them in WhatsApp overnight, qualified intent, and booked 42 property viewings. The system paid for itself with our first estate sale.\"\'",
    "nicheTag: 'НИША: НЕДВИЖИМОСТЬ & ДЕВЕЛОПМЕНТ (ЖК И КП)'": "nicheTag: 'NICHE: REAL ESTATE & LUXURY DEVELOPMENTS'",
    "stackTag: 'СТЕК: VOICE AI + AMOCRM + WHATSAPP'": "stackTag: 'STACK: VOICE AI + AMOCRM + WHATSAPP'",
    "title: 'Федеральный девелопер премиальных коттеджных поселков'": "title: 'Premier Luxury Real Estate Developer'",
    "subtitle: 'Реактивация 3 800 спящих лидов из архива CRM и автоматическая запись на просмотры'": "subtitle: 'Reactivating 3,800 dormant CRM leads and booking automated site viewings'",
    "revenue: '+6.8M ₽'": "revenue: '+$90,000'",
    "revenueNote: 'С АРХИВНОЙ БАЗЫ ЗА 30 ДНЕЙ'": "revenueNote: 'FROM DORMANT BASE IN 30 DAYS'",
    "label: 'СКОРОСТЬ ОБЗВОНА', val: '48 ЧАСОВ', sub: 'На полный обзвон 3 800 контактов'": "label: 'CALL SPEED', val: '48 HOURS', sub: 'To process 3,800 contacts'",
    "label: 'РЕАКТИВАЦИЯ БАЗЫ', val: '41% ВЕРНУЛИСЬ', sub: '1 558 клиентов вернулись в воронку'": "label: 'REACTIVATION RATE', val: '41% RE-ENGAGED', sub: '1,558 leads returned to pipeline'",
    "label: 'ВЫРУЧКА С АРХИВА', val: '+6.8M ₽', sub: 'Прямая выручка с закрытых сделок'": "label: 'REVENUE GENERATED', val: '+$90,000', sub: 'Direct from closed sales'",
    "label: 'ОКУПАЕМОСТЬ AI', val: 'СО 2-Й СДЕЛКИ', sub: 'Полный возврат инвестиций'": "label: 'SYSTEM ROI', val: 'WITH 2ND DEAL', sub: '100% investment payback'",
    "summaryA: 'В архиве висело <strong>3 800 спящих лидов</strong> • Менеджеры саботировали звонки • Бюджет на рекламу рос на 30%'": "summaryA: 'Archive held <strong>3,800 dormant leads</strong> • Reps postponed cold calls • Ad spend climbed 30%'",
    "summaryB: 'Voice AI обзвонил базу за <strong>48 часов</strong> • <strong>1 558 лидов реактивировано</strong> • <strong>+6.8M ₽ чистой прибыли</strong>'": "summaryB: 'Voice AI contacted base in <strong>48 hours</strong> • <strong>1,558 leads re-engaged</strong> • <strong>+$90,000 net profit</strong>'",
    "leftTitle: 'WhatsApp & Voice AI • Диалог с клиентом'": "leftTitle: 'WhatsApp & Voice AI • Client Dialogue'",
    "Михаил Александрович (КП Резиденция)": "Michael A. (Forest Residence)",
    "в сети • WhatsApp Business": "online • WhatsApp Business",
    "Запись звонка: Voice AI Altai Optima": "Call Recording: Voice AI Altai Optima",
    "РАСПОЗНАНО 99.4%": "RECOGNITION 99.4%",
    "Слушать": "Listen",
    "Воспроизведение...": "Playing...",
    "<div><strong class=\"text-sky-900\">AI:</strong> «Михаил, добрый день! Открыли продажи 2-й очереди КП \"Лесная Резиденция\" с выгодой 12%. Отправляю генплан в WhatsApp?»</div>": "<div><strong class=\"text-sky-900\">AI:</strong> \"Hello Michael! We just launched Phase 2 sales at Forest Residence with a 12% preferred rate. Shall I share the master plan via WhatsApp?\"</div>",
    "<div><strong class=\"text-slate-950\">Клиент:</strong> «Да, скиньте в WhatsApp. Запишите на показ в субботу в 12:00.»</div>": "<div><strong class=\"text-slate-950\">Client:</strong> \"Yes, please send it to WhatsApp. Book me in for a viewing this Saturday at 12:00.\"</div>",
    "«Михаил, закрепил за вами просмотр коттеджа: <strong>Суббота, 12:00</strong>. Персональный пропуск на КП оформил, генплан и планировки 2-й очереди прикрепил ниже 📍»": "\"Michael, your villa viewing is confirmed for: <strong>Saturday, 12:00</strong>. Your private gate pass is issued, and Phase 2 floor plans are attached below 📍\"",
    "Генплан_Лесная_Резиденция_2очередь.pdf": "MasterPlan_Forest_Residence_Phase2.pdf",
    "4.8 MB • Коттедж 280 м²": "4.8 MB • Villa 280 m²",
    "Сообщение...": "Message...",
    "rightTitle: 'amoCRM • Карточка лида #74109'": "rightTitle: 'amoCRM • Lead Card #74109'",
    "Воронка: КП \"Лесная Резиденция\"": "Pipeline: Forest Residence Estates",
    "01. Архив (3 800)": "01. Archive (3,800)",
    "03. Просмотр Сб": "03. Viewing Sat",
    "04. Бронь/ДКП": "04. Reservation/Contract",
    "Сделка #74109: Михаил (Архивная база)": "Deal #74109: Michael (Archive)",
    "Автоназначение слота показа": "Automated viewing slot booking",
    "ПРОСМОТР НАЗНАЧЕН": "VIEWING BOOKED",
    "БЮДЖЕТ ПОКУПКИ:": "PURCHASE BUDGET:",
    "ДАТА ПОКАЗА:": "VIEWING DATE:",
    "Суббота, 12:00": "Saturday, 12:00",
    "ВЫБРАННЫЙ ОБЪЕКТ:": "SELECTED PROPERTY:",
    "КП \"Лесная Резиденция\", Участок №14, Коттедж 280 м²": "Forest Residence, Plot #14, Villa 280 m²",
    "#РЕАКТИВАЦИЯ_41%": "#REACTIVATION_41%",
    "#WHATSAPP_ГЕНПЛАН": "#WHATSAPP_MASTERPLAN",
    "⚡ Итог: спящий контакт из 3 800 архива реактивирован за 48 сек разговора робота.": "⚡ Outcome: Dormant lead from 3,800 database re-engaged in a 48s AI dialogue.",

    # Case 3: Auto
    "companyName: 'Дилерский центр «ТрансАвто СпецТехника»'": "companyName: 'TransAuto Commercial Fleet Dealership'",
    "companyNiche: 'Тягачи Sitrak, спецтехника & коммерческий лизинг • Оборот 2.1B ₽/год'": "companyNiche: 'Sitrak Trucks, Heavy Equipment & Fleet Leasing • $28M/yr Revenue'",
    "authorName: 'Денис Самойлов'": "authorName: 'Denis Samoilov'",
    "authorRole: 'Собственник сети дилерских центров'": "authorRole: 'Dealership Network Owner'",
    "review: '«45% обращений с Avito падали ночью и на выходных, когда отдел продаж спал. Клиенты успевали оставить заявки у пяти других дилеров. Робот отвечает за 1.2 секунды, считает лизинг через 1С и записывает на тест-драйв на площадку. Это дало нам +8.2M ₽ дополнительных продаж в месяц.»'": "review: '\"45% of inbound inquiries came at night and on weekends when reps were asleep. Clients would reach out to 5 competitors. The AI responds in 1.2s, calculates lease terms, and books on-site test drives. This brought +$110,000 in additional sales monthly.\"\'",
    "nicheTag: 'НИША: АВТОБИЗНЕС, СПЕЦТЕХНИКА & ЛИЗИНГ'": "nicheTag: 'NICHE: AUTOMOTIVE, FLEET & LEASING'",
    "stackTag: 'СТЕК: AVITO ЧАТ + WHATSAPP API + AMOCRM'": "stackTag: 'STACK: LIVE CHAT + WHATSAPP API + AMOCRM'",
    "title: 'Дилер коммерческой техники и грузовых авто'": "title: 'Commercial Fleet & Heavy Truck Dealership'",
    "subtitle: 'Круглосуточный захват заявок с Avito, подбор спецтехники и моментальный расчет лизинга'": "subtitle: '24/7 lead capture, vehicle configuration, and instant lease calculation'",
    "revenue: '+8.2M ₽'": "revenue: '+$110,000'",
    "revenueNote: 'ДОПОЛНИТЕЛЬНАЯ ВЫРУЧКА В МЕСЯЦ'": "revenueNote: 'ADDITIONAL REVENUE PER MONTH'",
    "label: 'ВРЕМЯ ОТКЛИКА', val: '1.2 СЕКУНДЫ', sub: 'В ночные часы и выходные'": "label: 'RESPONSE TIME', val: '1.2 SECONDS', sub: 'During nights & weekends'",
    "label: 'ДОХОДИМОСТЬ НА ТЕСТ', val: '+42%', sub: 'Рост конверсии в осмотр техники'": "label: 'TEST DRIVE SHOWUP', val: '+42%', sub: 'Higher on-site visit rate'",
    "label: 'КОНВЕРСИЯ В ДОГОВОР', val: '+28%', sub: 'Из холодного чата в сделку'": "label: 'DEAL CONVERSION', val: '+28%', sub: 'From cold chat to contract'",
    "label: 'ОКУПАЕМОСТЬ AI', val: '14 ДНЕЙ', sub: 'С первых двух проданных тягачей'": "label: 'SYSTEM ROI', val: '14 DAYS', sub: 'With first 2 trucks sold'",
    "summaryA: '<strong>45% заявок с Avito</strong> приходили ночью и сгорали • Менеджеры тратили до 40 мин на сбор параметров лизинга'": "summaryA: '<strong>45% of inquiries</strong> arrived at night • Reps spent 40 min assembling lease quotes'",
    "summaryB: 'Отклик <strong>1.2 секунды 24/7</strong> • Авторасчет лизинга • <strong>+8.2M ₽ доп. продаж техники</strong>'": "summaryB: 'Response in <strong>1.2 seconds 24/7</strong> • Automated lease calculation • <strong>+$110,000/mo extra sales</strong>'",
    "leftTitle: 'Avito Сообщения • Sitrak C7H Тягач'": "leftTitle: 'Commercial Chat • Heavy Truck Sitrak C7H'",
    "leftBadge: 'AVITO API • 23:40 (НОЧЬ)'": "leftBadge: 'LIVE CHAT API • 23:40 (NIGHT)'",
    "ООО \"ТрансЛогистик\" (Покупатель)": "TransLogistics Inc. (Buyer)",
    "в сети • Avito Профиль верифицирован ✓": "online • Verified Business Profile ✓",
    "Седельный тягач Sitrak C7H 4x2 Luxury (480 л.с.)": "Heavy Prime Mover Sitrak C7H 4x2 Luxury (480 hp)",
    "14 800 000 ₽</strong> • В наличии 4 шт. с ЭПТС": "$195,000</strong> • 4 units ready in stock",
    "«Седельный тягач Sitrak C7H в наличии? Какой аванс и ежемесячный платеж по лизингу на 3 года?»": "\"Is the Sitrak C7H truck in stock? What is the down payment and monthly lease on a 3-year term?\"",
    "23:40:05 (Ночь)": "23:40:05 (Night)",
    "AI Дилер Altai Optima": "AI Dealer Altai Optima",
    "1.2 сек отклик ✓": "1.2s response ✓",
    "«В наличии 4 тягача 2024 г. на стоянке Север. При авансе 15% (2 220 000 ₽) платеж: <strong>218 000 ₽/мес</strong> с субсидией. Забронировать показ на площадке завтра в 11:00?»": "\"We have 4 units (2024 model) at North Depot. With 15% down ($29,250), payment is: <strong>$2,850/mo</strong>. Shall I book an on-site inspection tomorrow at 11:00?\"",
    "23:40:07 • ✓✓ Доставлено": "23:40:07 • ✓✓ Delivered",
    "«Да, бронируйте на 11:00, приеду с водителем и реквизитами.»": "\"Yes, book it for 11:00. I will arrive with my fleet manager.\"",
    "Где посмотреть?": "Location?",
    "График лизинга": "Lease terms",
    "В наличии?": "In stock?",
    "rightTitle: 'amoCRM • Ночной лид и бронь техники'": "rightTitle: 'amoCRM • Night Lead & Fleet Booking'",
    "rightBadge: 'AMOCRM + 1С ЛИЗИНГ'": "rightBadge: 'AMOCRM + LEASING ERP'",
    "Воронка: Тягачи и Спецтехника в лизинг": "Pipeline: Commercial Trucks & Fleet Leasing",
    "БРОНЬ НА ТЕСТ": "TEST DRIVE RESERVED",
    "01. Avito 23:40 ✓": "01. Inquiry 23:40 ✓",
    "02. Лизинг 1С ✓": "02. Lease Calc ✓",
    "03. Бронь 11:00": "03. Test 11:00",
    "04. Договор": "04. Contract",
    "СТОИМОСТЬ ТЯГАЧА:": "TRUCK VALUE:",
    "АВАНС (15%):": "DOWN PAYMENT (15%):",
    "ПЛАТЕЖ ПО ЛИЗИНГУ:": "LEASE PAYMENT:",
    "218 000 ₽ / мес (36 мес)": "$2,850 / mo (36 mo)",
    "ДАТА ВИЗИТА:": "VISIT DATE:",
    "Завтра, 11:00": "Tomorrow, 11:00",
    "1С:Лизинг • Автоматический скоринг": "ERP Leasing • Automated Scoring",
    "Одобрено ✓": "Approved ✓",
    "Локация: Стоянка Север (бокс №4) • Менеджер площадки уведомлен в Telegram.": "Location: North Depot (Bay #4) • Fleet manager notified via Telegram.",

    # Case 4: Consulting
    "companyName: 'Юридическое бюро «Вершинин & Партнеры»'": "companyName: 'Vershinin & Partners Legal Advisory'",
    "companyNiche: 'Налоговый консалтинг & Аудит холдингов • Оборот 450M ₽/год'": "companyNiche: 'Tax Advisory & Corporate Audit • $6M/yr Revenue'",
    "authorName: 'Роман Вершинин'": "authorName: 'Roman Vershinin'",
    "authorRole: 'Управляющий партнер и CEO'": "authorRole: 'Managing Partner & CEO'",
    "review: '«Партнеры с высоким чеком тратили до 15 часов в неделю на пустые квалификационные созвоны. AI проводит интеллектуальный скоринг по 12 критериям за 20 секунд прямо в мессенджере и ставит в Google Calendar только целевых клиентов с крупным оборотом. Время закрытия сделки сократилось в разы.»'": "review: '\"Senior partners spent 15 hours a week on unqualified discovery calls. The AI scores leads across 12 criteria in 20s and books only high-revenue qualified accounts into Google Calendar. Our closing velocity doubled.\"\'",
    "nicheTag: 'НИША: B2B УСЛУГИ, КОНСАЛТИНГ & АУДИТ'": "nicheTag: 'NICHE: B2B ADVISORY, AUDIT & LEGAL'",
    "stackTag: 'СТЕК: TELEGRAM BOT + AMOCRM + CALENDAR AI'": "stackTag: 'STACK: TELEGRAM BOT + AMOCRM + CALENDAR AI'",
    "title: 'Юридический консалтинг и налоговый аудит бизнеса'": "title: 'Corporate Legal Advisory & Tax Audit'",
    "subtitle: 'Интеллектуальный скоринг входящих заявок и автоматическая запись к экспертам'": "subtitle: 'Intelligent lead qualification and automated partner meeting scheduling'",
    "revenue: '+4.6M ₽'": "revenue: '+$60,000'",
    "label: 'ВРЕМЯ ДО ВСТРЕЧИ', val: '4 ЧАСА', sub: 'Вместо 7 дней до первой встречи'": "label: 'MEETING VELOCITY', val: '4 HOURS', sub: 'Instead of 7-day wait'",
    "label: 'СРЕДНИЙ ЧЕК', val: '+35%', sub: 'За счет точной квалификации'": "label: 'AVERAGE DEAL SIZE', val: '+35%', sub: 'Due to exact qualification'",
    "label: 'РУТИНА ЭКСПЕРТОВ', val: '0 МИНУТ', sub: 'На нецелевые первичные звонки'": "label: 'PARTNER DISCOVERY', val: '0 MINUTES', sub: 'On unqualified calls'",
    "label: 'ОКУПАЕМОСТЬ AI', val: '9 ДНЕЙ', sub: 'С первого закрытого договора аудита'": "label: 'SYSTEM ROI', val: '9 DAYS', sub: 'With first signed audit contract'",
    "summaryA: 'Партнеры тратили <strong>15 часов/нед</strong> на нецелевых клиентов • Долгий цикл согласования слотов (5–7 дней)'": "summaryA: 'Partners spent <strong>15 hrs/wk</strong> on bad leads • Slot scheduling took 5–7 days'",
    "summaryB: 'AI-скоринг 12 параметров • <strong>Время до Zoom: 4 часа</strong> • <strong>+4.6M ₽ выручки</strong>'": "summaryB: '12-point AI scoring • <strong>Time to Zoom: 4 hours</strong> • <strong>+$60,000 net profit</strong>'",
    "leftTitle: 'Instagram Direct & Telegram • Скоринг лида'": "leftTitle: 'Direct & Telegram • Lead Qualification'",
    "leftBadge: 'DIRECT + CALENDAR AI'": "leftBadge: 'DIRECT + CALENDAR AI'",
    "roman_invest_group (Роман В.)": "roman_invest_group (Roman V.)",
    "Собственник • Оборот 800M • В сети": "Owner • Revenue $10M+ • Online",
    "«Нужен налоговый аудит группы компаний (холдинг 3 юрлица, оборот 800 млн) перед реструктуризацией. Кто ведет такие проекты?»": "\"We require a corporate tax audit for a 3-entity holding company ($10M+ revenue) prior to restructuring. Who leads these engagements?\"",
    "AI Altai Optima (Скоринг 12/12)": "AI Altai Optima (Scoring 12/12)",
    "15 сек ✓": "15 sec ✓",
    "«Здравствуйте, Роман! Проекты с оборотом от 500 млн ведет лично управляющий партнер. Провел экспресс-скоринг: подходит <strong>четверг в 15:00</strong> для конфиденциального Zoom-разбора?»": "\"Hello Roman! Engagements of this scale are personally led by our Managing Partner. I have conducted discovery scoring: is <strong>Thursday at 15:00</strong> suitable for a confidential Zoom session?\"",
    "📅 Zoom: Налоговый аудит холдинга": "📅 Zoom: Holding Corporate Tax Audit",
    "СЛОТ ПОДТВЕРЖДЕН": "SLOT CONFIRMED",
    "Четверг, 15:00 – 15:45 • Управляющий партнер • Бриф сформирован": "Thursday, 15:00 – 15:45 • Managing Partner • Brief Prepared",
    "16:20:25 • ✓✓ Прочитано": "16:20:25 • ✓✓ Read",
    "«Подтверждаю четверг 15:00. Жду ссылку на Zoom и бриф.»": "\"Confirming Thursday 15:00. Looking forward to the Zoom link and brief.\"",
    "rightTitle: 'amoCRM + Google Calendar • Сделка #11084'": "rightTitle: 'amoCRM + Google Calendar • Deal #11084'",
    "rightBadge: 'AMOCRM + GOOGLE CALENDAR'": "rightBadge: 'AMOCRM + GOOGLE CALENDAR'",
    "Воронка: Юридический консалтинг": "Pipeline: Corporate Legal Advisory",
    "ZOOM НАЗНАЧЕН": "ZOOM CONFIRMED",
    "01. Direct ✓": "01. Direct ✓",
    "02. Скоринг 12/12 ✓": "02. Scoring 12/12 ✓",
    "03. Zoom Чт 15:00": "03. Zoom Thu 15:00",
    "04. Договор 750k": "04. Contract $10k",
    "ЧЕК ПРОЕКТА:": "PROJECT VALUE:",
    "СКОРИНГ AI:": "AI SCORING:",
    "12 из 12 параметров": "12 of 12 criteria",
    "ОБОРОТ БИЗНЕСА:": "ANNUAL REVENUE:",
    "800 000 000 ₽ (Холдинг)": "$10,000,000+ (Holding)",
    "СЛОТ CALENDAR:": "CALENDAR SLOT:",
    "Чт, 15:00 – 15:45": "Thu, 15:00 – 15:45",
    "Синхронизировано ✓": "Synchronized ✓",
    "Ссылка Zoom: <span class=\"font-mono text-sky-700 font-bold\">zoom.us/j/94821034...</span> • Бриф рисков отправлен в календарь партнера.": "Zoom Link: <span class=\"font-mono text-sky-700 font-bold\">zoom.us/j/94821034...</span> • Risk brief delivered to partner calendar.",

    # Form interactive states
    "submitBtn.innerHTML = '<span>Заявка отправляется...</span>';": "submitBtn.innerHTML = '<span>Submitting request...</span>';",
    "submitBtn.innerHTML = '<span class=\"font-bold tracking-wide\">ОБСУДИТЬ ДЕТАЛИ ПРОЕКТА</span><span class=\"btn-optic-arrow\">→</span>';": "submitBtn.innerHTML = '<span class=\"font-bold tracking-wide\">DISCUSS PROJECT DETAILS</span><span class=\"btn-optic-arrow\">→</span>';",
}

# Apply EN
en_res = ru_html
for k, v in en_dict.items():
    en_res = en_res.replace(k, v)

# Strip Cyrillic in comments for EN
en_res = re.sub(r'/\*[^\n]*?[\u0400-\u04FF]+[^\n]*?\*/', '', en_res)
en_res = re.sub(r'<!--[^\n]*?[\u0400-\u04FF]+[^\n]*?-->', '', en_res)
en_res = re.sub(r'//[^\n]*?[\u0400-\u04FF]+', '', en_res)

with open('en.html', 'w', encoding='utf-8') as f:
    f.write(en_res)

print("en.html built.")
