# -*- coding: utf-8 -*-
import sys

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# ==========================================
# 1. GENERATE ENGLISH VERSION (en.html)
# ==========================================
en = html

# Replace HTML tag & Meta Title
en = en.replace('<html lang="ru"', '<html lang="en"')
en = en.replace('<title>Altai Optima — Autonomous AI Business Architecture</title>', '<title>Altai Optima — Autonomous AI Sales Architecture</title>')

# Switcher active states
en = en.replace('<span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">RU</span>\n          <a href="en.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">EN</a>',
                '<a href="index.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">RU</a>\n          <span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">EN</span>')
en = en.replace('<span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">RU</span>\n            <a href="en.html" class="px-2 py-0.5 rounded-full hover:text-white transition">EN</a>',
                '<a href="index.html" class="px-2 py-0.5 rounded-full hover:text-white transition">RU</a>\n            <span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">EN</span>')
en = en.replace('<span class="px-3 py-1 rounded-full bg-sky-600 text-white">RU</span>\n        <a href="en.html" class="px-3 py-1 rounded-full bg-slate-100 text-slate-700 hover:bg-sky-50">EN</a>',
                '<a href="index.html" class="px-3 py-1 rounded-full bg-slate-100 text-slate-700 hover:bg-sky-50">RU</a>\n        <span class="px-3 py-1 rounded-full bg-sky-600 text-white">EN</span>')

# Sticky Nav items
en = en.replace('>КЕЙСЫ<', '>CASES<')
en = en.replace('>КАЛЬКУЛЯТОР<', '>CALCULATOR<')
en = en.replace('>АРХИТЕКТУРА<', '>ARCHITECTURE<')
en = en.replace('>РЕЗЮМЕ<', '>RESUME<')
en = en.replace('>РЕЗЮМЕ СОТРУДНИКА<', '>EMPLOYEE RESUME<')
en = en.replace('>ТЕСТОВЫЙ ЗАПУСК<', '>TEST PILOT<')
en = en.replace('>ТЕСТ<', '>TEST<')
en = en.replace('>ПОЛУЧИТЬ ПОДАРОК И ТЕСТ<', '>GET BONUS & PILOT<')

# Hero Header and Top content
en = en.replace('Добрый день. Меня зовут Эва, как могу вам помочь?', 'Good day! I am Eva, how can I assist your business today?')
en = en.replace('Тестовый запуск', 'Test Pilot')
en = en.replace('АВТОНОМНЫЙ', 'AUTONOMOUS')
en = en.replace('AI-ОТДЕЛ ПРОДАЖ', 'AI SALES DEPARTMENT')
en = en.replace('Пока наемный персонал теряет прибыль компании, искусственный интеллект конвертирует каждый контакт в сделку', 'While human reps lose company profits, artificial intelligence converts every lead into a closed deal')
en = en.replace('Посмотреть выгоду', 'Calculate Revenue')
en = en.replace('100% ВНИМАНИЯ', '100% ATTENTION')
en = en.replace(' К КАЖДОМУ КЛИЕНТУ', ' TO EVERY CLIENT')
en = en.replace('Скролл вниз', 'Scroll Down')

# Points of revenue loss
en = en.replace('СКОЛЬКО ДЕНЕГ ВЫ ТЕРЯЕТЕ,', 'HOW MUCH REVENUE DO YOU LOSE,')
en = en.replace('ПОКА МЕНЕДЖЕР ТОРМОЗИТ?', 'WHILE SALES REPS DELAY?')
en = en.replace('// ПРАВИЛО 3-Х СЕКУНД В B2B И B2C', '// THE 3-SECOND RULE IN MODERN SALES')
en = en.replace('СЛИВ КОНВЕРСИИ', 'CONVERSION DROP')
en = en.replace('ОЖИДАНИЕ 2 ЧАСА', '2 HOUR WAIT')
en = en.replace('Кофе ценой в сделку', 'A Coffee That Costs a Deal')
en = en.replace('Горячая заявка остывает, пока сотрудник раскачивается с утра. Лид теряет интерес и при звонке сухо бросает: спасибо, уже неактуально.', 'A hot lead goes cold while a sales rep gets ready for the day. The client loses interest and hangs up: "Thanks, already bought elsewhere."')
en = en.replace('УТЕЧКА МАРЖИ', 'MARGIN LEAK')
en = en.replace('ПЕРЕГОВОРЫ', 'NEGOTIATIONS')
en = en.replace('Скидка из слабости', 'Discounts from Weakness')
en = en.replace('Сотрудник пугается возражения дорого и раздает скидки за счет вашей прибыли, вместо аргументации ценности и удержания полной маржи.', 'The employee fears price objections and gives away unapproved discounts from your profit instead of defending product value and margin.')
en = en.replace('А МОЖЕТЕ ПОЛУЧАТЬ...', 'OR YOU COULD BE EARNING...')

# Manifesto section
en = en.replace('+30% К ВЫРУЧКЕ', '+30% NET REVENUE')
en = en.replace('Оптимизируем каждый этап вашей воронки и', 'We optimize every stage of your sales funnel and')
en = en.replace('выжимаем максимум чистой прибыли из входящего потока', 'extract maximum net profit from every incoming client')
en = en.replace('Мгновенный захват горячего клиента', 'Instant Capture of High-Intent Leads')
en = en.replace('СЕКУНДЫ', 'SECONDS')
en = en.replace('ВРЕМЯ ОТКЛИКА 24/7', '24/7 RESPONSE SPEED')
en = en.replace('Захват лида за 0.8 секунды', '0.8 second lead capture')
en = en.replace('Пока конкуренты открывают CRM, ваш AI уже презентовал продукт и выставил счет', 'While competitors open their CRM, your AI has already presented the product and sent an invoice')

# Solution Bento cards
en = en.replace('// АРХИТЕКТУРА СИСТЕМЫ', '// SYSTEM ARCHITECTURE')
en = en.replace('Четыре контура автономных продаж', 'Four Pillars of Autonomous Sales')
en = en.replace('ГОЛОСОВОЙ AI', 'VOICE AI')
en = en.replace('Живая речь эксперта', 'Human-Like Expert Voice')
en = en.replace('Собеседник слышит уверенного менеджера с безупречной дикцией.', 'The caller hears a confident, articulate sales manager.')
en = en.replace('AI-продавец мгновенно считывает микропаузы,', 'AI senses speech micro-pauses in real time,')
en = en.replace('снимает возражения и ведет коммуникацию человеческим голосом и подачей', 'resolves objections and drives conversation with flawless human tone and pacing')
en = en.replace('Естественные интонации и контекстная память', 'Natural intonations & persistent memory')
en = en.replace('100% фокус на продаже', '100% focused on closing')

en = en.replace('ВСЕ МЕССЕНДЖЕРЫ', 'OMNICHANNEL MESSAGING')
en = en.replace('Мгновенный ответ в любом удобном для клиента мессенджере', 'Instant real-time responses across all client messaging channels')
en = en.replace('КАНАЛЫ СВЯЗИ 24/7/365:', '24/7/365 CHANNELS:')
en = en.replace('Официальный API', 'Official Cloud API')
en = en.replace('Личные и бот', 'Personal & Bot API')
en = en.replace('Авто-ответ 24/7', '24/7 Fast Response')

en = en.replace('РЕАКТИВАЦИЯ АРХИВА', 'DATABASE REACTIVATION')
en = en.replace('Второе дыхание базы', 'Revitalizing Cold Databases')
en = en.replace('Уснувшие контакты возвращаются в диалог', 'Dormant contacts re-engage in active sales dialogues')
en = en.replace('через деликатные персонализированные касания без спама и раздражения', 'through tailored, high-value touches without spam or annoyance')
en = en.replace('Уснувшая база', 'Dormant base')
en = en.replace('Успешная оплата', 'Paid deals')
en = en.replace('800 контактов', '800 contacts')
en = en.replace('+1.8M ₽', '+$24,000')

en = en.replace('АВТОНОМНАЯ CRM', 'AUTONOMOUS CRM')
en = en.replace('Сделки двигаются сами', 'Deals Advance Automatically')
en = en.replace('Система протоколирует договоренности, выставляет счета и', 'The system records commitments, issues invoices, and')
en = en.replace('автоматически переводит этап сделки по воронке без участия человека', 'automatically shifts deal stages through the funnel without human effort')
en = en.replace('Этап 1', 'Stage 1')
en = en.replace('Скоринг', 'Scoring')
en = en.replace('Этап 2', 'Stage 2')
en = en.replace('Расчет КП', 'Quote & Specs')
en = en.replace('Финал', 'Final')
en = en.replace('Оплачено ✓', 'Paid ✓')
en = en.replace('Сквозная синхронизация', 'Full-stack Sync')

# Dialogue Simulator
en = en.replace('Психология коммуникации', 'Real-Time Communication')
en = en.replace('в реальном времени', 'Psychology & Tone')
en = en.replace('Автономная генерация ответов 0.8с', 'Autonomous response 0.8s')
en = en.replace('Диалог ведется на основе регламентов вашего бизнеса', 'Conversations adhere strictly to your business rules and knowledge base')
en = en.replace(', без пауз, раздражения и глупых опечаток нанятых стажеров.', ', free from pauses, fatigue, or rookie mistakes.')
en = en.replace('ПЕРЕХОД К ОПЛАТЕ', 'CLOSE & PAYMENT')
en = en.replace('Сделка за 3 реплики', 'Close in 3 Messages')
en = en.replace('ВЫЯВЛЕНИЕ ПОТРЕБНОСТИ', 'NEEDS DISCOVERY')
en = en.replace('Консультация и подбор', 'Consultation & Matching')
en = en.replace('ОТРАБОТКА ВОЗРАЖЕНИЯ', 'OBJECTION HANDLING')
en = en.replace('Защита базового прайса', 'Protecting Full Price')
en = en.replace('МАРКЕТПЛЕЙСЫ / DIRECT', 'MARKETPLACE / DIRECT')
en = en.replace('Подбор и оформление', 'Sizing & Fast Checkout')
en = en.replace('Эва // Altai Optima', 'Eva // Altai Optima')
en = en.replace('в сети • отклик 0.8с', 'online • 0.8s response')
en = en.replace('Клиент пишет ответ...', 'Client is typing...')
en = en.replace('Эва печатает ответ...', 'Eva is typing...')
en = en.replace('Ожидание реакции клиента...', 'Awaiting client response...')
en = en.replace('Обработка намерения лида (0.8c)...', 'Processing lead intent (0.8s)...')
en = en.replace('сделка закрыта ✓', 'deal closed ✓')

# Pipeline CRM section
en = en.replace('Пока менеджеры ленятся заполнять CRM', 'While human reps neglect CRM data entry')
en = en.replace('AI-сотрудник автоматически вносит 100%', 'AI Agent automatically logs 100% of dialogue data')
en = en.replace('данных из диалогов и двигает сделку по воронке', 'and drives the deal forward through the pipeline')
en = en.replace('Егоров Ренат (AI Altai)', 'Renat Egorov (AI Altai)')
en = en.replace('Отв-ный', 'Assignee')
en = en.replace('Раб. тел.', 'Work Phone')
en = en.replace('Email раб.', 'Work Email')
en = en.replace('Должность', 'Position')
en = en.replace('КОМПАНИЯ', 'COMPANY')
en = en.replace('Бюджет лида', 'Deal Budget')
en = en.replace('Сфера / Web', 'Industry')
en = en.replace('Адрес', 'Address')
en = en.replace('Статус в CRM', 'CRM Status')
en = en.replace('Автозаполнение всех полей в CRM', 'Autofill 100% fields in CRM')
en = en.replace('СИНХРОНИЗИРОВАНО', 'SYNCHRONIZED')
en = en.replace('ДВИЖЕНИЕ СДЕЛКИ В AMOCRM', 'PIPELINE FLOW IN CRM')
en = en.replace('Этапы воронки без зависаний', 'Seamless Funnel Velocity')
en = en.replace('ДЕНЬГИ НА СЧЕТУ', 'FUNDS IN ACCOUNT')
en = en.replace('Прайс защищен', 'Price Protected')
en = en.replace('100% полей в CRM', '100% Fields Logged')

# Cases section
en = en.replace('// РЕАЛЬНЫЕ КЕЙСЫ', '// REAL CASE STUDIES')
en = en.replace('Разборы внедрения', 'Proven Implementation Breakdown')
en = en.replace('автономного отдела продаж', 'of Autonomous AI Sales')
en = en.replace('B2B Опт & Поставки', 'B2B Wholesale & Supply')
en = en.replace('Металл, комплектующие', 'Industrial, Manufacturing')
en = en.replace('Недвижимость & КП', 'Real Estate & Land')
en = en.replace('Девелопмент, ЖК', 'Developments, Luxury')
en = en.replace('Автобизнес & Лизинг', 'Automotive & Fleet')
en = en.replace('Avito, спецтехника', 'Trucks, Heavy Equipment')
en = en.replace('B2B Консалтинг', 'B2B Consulting & Legal')
en = en.replace('Аудит, сложные услуги', 'Tax & Advisory Services')
en = en.replace('ЧИСТАЯ ВЫРУЧКА С AI', 'NET REVENUE WITH AI')
en = en.replace('РЕЗУЛЬТАТ', 'RESULTS')
en = en.replace('Открыть калькулятор', 'Open Calculator')
en = en.replace('Рассчитайте выгоду под вашу нишу:', 'Calculate revenue for your industry:')
en = en.replace('ДЕМОНСТРАЦИЯ СЦЕНАРИЯ', 'LIVE WORKFLOW DEMO')

# Calculator
en = en.replace('// МЫСЛИ ГЛОБАЛЬНО, ДЕЙСТВУЙ ЛОКАЛЬНО', '// THINK GLOBALLY, AUTOMATE DECISIVELY')
en = en.replace('Сколько чистой прибыли принесет', 'How Much Net Profit Will an')
en = en.replace('автономный отдел продаж?', 'Autonomous Sales Department Deliver?')
en = en.replace('Входящих заявок в месяц:', 'Monthly inbound leads:')
en = en.replace('лидов', 'leads')
en = en.replace('Средний чек сделки (₽):', 'Average deal value ($):')
en = en.replace('ЧИСТАЯ ПРИБЫЛЬ В МЕСЯЦ:', 'NET PROFIT PER MONTH:')
en = en.replace('ДОПОЛНИТЕЛЬНО В ГОД:', 'ADDITIONAL PER YEAR:')
en = en.replace('Зафиксировать эту прибыль для вашего бизнеса', 'Secure this profit for your business')

# Recruiter & Resume
en = en.replace('ИНТЕРАКТИВНЫЙ РЕКРУТЕР', 'INTERACTIVE RECRUITER')
en = en.replace('Ваш сотрудник может быть любым', 'Your AI Employee Can Be Anyone')
en = en.replace('Кликните на аватар, чтобы изучить резюме:', 'Click any avatar to inspect resume & voice persona:')
en = en.replace('ВЫБЕРИТЕ АВАТАР:', 'CHOOSE AVATAR:')
en = en.replace('10 ГОЛОСОВ', '10 VOICES')
en = en.replace('РЕЗЮМЕ СОТРУДНИКА', 'EMPLOYEE RESUME')
en = en.replace('СТАРШИЙ ВИЦЕ-ПРЕЗИДЕНТ ПО ПРОДАЖАМ', 'SENIOR VP OF SALES')
en = en.replace('Вся Россия, CRM', 'Global, CRM Cloud')
en = en.replace('Возраст:', 'Age:')
en = en.replace('лет', 'years')
en = en.replace('Готова к работе', 'Ready for deployment')
en = en.replace('Ключевые компетенции', 'Key Competencies')
en = en.replace('Условия и график', 'Terms & Schedule')
en = en.replace('Языки', 'Languages')
en = en.replace('О себе', 'About Me')
en = en.replace('Режим работы:', 'Schedule:')
en = en.replace('Результат:', 'Impact:')
en = en.replace('Зарплата:', 'Salary:')
en = en.replace('Владение:', 'Fluency:')
en = en.replace('Уровень:', 'Level:')
en = en.replace('7 170 языков', '7,170 languages')
en = en.replace('от 100 000 ₽', 'from $1,500/mo')
en = en.replace('+30% к прибыли', '+30% to revenue')

# Demo & Modal Form
en = en.replace('ПОДАРОК ПРИ ПОДКЛЮЧЕНИИ', 'SPECIAL BONUS ON ONBOARDING')
en = en.replace('Время убрать человеческий фактор из отдела продаж и забрать упущенную прибыль', 'Time to remove human error from sales and claim lost revenue')
en = en.replace('3 дня на настройку', '3-day full configuration & training')
en = en.replace('Сквозная интеграция с вашей CRM', 'Seamless integration into your CRM & channels')
en = en.replace('Никаких упущенных клиентов 24/7/365', 'Zero lost leads 24/7/365 guaranteed')
en = en.replace('ОБСУДИТЬ ДЕТАЛИ ПРОЕКТА', 'DISCUSS PROJECT & GET PILOT')
en = en.replace('Вставьте ссылку на сайт или опишите нишу', 'Enter your website or business niche')
en = en.replace('Телефон или Telegram для связи', 'Phone or Telegram handle')
en = en.replace('ЭКСКЛЮЗИВНЫЙ ПОДАРОК ПРИ ПОДКЛЮЧЕНИИ', 'EXCLUSIVE BONUS ON ONBOARDING')
en = en.replace('Бесплатная оцифровка и перенос базы из Excel в CRM', 'Free database digitization & transfer from Excel into CRM')
en = en.replace('ПОЛУЧИТЬ БЕСПЛАТНУЮ ОЦИФРОВКУ БАЗЫ', 'CLAIM FREE DATABASE DIGITIZATION')
en = en.replace('Заявка принята!', 'Application received!')
en = en.replace('Мы свяжемся с вами в течение 5 минут для демонстрации AI.', 'We will contact you within 5 minutes for a live AI demo.')

with open('en.html', 'w', encoding='utf-8') as f:
    f.write(en)
print("en.html generated successfully")

# ==========================================
# 2. GENERATE TURKISH VERSION (tr.html)
# ==========================================
tr = html

# Replace HTML tag & Meta Title
tr = tr.replace('<html lang="ru"', '<html lang="tr"')
tr = tr.replace('<title>Altai Optima — Autonomous AI Business Architecture</title>', '<title>Altai Optima — Otonom AI Satış Mimarisi</title>')

# Switcher active states
tr = tr.replace('<span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">RU</span>\n          <a href="en.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">EN</a>\n          <a href="tr.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">TR</a>',
                '<a href="index.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">RU</a>\n          <a href="en.html" class="px-2 py-0.5 rounded-full text-slate-600 hover:text-sky-600 transition">EN</a>\n          <span class="px-2 py-0.5 rounded-full bg-sky-600 text-white shadow-2xs">TR</span>')
tr = tr.replace('<span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">RU</span>\n            <a href="en.html" class="px-2 py-0.5 rounded-full hover:text-white transition">EN</a>\n            <a href="tr.html" class="px-2 py-0.5 rounded-full hover:text-white transition">TR</a>',
                '<a href="index.html" class="px-2 py-0.5 rounded-full hover:text-white transition">RU</a>\n            <a href="en.html" class="px-2 py-0.5 rounded-full hover:text-white transition">EN</a>\n            <span class="px-2 py-0.5 rounded-full bg-sky-500 text-white shadow-xs">TR</span>')
tr = tr.replace('<span class="px-3 py-1 rounded-full bg-sky-600 text-white">RU</span>\n        <a href="en.html" class="px-3 py-1 rounded-full bg-slate-100 text-slate-700 hover:bg-sky-50">EN</a>\n        <a href="tr.html" class="px-3 py-1 rounded-full bg-slate-100 text-slate-700 hover:bg-sky-50">TR</a>',
                '<a href="index.html" class="px-3 py-1 rounded-full bg-slate-100 text-slate-700 hover:bg-sky-50">RU</a>\n        <a href="en.html" class="px-3 py-1 rounded-full bg-slate-100 text-slate-700 hover:bg-sky-50">EN</a>\n        <span class="px-3 py-1 rounded-full bg-sky-600 text-white">TR</span>')

# Sticky Nav items
tr = tr.replace('>КЕЙСЫ<', '>BAŞARILAR<')
tr = tr.replace('>КАЛЬКУЛЯТОР<', '>HESAPLAYICI<')
tr = tr.replace('>АРХИТЕКТУРА<', '>MİMARİ<')
tr = tr.replace('>РЕЗЮМЕ<', '>ÖZGEÇMİŞ<')
tr = tr.replace('>РЕЗЮМЕ СОТРУДНИКА<', '>PERSONEL ÖZGEÇMİŞİ<')
tr = tr.replace('>ТЕСТОВЫЙ ЗАПУСК<', '>TEST PİLOTU<')
tr = tr.replace('>ТЕСТ<', '>TEST<')
tr = tr.replace('>ПОЛУЧИТЬ ПОДАРОК И ТЕСТ<', '>HEDİYE & TEST AL<')

# Hero Header and Top content
tr = tr.replace('Добрый день. Меня зовут Эва, как могу вам помочь?', 'İyi günler! Ben Eva, işletmenize nasıl yardımcı olabilirim?')
tr = tr.replace('Тестовый запуск', 'Test Pilotu')
tr = tr.replace('АВТОНОМНЫЙ', 'OTONOM')
tr = tr.replace('AI-ОТДЕЛ ПРОДАЖ', 'AI SATIŞ DEPARTMANI')
tr = tr.replace('Пока наемный персонал теряет прибыль компании, искусственный интеллект конвертирует каждый контакт в сделку', 'Personel şirketinizin kârını kaybederken, yapay zeka her teması satışa dönüştürür')
tr = tr.replace('Посмотреть выгоду', 'Kârı Hesapla')
tr = tr.replace('100% ВНИМАНИЯ', '%100 İLGİ')
tr = tr.replace(' К КАЖДОМУ КЛИЕНТУ', ' HER MÜŞTERİYE')
tr = tr.replace('Скролл вниз', 'Aşağı Kaydır')

# Points of revenue loss
tr = tr.replace('СКОЛЬКО ДЕНЕГ ВЫ ТЕРЯЕТЕ,', 'SATIŞ TEMSİLCİSİ GECİKİRKEN,')
tr = tr.replace('ПОКА МЕНЕДЖЕР ТОРМОЗИТ?', 'NE KADAR KÂR KAYBEDİYORSUNUZ?')
tr = tr.replace('// ПРАВИЛО 3-Х СЕКУНД В B2B И B2C', '// B2B VE B2C DE 3 SANİYE KURALI')
tr = tr.replace('СЛИВ КОНВЕРСИИ', 'DÖNÜŞÜM KAYBI')
tr = tr.replace('ОЖИДАНИЕ 2 ЧАСА', '2 SAAT BEKLEME')
tr = tr.replace('Кофе ценой в сделку', 'Satışa Mal Olan Kahve Molası')
tr = tr.replace('Горячая заявка остывает, пока сотрудник раскачивается с утра. Лид теряет интерес и при звонке сухо бросает: спасибо, уже неактуально.', 'Temsilci güne başlayana kadar sıcak müşteri soğur. Müşteri ilgisini kaybeder: "Teşekkürler, başka yerden aldık."')
tr = tr.replace('УТЕЧКА МАРЖИ', 'KÂR MARJI SIZINTISI')
tr = tr.replace('ПЕРЕГОВОРЫ', 'MÜZAKERELER')
tr = tr.replace('Скидка из слабости', 'Çaresizlikten Verilen İndirim')
tr = tr.replace('Сотрудник пугается возражения дорого и раздает скидки за счет вашей прибыли, вместо аргументации ценности и удержания полной маржи.', 'Temsilci "pahalı" itirazından korkup şirket kârından indirim dağıtır, oysa ürün değerini savunmalıdır.')
tr = tr.replace('А МОЖЕТЕ ПОЛУЧАТЬ...', 'VEYA ŞUNU KAZANABİLİRSİNİZ...')

# Manifesto section
tr = tr.replace('+30% К ВЫРУЧКЕ', '+%30 NET CİRO')
tr = tr.replace('Оптимизируем каждый этап вашей воронки и', 'Satış huninizin her aşamasını optimize ediyor ve')
tr = tr.replace('выжимаем максимум чистой прибыли из входящего потока', 'gelen her talepten maksimum net kâr elde ediyoruz')
tr = tr.replace('Мгновенный захват горячего клиента', 'Sıcak Müşteriyi Anında Yakalama')
tr = tr.replace('СЕКУНДЫ', 'SANİYE')
tr = tr.replace('ВРЕМЯ ОТКЛИКА 24/7', '24/7 YANIT HIZI')
tr = tr.replace('Захват лида за 0.8 секунды', '0.8 saniyede talep yakalama')
tr = tr.replace('Пока конкуренты открывают CRM, ваш AI уже презентовал продукт и выставил счет', 'Rakipleriniz CRM açana kadar yapay zekanız ürünü tanıttı ve faturayı kesti')

# Solution Bento cards
tr = tr.replace('// АРХИТЕКТУРА СИСТЕМЫ', '// SİSTEM MİMARİSİ')
tr = tr.replace('Четыре контура автономных продаж', 'Otonom Satışın Dört Temel Direği')
tr = tr.replace('ГОЛОСОВОЙ AI', 'SESLİ AI')
tr = tr.replace('Живая речь эксперта', 'Canlı Uzman Ses Tonu')
tr = tr.replace('Собеседник слышит уверенного менеджера с безупречной дикцией.', 'Arayan kişi kusursuz diksiyonlu, güven veren bir uzman duyar.')
tr = tr.replace('AI-продавец мгновенно считывает микропаузы,', 'AI konuşmadaki mikro duraklamaları anında analiz eder,')
tr = tr.replace('снимает возражения и ведет коммуникацию человеческим голосом и подачей', 'itirazları çözer ve doğal insan tonuyla satışı yönlendirir')
tr = tr.replace('Естественные интонации и контекстная память', 'Doğal tonlama ve kalıcı hafıza')
tr = tr.replace('100% фокус на продаже', 'Satışa %100 odaklanma')

tr = tr.replace('ВСЕ МЕССЕНДЖЕРЫ', 'TÜM MESAJLAŞMA KANALLARI')
tr = tr.replace('Мгновенный ответ в любом удобном для клиента мессенджере', 'Müşterinin tercih ettiği kanalda anında yanıt')
tr = tr.replace('КАНАЛЫ СВЯЗИ 24/7/365:', '7/24/365 İLETİŞİM KANALLARI:')
tr = tr.replace('Официальный API', 'Resmi API')
tr = tr.replace('Личные и бот', 'Bireysel & Bot')
tr = tr.replace('Авто-ответ 24/7', '7/24 Otomatik Yanıt')

tr = tr.replace('РЕАКТИВАЦИЯ АРХИВА', 'VERİ TABANI CANLANDIRMA')
tr = tr.replace('Второе дыхание базы', 'Eski Müşterilere İkinci Nefes')
tr = tr.replace('Уснувшие контакты возвращаются в диалог', 'Hareketsiz müşteriler yeniden sıcak satışa döner')
tr = tr.replace('через деликатные персонализированные касания без спама и раздражения', 'spam olmadan, son derece kibar ve kişiselleştirilmiş temaslarla')
tr = tr.replace('Уснувшая база', 'Eski liste')
tr = tr.replace('Успешная оплата', 'Ödenen satış')
tr = tr.replace('800 контактов', '800 müşteri')
tr = tr.replace('+1.8M ₽', '+750.000 ₺')

tr = tr.replace('АВТОНОМНАЯ CRM', 'OTONOM CRM')
tr = tr.replace('Сделки двигаются сами', 'Satışlar Kendi Kendine İlerler')
tr = tr.replace('Система протоколирует договоренности, выставляет счета и', 'Sistem anlaşmaları kaydeder, teklif ve fatura oluşturur ve')
tr = tr.replace('автоматически переводит этап сделки по воронке без участия человека', 'satış aşamasını insan müdahalesi olmadan otomatik ilerletir')
tr = tr.replace('Этап 1', 'Aşama 1')
tr = tr.replace('Скоринг', 'Skorlama')
tr = tr.replace('Этап 2', 'Aşama 2')
tr = tr.replace('Расчет КП', 'Teklif')
tr = tr.replace('Финал', 'Sonuç')
tr = tr.replace('Оплачено ✓', 'Ödendi ✓')
tr = tr.replace('Сквозная синхронизация', 'Uçtan Uca Senkron')

# Dialogue Simulator
tr = tr.replace('Психология коммуникации', 'Gerçek Zamanlı İletişim')
tr = tr.replace('в реальном времени', 'Psikolojisi ve Tonu')
tr = tr.replace('Автономная генерация ответов 0.8с', '0.8s otonom yanıt üretimi')
tr = tr.replace('Диалог ведется на основе регламентов вашего бизнеса', 'Görüşmeler şirketinizin kuralları ve ürün bilgisiyle yürütülür')
tr = tr.replace(', без пауз, раздражения и глупых опечаток нанятых стажеров.', ', duraksama, yorgunluk ve amatör hatalar olmadan.')
tr = tr.replace('ПЕРЕХОД К ОПЛАТЕ', 'ÖDEME VE KAPANMA')
tr = tr.replace('Сделка за 3 реплики', '3 Mesajda Satış')
tr = tr.replace('ВЫЯВЛЕНИЕ ПОТРЕБНОСТИ', 'İHTİYAÇ BELİRLEME')
tr = tr.replace('Консультация и подбор', 'Danışmanlık ve Seçim')
tr = tr.replace('ОТРАБОТКА ВОЗРАЖЕНИЯ', 'İTİRAZ YÖNETİMİ')
tr = tr.replace('Защита базового прайса', 'Fiyatın Korunması')
tr = tr.replace('МАРКЕТПЛЕЙСЫ / DIRECT', 'PAZARYERİ / DIRECT')
tr = tr.replace('Подбор и оформление', 'Beden ve Hızlı Sipariş')
tr = tr.replace('Эва // Altai Optima', 'Eva // Altai Optima')
tr = tr.replace('в сети • отклик 0.8с', 'çevrimiçi • 0.8s yanıt')
tr = tr.replace('Клиент пишет ответ...', 'Müşteri yazıyor...')
tr = tr.replace('Эва печатает ответ...', 'Eva yazıyor...')
tr = tr.replace('Ожидание реакции клиента...', 'Müşteri yanıtı bekleniyor...')
tr = tr.replace('Обработка намерения лида (0.8c)...', 'Niyet analiz ediliyor (0.8s)...')
tr = tr.replace('сделка закрыта ✓', 'satış tamamlandı ✓')

# Pipeline CRM section
tr = tr.replace('Пока менеджеры ленятся заполнять CRM', 'Temsilciler CRM doldurmayı ihmal ederken')
tr = tr.replace('AI-сотрудник автоматически вносит 100%', 'AI Ajanı diyalog verilerinin %100\'ünü kaydeder')
tr = tr.replace('данных из диалогов и двигает сделку по воронке', 've satışı hunide otomatik olarak ilerletir')
tr = tr.replace('Егоров Ренат (AI Altai)', 'Murat Yılmaz (AI Altai)')
tr = tr.replace('Отв-ный', 'Sorumlu')
tr = tr.replace('Раб. тел.', 'İş Tel')
tr = tr.replace('Email раб.', 'İş E-posta')
tr = tr.replace('Должность', 'Pozisyon')
tr = tr.replace('КОМПАНИЯ', 'ŞİRKET')
tr = tr.replace('Бюджет лида', 'Bütçe')
tr = tr.replace('Сфера / Web', 'Sektör / Web')
tr = tr.replace('Адрес', 'Adres')
tr = tr.replace('Статус в CRM', 'CRM Durumu')
tr = tr.replace('Автозаполнение всех полей в CRM', 'CRM\'de %100 otomatik doldurma')
tr = tr.replace('СИНХРОНИЗИРОВАНО', 'SENKRONİZE')
tr = tr.replace('ДВИЖЕНИЕ СДЕЛКИ В AMOCRM', 'CRM İÇİNDE SATIŞ HAREKETİ')
tr = tr.replace('Этапы воронки без зависаний', 'Takılmayan Satış Aşamaları')
tr = tr.replace('ДЕНЬГИ НА СЧЕТУ', 'PARA HESAPTA')
tr = tr.replace('Прайс защищен', 'Fiyat Korundu')
tr = tr.replace('100% полей в CRM', '%100 Alan Kaydedildi')

# Cases section
tr = tr.replace('// РЕАЛЬНЫЕ КЕЙСЫ', '// GERÇEK BAŞARI HİKAYELERİ')
tr = tr.replace('Разборы внедрения', 'Otonom Satış Departmanı')
tr = tr.replace('автономного отдела продаж', 'Entegrasyon Analizleri')
tr = tr.replace('B2B Опт & Поставки', 'B2B Toptan & Tedarik')
tr = tr.replace('Металл, комплектующие', 'Demir-Çelik, Parça')
tr = tr.replace('Недвижимость & КП', 'Gayrimenkul & Proje')
tr = tr.replace('Девелопмент, ЖК', 'Konut, Villa Projeleri')
tr = tr.replace('Автобизнес & Лизинг', 'Otomotiv & Filo')
tr = tr.replace('Avito, спецтехника', 'Tır, İş Makineleri')
tr = tr.replace('B2B Консалтинг', 'B2B Danışmanlık & Hukuk')
tr = tr.replace('Аудит, сложные услуги', 'Vergi ve Denetim')
tr = tr.replace('ЧИСТАЯ ВЫРУЧКА С AI', 'AI İLE NET CİRO')
tr = tr.replace('РЕЗУЛЬТАТ', 'SONUÇ')
tr = tr.replace('Открыть калькулятор', 'Hesaplayıcıyı Aç')
tr = tr.replace('Рассчитайте выгоду под вашу нишу:', 'Sektörünüze özel kârı hesaplayın:')
tr = tr.replace('ДЕМОНСТРАЦИЯ СЦЕНАРИЯ', 'CANLI SENARYO DEMOSU')

# Calculator
tr = tr.replace('// МЫСЛИ ГЛОБАЛЬНО, ДЕЙСТВУЙ ЛОКАЛЬНО', '// KÜRESEL DÜŞÜN, OTONOM HAREKET ET')
tr = tr.replace('Сколько чистой прибыли принесет', 'Otonom Satış Departmanı')
tr = tr.replace('автономный отдел продаж?', 'Ne Kadar Net Kâr Sağlar?')
tr = tr.replace('Входящих заявок в месяц:', 'Aylık gelen müşteri talebi:')
tr = tr.replace('лидов', 'talep')
tr = tr.replace('Средний чек сделки (₽):', 'Ortalama satış tutarı (₺):')
tr = tr.replace('ЧИСТАЯ ПРИБЫЛЬ В МЕСЯЦ:', 'AYLIK NET KÂR:')
tr = tr.replace('ДОПОЛНИТЕЛЬНО В ГОД:', 'YILLIK EK KÂR:')
tr = tr.replace('Зафиксировать эту прибыль для вашего бизнеса', 'Bu kârı işletmeniz için sabitleyin')

# Recruiter & Resume
tr = tr.replace('ИНТЕРАКТИВНЫЙ РЕКРУТЕР', 'İNTERAKTİF İŞE ALIM UZMANI')
tr = tr.replace('Ваш сотрудник может быть любым', 'Yapay Zeka Temsilcinizi Seçin')
tr = tr.replace('Кликните на аватар, чтобы изучить резюме:', 'Özgeçmiş ve ses tonunu incelemek için avatara tıklayın:')
tr = tr.replace('ВЫБЕРИТЕ АВАТАР:', 'AVATAR SEÇİN:')
tr = tr.replace('10 ГОЛОСОВ', '10 FARKLI SES')
tr = tr.replace('РЕЗЮМЕ СОТРУДНИКА', 'PERSONEL ÖZGEÇMİŞİ')
tr = tr.replace('СТАРШИЙ ВИЦЕ-ПРЕЗИДЕНТ ПО ПРОДАЖАМ', 'SATIŞTAN SORUMLU KIDEMLİ BAŞKAN YARDIMCISI')
tr = tr.replace('Вся Россия, CRM', 'Bulut CRM / Global')
tr = tr.replace('Возраст:', 'Yaş:')
tr = tr.replace('лет', 'yaşında')
tr = tr.replace('Готова к работе', 'Gereksiz bekleme olmadan hazır')
tr = tr.replace('Ключевые компетенции', 'Yetkinlikler')
tr = tr.replace('Условия и график', 'Çalışma Şartları')
tr = tr.replace('Языки', 'Diller')
tr = tr.replace('О себе', 'Hakkında')
tr = tr.replace('Режим работы:', 'Çalışma:')
tr = tr.replace('Результат:', 'Kâr Artışı:')
tr = tr.replace('Зарплата:', 'Maliyet:')
tr = tr.replace('Владение:', 'Diller:')
tr = tr.replace('Уровень:', 'Seviye:')
tr = tr.replace('7 170 языков', '7.170 dil')
tr = tr.replace('от 100 000 ₽', 'Aylık sabit')
tr = tr.replace('+30% к прибыли', '+%30 ciro artışı')

# Demo & Modal Form
tr = tr.replace('ПОДАРОК ПРИ ПОДКЛЮЧЕНИИ', 'BAŞLANGIÇ HEDİYESİ')
tr = tr.replace('Время убрать человеческий фактор из отдела продаж и забрать упущенную прибыль', 'Satıştan insan hatalarını çıkarmanın ve kaçan kârı geri almanın tam zamanı')
tr = tr.replace('3 дня на настройку', '3 günde tam kurulum ve eğitim')
tr = tr.replace('Сквозная интеграция с вашей CRM', 'CRM ve iletişim kanallarıyla tam entegrasyon')
tr = tr.replace('Никаких упущенных клиентов 24/7/365', '7/24/365 sıfır müşteri kaybı')
tr = tr.replace('ОБСУДИТЬ ДЕТАЛИ ПРОЕКТА', 'PROJEYİ GÖRÜŞÜN & TESTİ BAŞLATIN')
tr = tr.replace('Вставьте ссылку на сайт или опишите нишу', 'Web sitenizi veya sektörünüzü yazın')
tr = tr.replace('Телефон или Telegram для связи', 'Telefon veya Telegram kullanıcı adı')
tr = tr.replace('ЭКСКЛЮЗИВНЫЙ ПОДАРОК ПРИ ПОДКЛЮЧЕНИИ', 'ÖZEL ENTEGRASYON HEDİYESİ')
tr = tr.replace('Бесплатная оцифровка и перенос базы из Excel в CRM', 'Excel müşteri tabanınızı CRM\'e ücretsiz aktarım')
tr = tr.replace('ПОЛУЧИТЬ БЕСПЛАТНУЮ ОЦИФРОВКУ БАЗЫ', 'ÜCRETSİZ VERİ AKTARIMI ALIN')
tr = tr.replace('Заявка принята!', 'Başvurunuz Alındı!')
tr = tr.replace('Мы свяжемся с вами в течение 5 минут для демонстрации AI.', 'Yapay zeka canlı demosu için 5 dakika içinde sizinle iletişime geçeceğiz.')

with open('tr.html', 'w', encoding='utf-8') as f:
    f.write(tr)
print("tr.html generated successfully")
